import {chromium} from '@playwright/test';
import {preview} from 'vite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const live=process.env.TEST_URL,server=live?null:await preview({preview:{host:'127.0.0.1',port:5181,strictPort:true}});
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TEST_CHROMIUM_PATH?{executablePath:process.env.TEST_CHROMIUM_PATH}:{}),...(live&&process.env.HTTPS_PROXY?{proxy:{server:process.env.HTTPS_PROXY}}:{})});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,ignoreHTTPSErrors:true});
const page=await context.newPage(),errors=[],dialogs=[],missing=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{dialogs.push(d.message());void d.dismiss();});page.on('request',r=>{if(/\/books\/.*\.pdf/.test(r.url()))missing.push(r.url());});
fs.mkdirSync('tmp/qa',{recursive:true});
const button=name=>page.getByRole('button',{name,exact:true});
async function nav(name){const m=page.getByRole('navigation',{name:'Navegación móvil',exact:true});await (await m.isVisible()?m:page.getByRole('navigation',{name:'Navegación principal',exact:true})).getByRole('button',{name,exact:true}).click();}
async function overflow(label){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,label);}
const course=c=>page.getByRole('combobox',{name:'Elegir curso'}).selectOption(c);
async function select(c,code,id){await nav('Practicar');await course(c);await page.getByLabel('Semana de Book Exam').selectOption('all');await page.getByLabel('Tema de Book Exam').selectOption('all');await page.getByLabel('Sección de Book Exam').selectOption(code);await page.getByLabel('Problema de Book Exam').selectOption(id);await page.locator('.book-problem').waitFor();}
async function original(c){await page.locator('.book-problem-original>summary').click();const views=page.locator('.book-original');await views.first().waitFor();if(!await views.first().locator('img').count()){
 const file=process.env[c==='precalculo'?'TEST_PRECALC_BOOK':'TEST_DISCRETA_BOOK'];assert.ok(file,'Source PDF required for full verification');await views.first().locator('input[type=file]').setInputFiles(file);
 }
 await views.first().locator('img').waitFor({timeout:45000});assert.match(await views.first().locator('.original-status').innerText(),/original|verificada/);await views.first().getByRole('button',{name:'Ampliar original',exact:true}).click();await page.getByRole('dialog',{name:'Página de tu copia'}).waitFor();await button('Volver a resolver').click();}
try{
 await page.goto(live||'http://127.0.0.1:5181/');await page.getByRole('heading',{name:'Tu ruta de aprendizaje'}).waitFor();await overflow('phone home');
 await button('Abrir Proposiciones y conectores').click();await page.getByRole('button',{name:'Ahora me toca practicar'}).waitFor();await button('Salir de la lección').click();await page.getByRole('dialog',{name:'¿Pausar esta sesión?'}).getByRole('button',{name:'Pausar y volver'}).click();
 await select('precalculo','1.4','precalculo-18-3a');assert.ok(await page.locator('.book-problem .katex').count());await original('precalculo');
 const editor=page.getByRole('textbox',{name:'Mi desarrollo',exact:true});await editor.fill('Paso 1\nPaso 2');await editor.focus();await editor.press('Enter');await editor.pressSequentially('Paso 3');
 await editor.evaluate(el=>{el.focus();el.setSelectionRange(4,4);el.dispatchEvent(new Event('select',{bubbles:true}));});await page.getByRole('group',{name:'Símbolos matemáticos'}).getByRole('button',{name:'x',exact:true}).tap();assert.equal(await editor.inputValue(),'Pasox 1\nPaso 2\nPaso 3');
 await button('Borrar').tap();assert.equal(await editor.inputValue(),'Paso 1\nPaso 2\nPaso 3');await button('Nueva línea').tap();await button('Deshacer').tap();await button('Rehacer').tap();assert.equal((await editor.inputValue()).split('\n').length,4);const draft=await editor.inputValue();
 await button('Guardar borrador').click();await button('Hecho por mí · sin corregir').click();await page.locator('.response-state.submitted').waitFor();assert.equal(await page.locator('.response-state.validated').count(),0);await overflow('phone free answer');await page.screenshot({path:'tmp/qa/book-flow-phone.png',fullPage:true});
 await nav('Aprender');await nav('Practicar');assert.equal(await editor.inputValue(),draft);await page.reload();await nav('Practicar');assert.equal(await editor.inputValue(),draft);await page.locator('.response-state.submitted').waitFor();await original('precalculo');
 await button('Siguiente problema').click();await page.getByRole('heading',{name:'Ejercicio 3b',exact:true}).waitFor();assert.equal(await editor.inputValue(),'');await button('Anterior').click();assert.equal(await editor.inputValue(),draft);
 await select('precalculo','1.4','precalculo-18-2');assert.equal(await page.locator('.book-given-table tbody tr').count(),6);await original('precalculo');await page.screenshot({path:'tmp/qa/book-table-phone.png',fullPage:true});await overflow('table phone');
 await select('discreta','1.1','discreta-37-7');await original('discreta');await page.screenshot({path:'tmp/qa/book-diagram-phone.png',fullPage:true});
 await select('discreta','1.4','discreta-73-1a');await page.locator('.reviewed-answer-panel>summary').click();await button('Resolver con corrección y explicación').click();await page.getByRole('textbox',{name:'Nueva línea de la demostración'}).waitFor();
 for(const [expression,rule] of [['¬R','Modus tollens'],['¬R∨¬S','Adición'],['¬(R∧S)','De Morgan'],['¬(¬P∨¬Q)','Modus tollens'],['P∧Q','De Morgan + doble negación'],['P','Simplificación']]){await page.getByRole('textbox',{name:'Nueva línea de la demostración'}).fill(expression);await button(rule).click();await button('Comprobar este paso').click();}
 await page.getByRole('heading',{name:'¡Bien razonado!'}).waitFor();await button('Ver respuesta').click();await page.getByRole('region',{name:'Respuesta explicada'}).waitFor();await button('Continuar').click();await button('Volver a mi ruta').click();await nav('Practicar');await page.locator('.response-state.validated').waitFor();
 await nav('Biblioteca');await button('Abrir Técnica · libro en texto').click();await page.getByRole('textbox',{name:'Buscar dentro del libro'}).fill('predicados');await page.getByLabel('Resultados de búsqueda').locator('button').first().waitFor();await page.getByRole('spinbutton',{name:'Página PDF',exact:true}).fill('73');await button('Ver página visual').click();await page.locator('.book-original img').waitFor({timeout:45000});await button('1.4 · ejercicio 1b').click();await page.getByRole('heading',{name:'Ejercicio 1b',exact:true}).waitFor();await button('Siguiente problema').click();await page.getByRole('heading',{name:'Ejercicio 1c',exact:true}).waitFor();
 for(const size of [{width:800,height:1280},{width:1280,height:800}]){await page.setViewportSize(size);await nav('Ajustes');await page.getByLabel('Modo oscuro').check();await nav('Practicar');await overflow(`tablet ${size.width}`);await page.screenshot({path:`tmp/qa/book-flow-dark-${size.width}.png`,fullPage:true});assert.equal(await page.locator('.katex-error').count(),0);}
 if(!live){await page.evaluate(async()=>navigator.serviceWorker.ready);await page.reload();await nav('Practicar');await context.setOffline(true);await page.reload();await nav('Practicar');await original('discreta');await page.getByLabel('Mi desarrollo').fill('Sin conexión\nConservo los pasos');await nav('Biblioteca');await button('Abrir Técnica · libro en texto').click();await page.getByRole('spinbutton',{name:'Página PDF',exact:true}).fill('94');await button('Ver página visual').click();await page.locator('.book-original img').first().waitFor({timeout:45000});await page.screenshot({path:'tmp/qa/book-flow-offline.png',fullPage:true});}
 assert.deepEqual(errors,[]);assert.deepEqual(dialogs,[]);assert.deepEqual(missing,[]);
 console.log('PASS: lesson → Book Exam, both exact PDFs, formula/table/diagram, multiline touch editor, cursor/backspace/undo/redo, saved states/resume, next/previous, reviewed proof/solution, Técnica search/page/practice, phone/tablet dark, no dialogs or missing PDF routes'+(live?' · production':' · offline reload/PDF/text/drafts'));
}catch(e){await page.screenshot({path:'tmp/qa/book-flow-failure.png',fullPage:true});console.error((await page.locator('body').innerText()).slice(0,3500));throw e;}
finally{await browser.close();if(server)await new Promise(r=>server.httpServer.close(r));}
