import { chromium } from '@playwright/test';
import { createServer } from 'vite';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const server=await createServer({server:{host:'127.0.0.1',port:5176,strictPort:true}});
await server.listen();
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TEST_CHROMIUM_PATH?{executablePath:process.env.TEST_CHROMIUM_PATH}:{})});
const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const page=await context.newPage(),errors=[];
page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.message);});page.on('dialog',d=>d.accept());
fs.mkdirSync('tmp/qa',{recursive:true});
const button=name=>page.getByRole('button',{name,exact:true});
const nav=async name=>{const mobile=page.getByRole('navigation',{name:'Navegación móvil',exact:true});await (await mobile.isVisible()?mobile:page.getByRole('navigation',{name:'Navegación principal',exact:true})).getByRole('button',{name,exact:true}).click();};
const progress=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mate-u-duo.v1')));
const noOverflow=async label=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label);
try {
  await page.goto('http://127.0.0.1:5176/');await button('Continuar mi ruta').waitFor();
  const route=page.locator('details.route-disclosure');assert.equal(await route.getAttribute('open'),null,'full route stays collapsed to keep home calm');assert.equal(await route.locator('.level-card').count(),0);
  await route.locator('summary').click();assert.equal(await route.locator('.level-card').count(),22);
  await button('Guardar Proposiciones y conectores').click();await button('Guardados').click();
  assert.equal(await page.locator('.level-card').count(),1);
  await page.reload();const reloadedRoute=page.locator('details.route-disclosure');await reloadedRoute.locator('summary').click();await button('Guardados').click();assert.equal(await reloadedRoute.locator('.level-card').count(),1);
  await button('Guardados').click();await page.getByRole('textbox',{name:'Buscar un nivel'}).fill('bicondicional');
  assert.equal(await page.locator('.level-card').count(),1);await page.getByRole('textbox',{name:'Buscar un nivel'}).fill('');
  await button('Abrir Proposiciones y conectores').click();await button('Ahora me toca practicar').click();
  await button(/Cerrá la puerta\./).click();await button('Comprobar').click();await page.getByRole('heading',{name:'Todavía no. Probá otra vez.'}).waitFor();
  await button(/2 \+ 2 = 4/).click();await button('Comprobar').click();await button('Continuar').click();
  await button('P').tap();await button('Conjunción').tap();await button('Negación').tap();await button('Q').tap();
  const answer=page.getByRole('textbox',{name:'Tu respuesta',exact:true});assert.equal(await answer.inputValue(),'P∧¬Q');
  await button('Ver leyes').click();await page.getByRole('dialog').waitFor();
  await page.keyboard.press('Shift+Tab');assert.equal(await button('Volver al ejercicio').evaluate(el=>el===document.activeElement),true);
  await page.keyboard.press('Tab');assert.equal(await button('Cerrar leyes').evaluate(el=>el===document.activeElement),true);
  await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
  assert.equal(await button('Ver leyes').evaluate(el=>el===document.activeElement),true);
  await button('Ayuda guiada · 5').click();const spent=(await progress()).spentCoins;
  await button('Salir de la lección').click();await button('Retomar sesión').waitFor();await page.reload();await button('Retomar sesión').click();
  assert.equal(await answer.inputValue(),'P∧¬Q');assert.equal(await button('Ayuda guiada · 5').isDisabled(),true);
  assert.equal((await progress()).spentCoins,spent,'resuming does not charge the hint twice');
  await page.getByText('Veámoslo paso a paso',{exact:true}).waitFor();await page.screenshot({path:'tmp/qa/resumed-answer.png',fullPage:true});
  await button('Comprobar').click();await button('Continuar').click();await button(/F$/).click();await button('Comprobar').click();await button('Continuar').click();
  await page.getByRole('heading',{name:'Un paso más cerca.'}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('mate-u-duo.session.v1')),null);
  await button('Volver a mi ruta').click();await nav('Practicar');await button(/Diario de errores/).click();
  const mistake=page.locator('.mistake-card').first();assert.equal(await mistake.locator('.submitted-answer code').textContent(),'Cerrá la puerta.');
  await mistake.getByRole('button',{name:'Entender mi error'}).click();assert.equal(await mistake.locator('.journal-explanation code').textContent(),'2 + 2 = 4');
  await mistake.getByRole('button',{name:'Volver a intentarlo'}).click();await button(/2 \+ 2 = 4/).click();await button('Comprobar').click();await button('Continuar').click();await button('Volver a mi ruta').click();
  await nav('Practicar');await button(/Diario de errores/).click();await page.getByText('Resuelto sin ayuda',{exact:true}).waitFor();
  await page.screenshot({path:'tmp/qa/mistake-journal.png',fullPage:true});
  await button('Mi práctica').click();await button(/Una pausa/).click();await page.getByLabel('Tema',{exact:true}).selectOption('S1 · Lógica proposicional');await page.getByLabel('Dificultad',{exact:true}).selectOption('1');
  const start=page.getByRole('button',{name:/Empezar \d+ ejercicios/});assert.equal(await start.isEnabled(),true);
  const size=Number((await start.textContent()).match(/\d+/)[0]);assert(size>0&&size<=8);
  await start.click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mate-u-duo.session.v1')));assert.equal(saved.ids.length,size);
  await button('Salir de la lección').click();await nav('Cuaderno');await button('Explorar').click();
  await page.locator('.logic-output b').waitFor();assert.equal(await page.locator('.logic-output b').textContent(),'F');
  await button('Cambiar Q').tap();assert.equal(await page.locator('.logic-output b').textContent(),'V');assert.equal(await page.locator('.current-truth-row').count(),1);
  await button('Explorar De Morgan').click();assert.equal(await page.locator('.logic-output b').textContent(),'F');
  await page.locator('.custom-expression summary').click();await page.getByRole('textbox',{name:'Expresión para explorar'}).fill('P∧');assert.equal(await page.locator('.logic-output b').textContent(),'?');
  await button('Explorar Implicación').click();await noOverflow('logic mobile');
  await button('Conjuntos en vivo').click();await button('A ∩ B').click();assert.equal(await page.locator('.set-result b').textContent(),'{3}');
  await button('A contiene 3').tap();assert.equal(await page.locator('.set-result b').textContent(),'{∅}');await button('Aᶜ').click();assert.equal(await page.locator('.set-result b').textContent(),'{3, 4, 5, 6}');
  await page.getByRole('combobox',{name:'Elegir curso'}).selectOption('precalculo');await page.locator('.equation-solution').waitFor();
  assert.equal(await page.locator('.root-chips').textContent(),'x = -1x = 3');await button('Una raíz').click();assert.equal(await page.locator('.root-chips').textContent(),'x = 2');
  await button('Sin raíces').click();await page.getByRole('heading',{name:'No hay soluciones reales',exact:true}).waitFor();
  await page.getByRole('slider',{name:'Coeficiente a'}).fill('0');await page.getByRole('slider',{name:'Coeficiente b'}).fill('0');await page.getByRole('slider',{name:'Coeficiente c'}).fill('0');await page.getByRole('heading',{name:'Infinitas soluciones reales',exact:true}).waitFor();
  await page.getByRole('checkbox',{name:'Mostrar raíces y solución'}).uncheck();assert.equal(await page.locator('.equation-solution').count(),0);await button('Dos raíces').click();await page.getByRole('checkbox',{name:'Mostrar raíces y solución'}).check();await noOverflow('equation mobile');
  await page.screenshot({path:'tmp/qa/mobile-explorer.png',fullPage:true});
  for(const size of [{width:800,height:1280},{width:1024,height:768},{width:1280,height:800}]) {
    await page.setViewportSize(size);await nav('Ajustes');await page.getByLabel('Modo oscuro').check();await page.getByLabel('Tamaño de letra').fill('1.3');
    await nav('Cuaderno');await button('Explorar').click();await page.locator('.equation-graph').waitFor();await noOverflow(`equation ${size.width}`);
    await page.screenshot({path:`tmp/qa/explorer-${size.width}.png`,fullPage:true});
    await nav('Practicar');await page.locator('.session-builder').waitFor();await noOverflow(`practice ${size.width}`);
    await page.screenshot({path:`tmp/qa/practice-${size.width}.png`,fullPage:true});
    await nav('Aprender');const routeOnTablet=page.locator('details.route-disclosure');await routeOnTablet.locator('summary').click();assert.equal(await routeOnTablet.locator('.level-card').count(),25);await noOverflow(`levels ${size.width}`);
  }
  assert.deepEqual(errors,[],'uncaught browser exceptions');
  console.log('Experience QA passed: saved/searchable levels, touch answers, modal focus, paid hint and session recovery, actual-answer journal, adaptive filters, live logic/sets/equations, responsive tablet and large type.');
} catch(e) {await page.screenshot({path:'tmp/qa/experience-failure.png',fullPage:true});throw e;} finally {await browser.close();await server.close();}
