import fs from 'node:fs';
import {bookCatalog,pageInventory,reviewedActivities,assignmentLabel} from '../src/bookCatalog';
import {bank} from '../src/learning';
import {lessons} from '../src/content';
import {bookEditions} from '../src/bookEditions';
const list=(ns:number[])=>[...new Set(ns)].sort((a,b)=>a-b).join(', ');
let out='# Auditoría de digitalización\n\nFecha: 2026-10-07. Corte: Precálculo PDF 1–63; Discreta PDF 1–152 (impresa 150).\n\n';
out+='Se revisaron visualmente las **52 páginas de ejercicios** del inventario, con orden de problemas, incisos, ñ, subincisos romanos y continuaciones. El texto teórico extraído sigue siendo **auxiliar sin certificar**; no se declara revisada manualmente cada una de las 215 páginas del corte. La búsqueda y los ejemplos didácticos adaptados no convierten esa extracción en una edición matemática fiel.\n\n';
out+='## Cobertura por libro, semana y sección\n\nLas semanas confirmadas relacionan temas del material docente con el libro; no implican que el docente haya asignado todos los ejercicios de la sección. “B” organiza el libro sin afirmar una semana. “Apoyo” pertenece al corte, con semana sin confirmar. Los ejercicios fuera del corte no entran en este catálogo ni en sus estadísticas.\n\n';
out+='| Libro | Semana/bloque | Sección | PDF de ejercicios examinados | Problemas numerados¹ | Actividades (incisos/enteros) | Transcripciones revisadas | Originales² | Actividades con clave / prácticas revisadas³ |\n|---|---|---|---|---:|---:|---:|---|---:|\n';
const rows:any[]=[];
for(const course of ['precalculo','discreta'] as const){
 const items=bank(lessons,course),all=bookCatalog[course];
 for(const key of [...new Set(all.map(p=>`${p.sectionCode}|${p.week}`))]){
  const [code,week]=key.split('|'),ps=all.filter(p=>p.sectionCode===code&&p.week===week);
  const reviewed=ps.filter(p=>p.review==='reviewed').length,valid=ps.filter(p=>reviewedActivities(p,items).length).length,keys=new Set(ps.flatMap(p=>reviewedActivities(p,items).map(i=>i.question.id))).size;
  const pages=pageInventory.filter(r=>r.course===course&&r.sectionCode===code&&r.weeks.includes(week)).map(r=>r.page);
  rows.push({course,week,sectionCode:code,pages,problems:new Set(ps.map(p=>p.number)).size,activities:ps.length,transcriptionsReviewed:reviewed,originalsAfterImport:ps.length,activitiesWithKey:valid,reviewedPracticeVariants:keys});
  out+=`| ${course==='precalculo'?'Precálculo':'Discreta'} | ${assignmentLabel(week)} | ${code} · ${ps[0].section} | ${list(pages)} | ${new Set(ps.map(p=>p.number)).size} | ${ps.length} | ${reviewed}/${ps.length} | ${ps.length}/${ps.length} tras importar | ${valid} / ${keys} |\n`;
 }
}
out+='\n¹ Un problema con varios incisos se cuenta una sola vez dentro de una fila. Discreta 2.1 nº20 se reparte entre S3 y S4 y no debe sumarse dos veces en el total de problemas. Totales únicos: **28 problemas numerados / 164 actividades de Precálculo**, **180 / 362 de Discreta**.\n\n';
out+='² La disponibilidad visual depende de importar la edición correspondiente una vez en el navegador. **No hay PDF íntegro publicado ni ruta /books/*.pdf prometida.** El visor abre recorte o página completa dentro de la app; una copia con hash distinto se muestra completa con advertencia de edición sin verificar. Los datos se conservan en IndexedDB; borrar los datos del navegador elimina la copia.\n\n';
out+='³ Hay 59 prácticas ya revisadas (30 Precálculo, 29 Discreta); algunas son variantes de la misma actividad, como una tabla y una clasificación. Se conservan corrección, pistas, explicación, restricciones y requisitos de forma. **No se añadieron claves automáticas nuevas.** En el resto se practica respuesta libre sin corregir. “Hecho” no concede acierto ni XP; el verde se reserva para resultados del corrector existente.\n\n';
out+='## Inventario verificable por página\n\nFuente estructurada: [bookInventory.json](../src/bookInventory.json). Catálogo: [bookProblemCatalog.json](../src/bookProblemCatalog.json). `referencedBy` registra actividades que necesitan datos de la página aunque su inciso empiece en otra; `continuesFromPreviousPage` y `continuesOnNextPage` registran continuaciones. Páginas auxiliares con datos usados: Discreta 36 (Protágoras),40 (Vacilonia),72 (sistema formal), 131 (teorema decimal), 143 y 145 (inclusión-exclusión).\n\n| Libro | PDF / impresa | Sección | Incisos o problemas que empiezan aquí, en orden | Continúa desde / hacia la página contigua |\n|---|---|---|---|---|\n';
for(const r of [...pageInventory].sort((a,b)=>a.course.localeCompare(b.course)||a.page-b.page))out+=`| ${r.course} | ${r.page} / ${r.printedPage} | ${r.sectionCode} | ${r.labels.join(', ')||'Sin inicio; continuación'} | ${r.continuesFromPreviousPage.join(', ')||'—'} / ${r.continuesOnNextPage.join(', ')||'—'} |\n`;
out+='\n## Relación con el material semanal\n\n| Material disponible | Temas comprobados | Relación con el libro | Asignación expresa o coincidencia verificada |\n|---|---|---|---|\n';
out+='| Discreta S1, 13 páginas | Proposiciones, conectivas, tablas, simplificación | 1.2: PDF46–58; 1.3:59–63 | 1.2:1b,8b,11b,11d,11e coinciden con actividades de clase. Otros ejercicios docentes son variantes; no se igualan automáticamente. |\n';
out+='| Discreta S2, 10 páginas | Circuitos e inferencias | 1.4:64–78 | 1.4:1a,1f,1i,1j,1m,1p,3d,3f,3j coinciden. El inciso U de clase usa P∨T, mientras el libro usa P∧T: se conserva la diferencia. |\n';
out+='| Discreta S3, 10 páginas | Predicados, universos, cuantificadores y negación | 1.6:83–97; además 2.1 nº20 | 1.6:1a,1b,1d,1f,1g,1h,1i,2a,2b.i–iv; 2.1:20a,20c. Estos dos últimos se etiquetan S3 aunque estén en el capítulo de conjuntos. |\n';
out+='| Discreta S4, 18 páginas | Pertenencia, inclusión, operaciones con y sin diagramas | 2.1:111–128;2.3:135–138;2.4:139–142 | Relación temática confirmada. No se declara asignada toda la sección del libro. Cardinalidad 2.5 queda con semana por confirmar. |\n';
out+='| Precálculo S4, 7 páginas | División sintética, simplificación, operaciones de fracciones y racionalización | 3.2.6:43–45;3.3:45–53;práctica3.3.5:52–53 | 1g,2f,2l,3k expresamente asignados en la página7 del material docente. |\n';
out+='\nNo se encontró material docente de Precálculo S1–S3 ni S5–S6 entre los archivos disponibles. Los bloques B1,B2,B3,B5 quedan sin equivalencia semanal certificada. Tampoco se asignan semanas nuevas a los complementos de Discreta. Los IDs históricos de rutas se conservan para reanudar exámenes anteriores. Las tarjetas y lecciones muestran la relación docente o el aviso de complemento/semana por confirmar; la relación auditada ejercicio→semana es la de Book Exam y esta tabla.\n\n';
out+='## Faltas y límites explícitos\n\n- **Tres actividades sin transcripción gráfica reconstruida**: Discreta1.1 nº7 y nº11, PDF39/impresa37, y nº29, PDF43/impresa41. Mantienen texto auxiliar y original privado; no se declaran transcripciones exactas.\n- **Texto de Técnica**: no se certificaron todas las fórmulas del texto teórico extraído. Está plegado y rotulado auxiliar, junto con ejemplos adaptados y acceso al original.\n- **Claves**: el resto del inventario carece de solución validada. Los ejercicios abiertos siguen abiertos. La comprobación de una transformación en el cuaderno no prueba la solución completa.\n- Discreta2.5 nº15 conserva la barra sobre P(A×B), con advertencia sobre el universo del complemento. Precálculo2.5 nº8 conserva la inconsistencia potencial entre grado del residuo y divisor. No se inventan respuestas para estas consignas.\n- No se certificó una equivalencia S5–S6; el adelanto solo se ofrece fuera del corte del libro y queda separado de Book Exam.\n\n';
out+='## Ediciones de referencia\n\n';for(const c of ['precalculo','discreta'] as const)out+=`- ${bookEditions[c].title}: SHA-256 \`${bookEditions[c].sha256}\`.\n`;
out+='\n## Reproducción y pruebas\n\nLa revisión humana está codificada en los scripts `review-*.py`; no es una certificación automática por OCR. Ejecute `audit-books.py` con ambas fuentes, después `review-precalculo.py` con Precálculo, `review-discreta.py`, `review-inference.py`, `review-quantifiers.py`, `review-sets.py`, `review-final-sections.py`, `finalize-audit.py`, `review-dependencies.py`, y `node --import tsx scripts/coverage.ts`. Los PDF se proporcionan localmente; no se incluyen en git.\n\nPruebas: `npm test`, `npm run build` y `tests/book-flow.mjs` con ambas ediciones mediante `TEST_PRECALC_BOOK` y `TEST_DISCRETA_BOOK`. La prueba de navegador recorre lección, ambos libros, fórmula/tabla/diagrama, teclado táctil, cursor, guardado/reanudación, corrector revisado, Técnica, tamaños390×844,800×1280,1280×800 y recarga sin conexión. El registro del despliegue se guarda separadamente en [DELIVERY.md](DELIVERY.md).\n';
fs.writeFileSync('docs/COVERAGE.md',out);fs.writeFileSync('docs/coverage.json',JSON.stringify(rows,null,2)+'\n');
console.log(rows);
