import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, Flame, GraduationCap, Home, Moon, RefreshCw, Settings, Star, Trophy, X, Coins, Download } from 'lucide-react';
import { lessons, courseInfo, sourceNotes } from './content';
import type { Lesson, Progress, Question } from './types';
import { dayKey, freshProgress, lessonMastery, loadProgress, recordAttempt, STORAGE_KEY, streak, validateProgress } from './progress';
import { Exercise } from './Exercise';
const Books = lazy(()=>import('./Books').then(m=>({default:m.Books})));
const BookOriginal=lazy(()=>import('./BookOriginal').then(m=>({default:m.BookOriginal})));
import { bookExercises } from './bookExercises';
import { Library } from './Library';
import { TopicIcon } from './TopicIcon';
import { palettes, validPalette, type Palette } from './palettes';
import { bank, dailyChallenge, latestAttempts, practicePlan, sessionSummary, type PracticeItem } from './learning';
import { makeSession, loadSession, saveSession, SESSION_KEY, type Session } from './sessions';
import { HomeDashboard } from './HomeDashboard';
import { LessonStory } from './LessonStory';
import { ConfirmDialog, type Confirmation } from './ConfirmDialog';
import { generateExam } from './exam';
import { ExamResults } from './ExamResults';
const PracticeHub=lazy(()=>import('./PracticeHub').then(m=>({default:m.PracticeHub})));
const navigation=[{id:'learn',label:'Aprender',icon:Home},{id:'practice',label:'Practicar',icon:RefreshCw},{id:'library',label:'Biblioteca',icon:GraduationCap},{id:'books',label:'Mi libro',icon:BookOpen},{id:'settings',label:'Ajustes',icon:Settings}];
function Mascot(){return <svg className="mascot" viewBox="0 0 160 170" aria-label="Milo, tu compañero de matemáticas" role="img"><ellipse cx="84" cy="156" rx="49" ry="8" fill="#30205820"/><path d="M38 51 Q23 9 51 30 L70 44 Q85 30 100 40 L124 26 Q141 19 130 65 Q149 92 136 131 Q117 155 66 149 Q30 143 29 103 Q24 70 38 51" fill="#d8f46d"/><path d="M37 53 Q35 23 51 39 L65 49 Q93 35 116 46 L129 35 L123 66 Q146 108 126 134 Q102 153 58 140 Q28 128 35 85Z" fill="#d8f46d" stroke="#b4d73f" strokeWidth="3"/><ellipse cx="70" cy="84" rx="12" ry="17" fill="white"/><ellipse cx="110" cy="84" rx="12" ry="17" fill="white"/><ellipse cx="74" cy="87" rx="5" ry="9" fill="#2c2441"/><ellipse cx="113" cy="87" rx="5" ry="9" fill="#2c2441"/><path d="M83 107 Q95 118 106 104" fill="none" stroke="#2c2441" strokeWidth="4" strokeLinecap="round"/><ellipse cx="56" cy="102" rx="9" ry="5" fill="#fa9eb3"/><ellipse cx="122" cy="102" rx="9" ry="5" fill="#fa9eb3"/><path d="M30 109 L14 99 M129 116 L145 104" stroke="#b4d73f" strokeWidth="9" strokeLinecap="round"/><path d="M72 146 L64 157 M110 145 L118 157" stroke="var(--button-accent)" strokeWidth="10" strokeLinecap="round"/><path d="M47 129 Q90 119 132 129 L132 139 Q86 130 48 140Z" fill="var(--button-accent)"/><text x="83" y="136" fill="white" fontSize="12" fontWeight="bold">π</text></svg>;}
export default function App(){
  const [p,setP]=useState<Progress>(loadProgress);const [tab,setTab]=useState('learn');const [session,setSession]=useState<Session|null>(null);const [index,setIndex]=useState(-1);const [result,setResult]=useState(false);const [storageError,setStorageError]=useState('');const [message,setMessage]=useState('');const [confirmation,setConfirmation]=useState<Confirmation|null>(null);const importRef=useRef<HTMLInputElement>(null);
  const [bookProblemId,setBookProblemId]=useState<string|undefined>();
  const [bookPage,setBookPage]=useState<number|undefined>();const [pending,setPending]=useState(loadSession);
  const course=courseInfo[p.course],path=useMemo(()=>lessons.filter(l=>l.course===p.course),[p.course]);const units=[...new Set(path.map(l=>l.unit))];const next=path.find(l=>!p.completed.includes(l.id))||path[0];const coins=Math.max(0,20+Math.floor(p.xp/5)-(p.spentCoins||0));
  const allItems=useMemo(()=>bank(lessons,p.course),[p.course]);
  const due=useMemo(()=>allItems.filter(i=>p.skills[i.question.id]&&Date.parse(p.skills[i.question.id].due)<=Date.now()),[p,allItems]);
  const errors=useMemo(()=>{const last=latestAttempts(p);return allItems.filter(i=>{const a=last.get(i.question.id);return a&&(!a.correct||a.assisted);});},[p,allItems]);
  useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(p));setStorageError('');}catch{setStorageError('El navegador no pudo guardar el avance. Exportá una copia antes de cerrar.');}document.documentElement.dataset.theme=p.dark?'dark':'light';const colors=palettes[validPalette(p.palette)];for(const [key,value] of Object.entries({'--purple':p.dark?colors.dark:colors.main,'--button-accent':colors.main,'--accent-deep':colors.deep,'--soft':p.dark?colors.night:colors.soft}))document.documentElement.style.setProperty(key,value);document.documentElement.style.setProperty('--font-scale',String(p.fontScale));document.documentElement.dataset.motion=p.reduceMotion?'reduce':'normal';},[p]);
  useEffect(()=>{if(!session||result)return;try{saveSession(session,index);setPending({session,index});}catch{setStorageError('No se pudo guardar la sesión. Conservá esta pestaña abierta.');}},[session,index,result]);
  function clearPending(){setPending(null);try{localStorage.removeItem(SESSION_KEY);for(const item of pending?.session.items||[])localStorage.removeItem(`mate-session-${pending!.session.id}-${item.question.id}`);}catch{}}
  function replacePaused(begin:()=>void){if(pending){setConfirmation({title:'¿Reemplazar la sesión pausada?',message:`Tenés «${pending.session.title}» guardada. Si empezás otra sesión, se borra el borrador de aquella.`,confirmLabel:'Empezar otra sesión',destructive:true,onConfirm:begin});}else begin();}
  function startItems(items:PracticeItem[],title:string,mode:string){if(!items.length){setMessage('No hay ejercicios pendientes con ese filtro.');return;}replacePaused(()=>{setBookProblemId(undefined);clearPending();setSession(makeSession(title,items,mode,p.xp));setIndex(0);setResult(false);window.scrollTo(0,0);});}
  function startExam(selectedUnits:string[]){try{const seed=crypto.randomUUID(),items=generateExam(p.course,selectedUnits,seed,lessons),exam=makeSession('Examen · 35 desafíos',items,'exam',p.xp);exam.examSeed=seed;exam.examUnits=selectedUnits;exam.examCourse=p.course;exam.examVersion=2;replacePaused(()=>{clearPending();setSession(exam);setIndex(0);setResult(false);window.scrollTo(0,0);});}catch(e){setMessage(e instanceof Error?e.message:'No se pudo preparar el examen.');}}
  function startLesson(l:Lesson){replacePaused(()=>{setBookProblemId(undefined);clearPending();setSession(makeSession(l.title,l.questions.map(question=>({lesson:l,question})),'lesson',p.xp,l));setIndex(-1);setResult(false);window.scrollTo(0,0);});}
  function startPractice(mode:string){const all=bank(lessons,p.course);startItems(mode==='review'?due:mode==='errors'?errors:mode==='daily'?dailyChallenge(all,p.course):practicePlan(all,p,mode==='quick'?3:mode==='exam'?18:8),({quick:'Una pausa para aprender',daily:'Reto del día',review:'Repaso espaciado',errors:'Aprender de mis errores',exam:'Simulacro de práctica'} as Record<string,string>)[mode]||'Práctica personalizada',mode);}
  function finish(){if(session?.lesson)setP(prev=>({...prev,completed:[...new Set([...prev.completed,session.lesson!.id])]}));setResult(true);setPending(null);try{localStorage.removeItem(SESSION_KEY);for(const item of session?.items||[])localStorage.removeItem(`mate-session-${session!.id}-${item.question.id}`);}catch{}}
  function favorite(id:string){setP(prev=>({...prev,favorites:prev.favorites?.includes(id)?prev.favorites.filter(x=>x!==id):[...(prev.favorites||[]),id]}));}
  function resume(){if(!pending)return;setP(prev=>({...prev,course:pending.session.items[0].lesson.course}));setSession(pending.session);setIndex(pending.index);setResult(false);window.scrollTo(0,0);}
  function advance(){if(session&&index+1<session.items.length)setIndex(index+1);else finish();window.scrollTo(0,0);}
  function exportData(){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mate-u-duo-${dayKey()}.json`;a.click();URL.revokeObjectURL(url);}
  async function importData(file:File){try{if(file.size>20*1024*1024)throw new Error('La copia supera 20 MB.');const v=validateProgress(JSON.parse(await file.text()));setConfirmation({title:'Importar copia',message:'Esto reemplaza tu avance y tus monedas actuales. Tus PDF y notas permanecen en este dispositivo.',confirmLabel:'Importar mi copia',onConfirm:()=>{clearPending();setP(v);setMessage('Copia importada.');}});}catch(e){setMessage(e instanceof Error?e.message:'No se pudo importar.');}}
  const completed=path.filter(l=>p.completed.includes(l.id)).length;const mastered=path.filter(l=>lessonMastery(p,l)===100).length;
  if(session){const item=session.items[index],summary=sessionSummary(p,session.items,session.started),lastAnswer=p.attempts.at(-1),answered=!!item&&lastAnswer?.questionId===item.question.id&&!!lastAnswer.correct&&Date.parse(lastAnswer.date)>=Date.parse(session.started),sessionPercent=result?100:(Math.max(0,index)+(answered?1:0))/session.items.length*100;return <div className="session-shell"><header className="session-header"><button onClick={()=>setConfirmation({title:'¿Pausar esta sesión?',message:'Tu ejercicio y tu respuesta quedan guardados para continuar después.',confirmLabel:'Pausar y volver',onConfirm:()=>setSession(null)})} aria-label="Salir de la lección"><X/></button><div className="progress-track" role="progressbar" aria-label="Avance de esta sesión" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(sessionPercent)}><div style={{width:`${sessionPercent}%`}}/></div><span className="session-count">{result?session.items.length:Math.max(0,index+1)} / {session.items.length}</span></header><main className={`session-content ${item?.question.bookSource&&!result?'has-book-exercise':''}`}>
    {result?(session.mode==='exam'?<ExamResults session={session} progress={p} onLeave={()=>{setSession(null);setTab('practice');}}/>:<section className="result card result-simple"><div className="celebration"><TopicIcon name="🎉" size={65}/></div><span className="eyebrow">SESIÓN COMPLETADA</span><h1>¡Bien hecho!</h1><p>Terminaste {session.items.length} ejercicios.</p><div className="result-simple-score"><b>{summary.clean}/{session.items.length}</b><span>al primer intento</span></div><details className="simple-more"><summary>Ver detalles</summary><p>+{p.xp-session.startingXP} XP · {summary.retries} reintentos · {summary.helped} con ayuda.</p><p>Para afianzar, volvé a resolverlos otro día sin pistas.</p></details><button className="primary" onClick={()=>{setSession(null);setTab('learn');}}>Seguir aprendiendo<ArrowRight size={18}/></button></section>):
      index<0&&session.lesson?<LessonStory key={session.id} lesson={session.lesson} onStart={()=>setIndex(0)}/>:
      item&&<><div className="exercise-meta"><span>{session.title}</span></div><div className={item.question.bookSource?"book-exercise-layout":""}>{item.question.bookSource&&<Suspense fallback={<aside className="card" role="status">Preparando el recorte del libro…</aside>}><BookOriginal key={item.lesson.course} source={item.question.bookSource}/></Suspense>}<Exercise key={`${session.id}-${item.question.id}-${index}`} draftKey={`mate-session-${session.id}-${item.question.id}`} question={item.question} course={item.lesson.course} rewardAvailable={!p.attempts.some(a=>a.questionId===item.question.id&&a.correct)} coins={coins} onSpend={n=>setP(prev=>({...prev,spentCoins:(prev.spentCoins||0)+n}))} onAttempt={(correct,assisted,details)=>setP(prev=>recordAttempt(prev,item.lesson,item.question,correct,assisted,new Date(),details))} onNext={advance}/></div></>}
    {storageError&&<p role="alert">{storageError}</p>}</main><ConfirmDialog value={confirmation} onClose={()=>setConfirmation(null)}/></div>;}
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('learn');}}><span>m<span className="brand-dot">•</span></span><div>mate<span>U DUO</span></div></a><nav aria-label="Navegación principal">{navigation.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>{setBookProblemId(undefined);setTab(n.id);setMessage('');window.scrollTo(0,0);}}><span className="nav-icon"><n.icon size={23} strokeWidth={2.7}/></span><span>{n.label}</span>{n.id==='practice'&&due.length>0&&<b>{due.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">S</div><div>Tu espacio de estudio<small>Progreso en este dispositivo</small></div></div></aside>
    <div className="main-shell"><header className="topbar"><span className="mobile-brand">mate <b>U DUO</b></span><label className="course-picker"><span>Tu curso</span><select aria-label="Elegir curso" value={p.course} onChange={e=>{setBookProblemId(undefined);setBookPage(undefined);setP({...p,course:e.target.value as Progress['course']});}}><option value="discreta">Matemática Discreta</option><option value="precalculo">Precálculo</option></select></label><div className="top-stats"><span title="Racha"><Flame size={20} color="#e77d32"/>{streak(p)}</span><span title="Experiencia"><Star size={20} color="#bd8b0c"/>{p.xp}</span><span title="Monedas ficticias"><Coins size={20} color="#168979"/>{coins}</span></div><button className="icon-button" aria-label="Cambiar tema claro u oscuro" onClick={()=>setP({...p,dark:!p.dark})}><Moon size={19}/></button></header>
    <div className="content-grid single"><main className="main-content">{message&&<p role="status" className="notice">{message}</p>}{storageError&&<p role="alert" className="notice">{storageError}</p>}
      {tab==='learn'&&<HomeDashboard progress={p} path={path} pending={pending} onLesson={startLesson} onResume={resume} onDiscard={()=>setConfirmation({title:'¿Descartar la sesión guardada?',message:'Se elimina el borrador de esa sesión. Tu avance anterior se conserva.',confirmLabel:'Descartar sesión',destructive:true,onConfirm:clearPending})} onFavorite={favorite}/>}
      {tab==='practice'&&<Suspense fallback={<p role="status">Preparando tu práctica…</p>}><PracticeHub key={`${p.course}-${bookProblemId||'saved'}`} initialBookProblem={bookProblemId} progress={p} pending={pending} onResume={resume} onStart={startItems} onExam={startExam} onLesson={startLesson} onRead={page=>{setBookPage(page);setTab('books');window.scrollTo(0,0);}}/></Suspense>}
      {tab==='library'&&<Library key={p.course} course={p.course} onProblem={id=>{setBookProblemId(id);setTab('practice');window.scrollTo(0,0);}} onPractice={startLesson} onRead={page=>{setBookPage(page);setTab('books');window.scrollTo(0,0);}}/>}
      {tab==='books'&&<Suspense fallback={<p role="status">Preparando tu libro…</p>}><Books key={p.course} course={p.course} initialPage={bookPage} onPageChange={setBookPage} onProblem={id=>{setBookProblemId(id);setTab('practice');window.scrollTo(0,0);}}/></Suspense>}
      {tab==='progress'&&<div className="simple-flow"><h1>Mi avance</h1><p>Tu progreso en este dispositivo.</p><div className="simple-stats"><div><b>{completed}/{path.length}</b><span>lecciones terminadas</span></div><div><b>{mastered}</b><span>temas dominados</span></div><div><b>{streak(p)}</b><span>días de racha</span></div></div><details className="simple-more"><summary>Ver avance por tema</summary><div className="simple-link-list">{path.map(l=><div key={l.id}><b>{l.title}</b><span>{lessonMastery(p,l)}% de dominio</span></div>)}</div></details><button className="secondary" onClick={()=>setTab('settings')}>Volver a Ajustes</button></div>}
      {tab==='settings'&&<div className="simple-flow"><h1>Ajustes</h1><button className="simple-link" onClick={()=>setTab('progress')}><Trophy size={20}/><span><b>Mi avance</b><small>{completed} lecciones terminadas</small></span><ChevronRight size={18}/></button><section className="card settings"><h2>Lectura</h2><div className="settings-controls"><label>Modo oscuro<input type="checkbox" checked={p.dark} onChange={e=>setP({...p,dark:e.target.checked})}/></label><label>Tamaño de letra<input type="range" min="1" max="1.3" step=".05" value={p.fontScale} onChange={e=>setP({...p,fontScale:Number(e.target.value)})}/></label></div></section><details className="simple-more"><summary>Copia y datos</summary><p>El avance y los PDF se guardan en este navegador. La copia JSON incluye el avance; el PDF permanece aparte.</p><div className="row wrap"><button className="secondary" onClick={exportData}><Download size={18}/> Exportar avance</button><button className="secondary" onClick={()=>importRef.current?.click()}>Importar copia</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importData(f);e.target.value='';}}/><button className="danger" onClick={()=>setConfirmation({title:'¿Reiniciar tu progreso?',message:'Se borran el avance y la sesión pausada. Tus libros y notas permanecen.',confirmLabel:'Reiniciar progreso',destructive:true,onConfirm:()=>{clearPending();setP(freshProgress());}})}>Reiniciar avance</button></div></details></div>}
    </main></div><ConfirmDialog value={confirmation} onClose={()=>setConfirmation(null)}/>
    <nav className="mobile-nav" aria-label="Navegación móvil">{navigation.map(n=><button className={tab===n.id||n.id==='settings'&&tab==='progress'?'active':''} key={n.id} onClick={()=>{setBookProblemId(undefined);setTab(n.id);window.scrollTo(0,0);}}><span className="nav-icon"><n.icon size={23} strokeWidth={2.7}/></span><span>{n.label}</span></button>)}</nav></div></div>;
}
