import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, Flame, GraduationCap, Home, Moon, RefreshCw, Settings, Sparkles, Star, Target, Trophy, X, Coins, Wrench, Download } from 'lucide-react';
import katex from 'katex';
import { lessons, courseInfo, sourceNotes } from './content';
import type { Lesson, Progress, Question } from './types';
import { dayKey, freshProgress, lessonMastery, loadProgress, recordAttempt, STORAGE_KEY, streak, validateProgress } from './progress';
import { shuffle } from './engine';
import { Exercise } from './Exercise';
import { Workbench } from './Workbench';
const Books = lazy(()=>import('./Books').then(m=>({default:m.Books})));
import { Proof } from './Proof';
import { Library } from './Library';
import { TopicIcon } from './TopicIcon';
type Session={title:string;items:{lesson:Lesson;question:Question}[];lesson?:Lesson;mode:string};
const navigation=[{id:'learn',label:'Aprender',icon:Home},{id:'practice',label:'Practicar',icon:RefreshCw},{id:'library',label:'Biblioteca',icon:GraduationCap},{id:'books',label:'Mi libro',icon:BookOpen},{id:'lab',label:'Cuaderno',icon:Wrench},{id:'progress',label:'Mi avance',icon:Trophy},{id:'settings',label:'Ajustes',icon:Settings}];
function MathLine({text}:{text:string}) { return <div className="math" dangerouslySetInnerHTML={{__html:katex.renderToString(text,{throwOnError:false,strict:false,displayMode:true})}}/>; }
function Mascot(){return <svg className="mascot" viewBox="0 0 160 170" aria-label="Milo, tu compañero de matemáticas" role="img"><ellipse cx="84" cy="156" rx="49" ry="8" fill="#30205820"/><path d="M38 51 Q23 9 51 30 L70 44 Q85 30 100 40 L124 26 Q141 19 130 65 Q149 92 136 131 Q117 155 66 149 Q30 143 29 103 Q24 70 38 51" fill="#d8f46d"/><path d="M37 53 Q35 23 51 39 L65 49 Q93 35 116 46 L129 35 L123 66 Q146 108 126 134 Q102 153 58 140 Q28 128 35 85Z" fill="#d8f46d" stroke="#b4d73f" strokeWidth="3"/><ellipse cx="70" cy="84" rx="12" ry="17" fill="white"/><ellipse cx="110" cy="84" rx="12" ry="17" fill="white"/><ellipse cx="74" cy="87" rx="5" ry="9" fill="#2c2441"/><ellipse cx="113" cy="87" rx="5" ry="9" fill="#2c2441"/><path d="M83 107 Q95 118 106 104" fill="none" stroke="#2c2441" strokeWidth="4" strokeLinecap="round"/><ellipse cx="56" cy="102" rx="9" ry="5" fill="#fa9eb3"/><ellipse cx="122" cy="102" rx="9" ry="5" fill="#fa9eb3"/><path d="M30 109 L14 99 M129 116 L145 104" stroke="#b4d73f" strokeWidth="9" strokeLinecap="round"/><path d="M72 146 L64 157 M110 145 L118 157" stroke="#7556ef" strokeWidth="10" strokeLinecap="round"/><path d="M47 129 Q90 119 132 129 L132 139 Q86 130 48 140Z" fill="#7556ef"/><text x="83" y="136" fill="white" fontSize="12" fontWeight="bold">π</text></svg>;}
export default function App(){
  const [p,setP]=useState<Progress>(loadProgress);const [tab,setTab]=useState('learn');const [session,setSession]=useState<Session|null>(null);const [index,setIndex]=useState(-1);const [result,setResult]=useState(false);const [storageError,setStorageError]=useState('');const [message,setMessage]=useState('');const [install,setInstall]=useState<any>(null);const importRef=useRef<HTMLInputElement>(null);
  const [bookPage,setBookPage]=useState<number|undefined>();
  const course=courseInfo[p.course],path=lessons.filter(l=>l.course===p.course);const units=[...new Set(path.map(l=>l.unit))];const next=path.find(l=>!p.completed.includes(l.id))||path[0];const coins=Math.max(0,20+Math.floor(p.xp/5)-(p.spentCoins||0));
  const due=useMemo(()=>path.flatMap(lesson=>lesson.questions.filter(q=>p.skills[q.id]&&Date.parse(p.skills[q.id].due)<=Date.now()).map(question=>({lesson,question}))),[p,path]);
  const errors=useMemo(()=>path.flatMap(lesson=>lesson.questions.filter(q=>{const a=p.attempts.filter(a=>a.questionId===q.id).at(-1);return a&&(!a.correct||a.assisted);}).map(question=>({lesson,question}))),[p,path]);
  const today=p.attempts.filter(a=>dayKey(new Date(a.date))===dayKey()).length;const mastered=path.filter(l=>lessonMastery(p,l)===100).length;
  useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(p));setStorageError('');}catch{setStorageError('El navegador no pudo guardar el avance. Exportá una copia antes de cerrar.');}document.documentElement.dataset.theme=p.dark?'dark':'light';document.documentElement.style.setProperty('--font-scale',String(p.fontScale));document.documentElement.dataset.motion=p.reduceMotion?'reduce':'normal';},[p]);
  useEffect(()=>{const handler=(e:Event)=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler);},[]);
  function startLesson(l:Lesson){setSession({title:l.title,lesson:l,mode:'lesson',items:l.questions.map(question=>({lesson:l,question}))});setIndex(-1);setResult(false);window.scrollTo(0,0);}
  function startPractice(mode:string){let items=mode==='review'?due:mode==='errors'?errors:path.flatMap(lesson=>lesson.questions.map(question=>({lesson,question})));items=shuffle(items).slice(0,mode==='exam'?18:mode==='diagnostic'?8:10);if(!items.length){setMessage('No hay ejercicios pendientes en esta categoría. Podés usar la práctica mixta.');return;}setSession({title:({review:'Repaso espaciado',errors:'Aprender de mis errores',exam:'Simulacro de práctica',diagnostic:'Punto de partida',mixed:'Práctica mixta'} as Record<string,string>)[mode],mode,items});setIndex(0);setResult(false);window.scrollTo(0,0);}
  function finish(){if(session?.lesson)setP(prev=>({...prev,completed:[...new Set([...prev.completed,session.lesson!.id])]}));setResult(true);}
  function advance(){if(session&&index+1<session.items.length)setIndex(index+1);else finish();window.scrollTo(0,0);}
  function exportData(){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mate-u-duo-${dayKey()}.json`;a.click();URL.revokeObjectURL(url);}
  async function importData(file:File){try{if(file.size>20*1024*1024)throw new Error('La copia supera 20 MB.');const v=validateProgress(JSON.parse(await file.text()));if(!window.confirm('¿Reemplazar tu progreso con esta copia?'))return;setP(v);setMessage('Copia importada.');}catch(e){setMessage(e instanceof Error?e.message:'No se pudo importar.');}}
  const completed=path.filter(l=>p.completed.includes(l.id)).length;
  if(session){const item=session.items[index];return <div className="session-shell"><header className="session-header"><button onClick={()=>{if(window.confirm('¿Salir de la sesión? Tus respuestas ya están guardadas.'))setSession(null);}} aria-label="Salir de la lección"><X/></button><div className="progress-track"><div style={{width:`${result?100:Math.max(0,index)/session.items.length*100}%`}}/></div><span><Coins size={18}/>{coins}</span><span className="infinite">∞</span></header><main className="session-content">
    {result?<section className="result card"><div className="celebration"><TopicIcon name="🎉" size={65}/></div><span className="eyebrow">SESIÓN COMPLETADA</span><h1>Un paso más cerca.</h1><p>Completaste {session.items.length} ejercicios de {session.title.toLowerCase()}.</p><div className="result-stats"><div><b>{p.xp}</b><small>XP total</small></div><div><b>{streak(p)}</b><small>días de racha</small></div><div><b>∞</b><small>oportunidades</small></div></div><p>Completar una lección es el primer paso. El dominio se confirma al resolver de nuevo, otro día y sin ayudas.</p><button className="primary" onClick={()=>{setSession(null);setTab('learn');}}>Volver a mi ruta<ArrowRight size={18}/></button></section>:
      index<0&&session.lesson?<section className="lesson-theory"><span className="eyebrow">{session.lesson.unit} · {session.lesson.minutes} MIN</span><div className="theory-icon"><TopicIcon name={session.lesson.icon} size={48}/></div><h1>{session.lesson.title}</h1>{session.lesson.theory.map(t=><p key={t}>{t}</p>)}<div className="formula-box">{session.lesson.formulas.map(f=><MathLine key={f} text={f}/>)}</div><section className="example"><h3>{session.lesson.example.title}</h3>{session.lesson.example.steps.map((s,i)=><div key={s}><span>{i+1}</span><p>{s}</p></div>)}</section><small>{session.lesson.source} · páginas {session.lesson.pages} · contenido adaptado</small><button className="primary wide" onClick={()=>setIndex(0)}>Ahora me toca practicar<ArrowRight size={18}/></button></section>:
      item&&<><div className="exercise-meta"><span>{session.title}</span><span>{index+1} / {session.items.length}</span></div><Exercise key={`${item.question.id}-${index}`} question={item.question} coins={coins} onSpend={n=>setP(prev=>({...prev,spentCoins:(prev.spentCoins||0)+n}))} onAttempt={(correct,assisted)=>setP(prev=>recordAttempt(prev,item.lesson,item.question,correct,assisted))} onNext={advance}/></>}
    {storageError&&<p role="alert">{storageError}</p>}</main></div>;}
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('learn');}}><span>m<span className="brand-dot">•</span></span><div>mate<span>U DUO</span></div></a><nav aria-label="Navegación principal">{navigation.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>{setTab(n.id);setMessage('');window.scrollTo(0,0);}}><n.icon size={21}/><span>{n.label}</span>{n.id==='practice'&&due.length>0&&<b>{due.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">S</div><div>Tu espacio de estudio<small>Progreso en este dispositivo</small></div></div></aside>
    <div className="main-shell"><header className="topbar"><span className="mobile-brand">mate <b>U DUO</b></span><label className="course-picker"><span>Tu curso</span><select aria-label="Elegir curso" value={p.course} onChange={e=>setP({...p,course:e.target.value as Progress['course']})}><option value="discreta">Matemática Discreta</option><option value="precalculo">Precálculo</option></select></label><div className="top-stats"><span title="Racha"><Flame size={20} color="#e77d32"/>{streak(p)}</span><span title="Experiencia"><Star size={20} color="#bd8b0c"/>{p.xp}</span><span title="Monedas ficticias"><Coins size={20} color="#168979"/>{coins}</span></div><button className="icon-button" aria-label="Cambiar tema claro u oscuro" onClick={()=>setP({...p,dark:!p.dark})}><Moon size={19}/></button></header>
    <div className={`content-grid ${tab!=='learn'?'single':''}`}><main className="main-content">{message&&<p role="status" className="notice">{message}</p>}{storageError&&<p role="alert" className="notice">{storageError}</p>}
      {tab==='learn'&&<><div className="page-heading"><div><span className="eyebrow">UN POQUITO CADA DÍA</span><h1>Tu próxima gran idea<br/>empieza por un paso.</h1><p>{course.subtitle}</p></div><span className="course-badge"><TopicIcon name={course.emoji} size={32}/></span></div><section className="mission"><div><span className="pill">TU MISIÓN DE HOY</span><h2>{completed===path.length?'Volvamos a conectar ideas':`Seguimos con ${next.title.toLowerCase()}`}</h2><p>Seis minutos. Un concepto. Más confianza.</p><button className="primary" onClick={()=>startLesson(next)}>Continuar mi ruta<ArrowRight size={18}/></button></div><Mascot/></section><div className="row route-heading"><h2>Tu ruta de aprendizaje</h2><span>{completed} / {path.length} lecciones</span></div><p className="route-note">Todas las lecciones están disponibles. Elegí el tema que necesitás hoy.</p>{units.map((u,ui)=><section className="unit" key={u}><div className="unit-title"><span>{String(ui+1).padStart(2,'0')}</span><div><h3>{u.split(' · ')[1]}</h3><small>{u.split(' · ')[0]} · {path.filter(l=>l.unit===u).length} lecciones</small></div><GraduationCap size={24}/></div><div className="lesson-path">{path.filter(l=>l.unit===u).map((l,i)=><div className={`path-stop offset-${i%4}`} key={l.id}><button className={`lesson-node ${p.completed.includes(l.id)?'done':''} ${l.id===next.id?'current':''}`} aria-label={`Abrir ${l.title}`} onClick={()=>startLesson(l)}>{p.completed.includes(l.id)?<Check size={30}/>:<span><TopicIcon name={l.icon}/></span>}</button><button className="lesson-label" onClick={()=>startLesson(l)}><b>{l.title}</b><small>{l.minutes} min · {p.completed.includes(l.id)?`completada · dominio ${lessonMastery(p,l)}%`:'por explorar'}</small></button></div>)}</div></section>)}<section className="card book-banner"><BookOpen size={28}/><div><h3>¿Tenés un ejercicio del libro?</h3><p>Abrilo y resolvelo con el cuaderno táctil.</p></div><button className="secondary" onClick={()=>setTab('books')}>Ir a mi libro<ChevronRight size={18}/></button></section></>}
      {tab==='practice'&&<><span className="eyebrow">RECUPERÁ LO QUE APRENDISTE</span><h1>Practicá a tu ritmo.</h1><p>Sin vidas que se agoten. Con explicación, pistas y espacio para volver a intentar.</p><div className="practice-grid">{[{mode:'review',icon:'🗓️',title:'Repaso espaciado',text:`${due.length} ejercicios listos para recordar.`},{mode:'errors',icon:'🌱',title:'Mis errores',text:`${errors.length} oportunidades para entender mejor.`},{mode:'mixed',icon:'🎲',title:'Práctica mixta',text:'Mezclá temas y construí conexiones.'},{mode:'diagnostic',icon:'🧭',title:'Punto de partida',text:'8 ejercicios para explorar tus fortalezas.'},{mode:'exam',icon:'🎯',title:'Simulacro',text:'18 ejercicios del banco. Formativo, sin límite de tiempo.'}].map(c=><button className="practice-card" key={c.mode} onClick={()=>startPractice(c.mode)}><span><TopicIcon name={c.icon} size={32}/></span><h3>{c.title}</h3><p>{c.text}</p><b>Empezar<ArrowRight size={18}/></b></button>)}</div><h2>Práctica por semana</h2>{units.map(u=><section className="card week-card" key={u}><h3>{u}</h3><div className="topic-list">{path.filter(l=>l.unit===u).map(l=><button key={l.id} onClick={()=>startLesson(l)}><TopicIcon name={l.icon} size={18}/> {l.title}<ChevronRight size={16}/></button>)}</div></section>)}</>}
      {tab==='library'&&<Library key={p.course} course={p.course} onPractice={startLesson} onRead={page=>{setBookPage(page);setTab('books');window.scrollTo(0,0);}}/>}
      {tab==='books'&&<Suspense fallback={<p role="status">Preparando tu libro…</p>}><Books key={p.course} course={p.course} initialPage={bookPage}/></Suspense>}
      {tab==='lab'&&<><span className="eyebrow">HECHO PARA PRACTICAR EN EL BUS</span><h1>Tu cuaderno, sin cuaderno.</h1><p>Construí expresiones tocando símbolos y verificá cada transformación.</p><Workbench/><Proof/></>}
      {tab==='progress'&&<><span className="eyebrow">EL AVANCE SE CONSTRUYE</span><h1>Mirá lo que ya conectaste.</h1><div className="summary-grid"><div className="card"><Flame/><b>{streak(p)}</b><span>días de racha</span></div><div className="card"><Star/><b>{p.xp}</b><span>XP acumulado</span></div><div className="card"><Check/><b>{completed}/{path.length}</b><span>lecciones completadas</span></div><div className="card"><Trophy/><b>{mastered}</b><span>lecciones dominadas</span></div></div><p>El dominio requiere aciertos sin ayuda en sesiones separadas por el intervalo de repaso. Repetir inmediatamente no cuenta como recuerdo a largo plazo.</p><div className="card">{path.map(l=><div className="mastery-row" key={l.id}><span><TopicIcon name={l.icon}/></span><div><b>{l.title}</b><div className="progress-track"><div style={{width:`${lessonMastery(p,l)}%`}}/></div></div><span>{lessonMastery(p,l)}%</span></div>)}</div><h2>Mi actividad reciente</h2><div className="card">{p.attempts.length===0?<p>Tu historia empieza con el primer ejercicio.</p>:p.attempts.slice(-12).reverse().map((a,i)=><div className="history" key={i}><span>{a.correct?'✓':'↻'}</span><div>{lessons.find(l=>l.id===a.lessonId)?.title}<small>{new Date(a.date).toLocaleString('es-CR')} · {a.assisted?'con ayuda o reintento':'sin ayuda'}</small></div></div>)}</div></>}
      {tab==='settings'&&<><span className="eyebrow">A TU MANERA</span><h1>Un espacio cómodo para aprender.</h1><section className="card settings"><label>Modo oscuro<input type="checkbox" checked={p.dark} onChange={e=>setP({...p,dark:e.target.checked})}/></label><label>Reducir movimiento<input type="checkbox" checked={p.reduceMotion} onChange={e=>setP({...p,reduceMotion:e.target.checked})}/></label><label>Tamaño de letra<input type="range" min="1" max="1.3" step=".05" value={p.fontScale} onChange={e=>setP({...p,fontScale:Number(e.target.value)})}/></label><label>Meta diaria (ejercicios)<input type="number" min="4" max="30" value={p.goal} onChange={e=>setP({...p,goal:Math.min(30,Math.max(4,Number(e.target.value)))})}/></label></section><section className="card"><h2>Tu progreso te pertenece</h2><p>El avance y los libros se guardan en este navegador. La copia JSON incluye avance y monedas; los PDF y las notas del libro se conservan aparte en este dispositivo.</p><div className="row wrap"><button className="secondary" onClick={exportData}><Download size={18}/>Exportar progreso</button><button className="secondary" onClick={()=>importRef.current?.click()}>Importar copia</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importData(f);e.target.value='';}}/><button className="danger" onClick={()=>{if(window.confirm('¿Borrar todo el progreso, XP y monedas? Los libros y sus notas se conservan.'))setP(freshProgress());}}>Reiniciar progreso</button></div>{install&&<button className="primary" onClick={async()=>{await install.prompt();setInstall(null);}}>Instalar en mi celular</button>}</section><section className="card"><h2>Materiales y cobertura</h2>{sourceNotes.map(n=><p key={n}>{n}</p>)}<p>{lessons.length} lecciones · {lessons.reduce((n,l)=>n+l.questions.length,0)} ejercicios con corrección. Práctica del libro: visor privado con saltos por semana y cuaderno de pasos. Sin servicio externo de IA.</p><h3>Videos de apoyo · Discreta</h3><a href="https://youtu.be/OXd_qDrEJIE" target="_blank" rel="noreferrer">Conectivos y tablas ↗</a><br/><a href="https://youtu.be/otoEtJYo_2E" target="_blank" rel="noreferrer">Análisis de proposiciones ↗</a><br/><a href="https://youtu.be/2owNnbzW8Rc" target="_blank" rel="noreferrer">Simplificación ↗</a></section></>}
    </main>{tab==='learn'&&<aside className="right-rail"><section className="card daily-goal"><div className="row"><Target color="#7556ef"/><b>Tu meta de hoy</b></div><div className="goal-ring" style={{background:`conic-gradient(#7556ef ${Math.min(100,today/p.goal*100)}%,var(--border) 0)`}}><div><b>{Math.min(today,p.goal)}<small>/{p.goal}</small></b><span>ejercicios</span></div></div><p>{today>=p.goal?'¡Meta alcanzada! Cada paso cuenta.':'Unos minutos hoy hacen una diferencia mañana.'}</p></section><section className="card review-card"><span className="icon-box"><RefreshCw/></span><h3>Que se quede con vos.</h3><p>{due.length?`${due.length} ejercicios esperan tu repaso.`:'Después de practicar, te proponemos cuándo volver a recordar.'}</p><button className="secondary wide" onClick={()=>{setTab('practice');}}>Ir a mis repasos<ArrowRight size={16}/></button></section><section className="small-tip"><Sparkles size={20}/><div><b>Entender también es avanzar.</b><p>Consultá una ley, pedí una pista y volvé a probar. Aquí no perdés vidas.</p></div></section><a className="repo-link" href="https://github.com/santinofuentesAI/mate_U_duo" target="_blank" rel="noreferrer">Hecho para tu forma de aprender ↗</a></aside>}</div>
    <nav className="mobile-nav" aria-label="Navegación móvil">{navigation.slice(0,6).map(n=><button className={tab===n.id?'active':''} key={n.id} onClick={()=>{setTab(n.id);window.scrollTo(0,0);}}><n.icon size={21}/><span>{n.label}</span></button>)}<button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')} aria-label="Ajustes"><Settings size={21}/><span>Ajustes</span></button></nav></div></div>;
}
