import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, Flame, GraduationCap, Home, Moon, RefreshCw, Settings, Sparkles, Star, Target, Trophy, X, Coins, Wrench, Download } from 'lucide-react';
import katex from 'katex';
import { lessons, courseInfo, sourceNotes } from './content';
import type { Lesson, Progress, Question } from './types';
import { dayKey, freshProgress, lessonMastery, loadProgress, recordAttempt, STORAGE_KEY, streak, validateProgress } from './progress';
import { Exercise } from './Exercise';
import { Workbench } from './Workbench';
const Books = lazy(()=>import('./Books').then(m=>({default:m.Books})));
import { Proof } from './Proof';
import { Library } from './Library';
import { TopicIcon } from './TopicIcon';
import { palettes, validPalette, type Palette } from './palettes';
import { bank, dailyChallenge, latestAttempts, practicePlan, sessionSummary, type PracticeItem } from './learning';
import { makeSession, loadSession, saveSession, SESSION_KEY, type Session } from './sessions';
import { LearningPath } from './LearningPath';
const PracticeHub=lazy(()=>import('./PracticeHub').then(m=>({default:m.PracticeHub})));
const Explorers=lazy(()=>import('./Explorers').then(m=>({default:m.Explorers})));
const navigation=[{id:'learn',label:'Aprender',icon:Home},{id:'practice',label:'Practicar',icon:RefreshCw},{id:'library',label:'Biblioteca',icon:GraduationCap},{id:'books',label:'Mi libro',icon:BookOpen},{id:'lab',label:'Cuaderno',icon:Wrench},{id:'progress',label:'Mi avance',icon:Trophy},{id:'settings',label:'Ajustes',icon:Settings}];
function MathLine({text}:{text:string}) { return <div className="math" dangerouslySetInnerHTML={{__html:katex.renderToString(text,{throwOnError:false,strict:false,displayMode:true})}}/>; }
function Mascot(){return <svg className="mascot" viewBox="0 0 160 170" aria-label="Milo, tu compañero de matemáticas" role="img"><ellipse cx="84" cy="156" rx="49" ry="8" fill="#30205820"/><path d="M38 51 Q23 9 51 30 L70 44 Q85 30 100 40 L124 26 Q141 19 130 65 Q149 92 136 131 Q117 155 66 149 Q30 143 29 103 Q24 70 38 51" fill="#d8f46d"/><path d="M37 53 Q35 23 51 39 L65 49 Q93 35 116 46 L129 35 L123 66 Q146 108 126 134 Q102 153 58 140 Q28 128 35 85Z" fill="#d8f46d" stroke="#b4d73f" strokeWidth="3"/><ellipse cx="70" cy="84" rx="12" ry="17" fill="white"/><ellipse cx="110" cy="84" rx="12" ry="17" fill="white"/><ellipse cx="74" cy="87" rx="5" ry="9" fill="#2c2441"/><ellipse cx="113" cy="87" rx="5" ry="9" fill="#2c2441"/><path d="M83 107 Q95 118 106 104" fill="none" stroke="#2c2441" strokeWidth="4" strokeLinecap="round"/><ellipse cx="56" cy="102" rx="9" ry="5" fill="#fa9eb3"/><ellipse cx="122" cy="102" rx="9" ry="5" fill="#fa9eb3"/><path d="M30 109 L14 99 M129 116 L145 104" stroke="#b4d73f" strokeWidth="9" strokeLinecap="round"/><path d="M72 146 L64 157 M110 145 L118 157" stroke="var(--button-accent)" strokeWidth="10" strokeLinecap="round"/><path d="M47 129 Q90 119 132 129 L132 139 Q86 130 48 140Z" fill="var(--button-accent)"/><text x="83" y="136" fill="white" fontSize="12" fontWeight="bold">π</text></svg>;}
export default function App(){
  const [p,setP]=useState<Progress>(loadProgress);const [tab,setTab]=useState('learn');const [session,setSession]=useState<Session|null>(null);const [index,setIndex]=useState(-1);const [result,setResult]=useState(false);const [storageError,setStorageError]=useState('');const [message,setMessage]=useState('');const [install,setInstall]=useState<any>(null);const importRef=useRef<HTMLInputElement>(null);
  const [bookPage,setBookPage]=useState<number|undefined>();const [pending,setPending]=useState(loadSession);const [labMode,setLabMode]=useState<'steps'|'explore'>('steps');
  const course=courseInfo[p.course],path=useMemo(()=>lessons.filter(l=>l.course===p.course),[p.course]);const units=[...new Set(path.map(l=>l.unit))];const next=path.find(l=>!p.completed.includes(l.id))||path[0];const coins=Math.max(0,20+Math.floor(p.xp/5)-(p.spentCoins||0));
  const due=useMemo(()=>path.flatMap(lesson=>lesson.questions.filter(q=>p.skills[q.id]&&Date.parse(p.skills[q.id].due)<=Date.now()).map(question=>({lesson,question}))),[p,path]);
  const errors=useMemo(()=>{const last=latestAttempts(p);return path.flatMap(lesson=>lesson.questions.filter(q=>{const a=last.get(q.id);return a&&(!a.correct||a.assisted);}).map(question=>({lesson,question})));},[p,path]);
  const today=new Set(p.attempts.filter(a=>dayKey(new Date(a.date))===dayKey()).map(a=>a.questionId)).size;const mastered=path.filter(l=>lessonMastery(p,l)===100).length;
  useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(p));setStorageError('');}catch{setStorageError('El navegador no pudo guardar el avance. Exportá una copia antes de cerrar.');}document.documentElement.dataset.theme=p.dark?'dark':'light';const colors=palettes[validPalette(p.palette)];for(const [key,value] of Object.entries({'--purple':p.dark?colors.dark:colors.main,'--button-accent':colors.main,'--accent-deep':colors.deep,'--soft':p.dark?colors.night:colors.soft}))document.documentElement.style.setProperty(key,value);document.documentElement.style.setProperty('--font-scale',String(p.fontScale));document.documentElement.dataset.motion=p.reduceMotion?'reduce':'normal';},[p]);
  useEffect(()=>{const handler=(e:Event)=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler);},[]);
  useEffect(()=>{if(!session||result)return;try{saveSession(session,index);setPending({session,index});}catch{setStorageError('No se pudo guardar la sesión. Conservá esta pestaña abierta.');}},[session,index,result]);
  function clearPending(){setPending(null);try{localStorage.removeItem(SESSION_KEY);for(const item of pending?.session.items||[])localStorage.removeItem(`mate-session-${pending!.session.id}-${item.question.id}`);}catch{}}
  function startItems(items:PracticeItem[],title:string,mode:string){if(!items.length){setMessage('No hay ejercicios pendientes con ese filtro.');return;}clearPending();setSession(makeSession(title,items,mode,p.xp));setIndex(0);setResult(false);window.scrollTo(0,0);}
  function startLesson(l:Lesson){clearPending();setSession(makeSession(l.title,l.questions.map(question=>({lesson:l,question})),'lesson',p.xp,l));setIndex(-1);setResult(false);window.scrollTo(0,0);}
  function startPractice(mode:string){const all=bank(lessons,p.course);startItems(mode==='review'?due:mode==='errors'?errors:mode==='daily'?dailyChallenge(all,p.course):practicePlan(all,p,mode==='quick'?3:mode==='exam'?18:8),({quick:'Una pausa para aprender',daily:'Reto del día',review:'Repaso espaciado',errors:'Aprender de mis errores',exam:'Simulacro de práctica'} as Record<string,string>)[mode]||'Práctica personalizada',mode);}
  function finish(){if(session?.lesson)setP(prev=>({...prev,completed:[...new Set([...prev.completed,session.lesson!.id])]}));setResult(true);setPending(null);try{localStorage.removeItem(SESSION_KEY);for(const item of session?.items||[])localStorage.removeItem(`mate-session-${session!.id}-${item.question.id}`);}catch{}}
  function favorite(id:string){setP(prev=>({...prev,favorites:prev.favorites?.includes(id)?prev.favorites.filter(x=>x!==id):[...(prev.favorites||[]),id]}));}
  function resume(){if(!pending)return;setP(prev=>({...prev,course:pending.session.items[0].lesson.course}));setSession(pending.session);setIndex(pending.index);setResult(false);window.scrollTo(0,0);}
  function advance(){if(session&&index+1<session.items.length)setIndex(index+1);else finish();window.scrollTo(0,0);}
  function exportData(){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mate-u-duo-${dayKey()}.json`;a.click();URL.revokeObjectURL(url);}
  async function importData(file:File){try{if(file.size>20*1024*1024)throw new Error('La copia supera 20 MB.');const v=validateProgress(JSON.parse(await file.text()));if(!window.confirm('¿Reemplazar tu progreso con esta copia?'))return;clearPending();setP(v);setMessage('Copia importada.');}catch(e){setMessage(e instanceof Error?e.message:'No se pudo importar.');}}
  const completed=path.filter(l=>p.completed.includes(l.id)).length;
  if(session){const item=session.items[index],summary=sessionSummary(p,session.items,session.started);return <div className="session-shell"><header className="session-header"><button onClick={()=>{if(window.confirm('¿Pausar la sesión? Vas a poder retomar este ejercicio y tu respuesta.'))setSession(null);}} aria-label="Salir de la lección"><X/></button><div className="progress-track"><div style={{width:`${result?100:Math.max(0,index)/session.items.length*100}%`}}/></div><span><Coins size={18}/>{coins}</span><span className="infinite">∞</span></header><main className="session-content">
    {result?<section className="result card"><div className="celebration"><TopicIcon name="🎉" size={65}/></div><span className="eyebrow">SESIÓN COMPLETADA</span><h1>Un paso más cerca.</h1><p>Completaste {session.items.length} ejercicios de {session.title.toLowerCase()}.</p><div className="result-stats"><div><b>+{p.xp-session.startingXP}</b><small>XP en esta sesión</small></div><div><b>{summary.clean}/{session.items.length}</b><small>al primer intento</small></div><div><b>{summary.retries}</b><small>reintentos útiles</small></div></div><p className="notice">{summary.helped?`${summary.helped} ejercicios con ayuda o reintento vuelven al repaso. Entenderlos es el siguiente paso.`:'Seguí practicando otro día para confirmar que podés recordarlo sin pistas.'}</p><p>Completar una lección es el primer paso. El dominio se confirma al resolver de nuevo, otro día y sin ayudas.</p><button className="primary" onClick={()=>{setSession(null);setTab('learn');}}>Volver a mi ruta<ArrowRight size={18}/></button></section>:
      index<0&&session.lesson?<section className="lesson-theory"><span className="eyebrow">{session.lesson.unit} · {session.lesson.minutes} MIN</span><div className="theory-icon"><TopicIcon name={session.lesson.icon} size={48}/></div><h1>{session.lesson.title}</h1>{session.lesson.theory.map(t=><p key={t}>{t}</p>)}<div className="formula-box">{session.lesson.formulas.map(f=><MathLine key={f} text={f}/>)}</div><section className="example"><h3>{session.lesson.example.title}</h3>{session.lesson.example.steps.map((s,i)=><div key={s}><span>{i+1}</span><p>{s}</p></div>)}</section><small>{session.lesson.source} · páginas {session.lesson.pages} · contenido adaptado</small><button className="primary wide" onClick={()=>setIndex(0)}>Ahora me toca practicar<ArrowRight size={18}/></button></section>:
      item&&<><div className="exercise-meta"><span>{session.title}</span><span>{index+1} / {session.items.length}</span></div><Exercise key={`${session.id}-${item.question.id}-${index}`} draftKey={`mate-session-${session.id}-${item.question.id}`} question={item.question} coins={coins} onSpend={n=>setP(prev=>({...prev,spentCoins:(prev.spentCoins||0)+n}))} onAttempt={(correct,assisted,details)=>setP(prev=>recordAttempt(prev,item.lesson,item.question,correct,assisted,new Date(),details))} onNext={advance}/></>}
    {storageError&&<p role="alert">{storageError}</p>}</main></div>;}
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('learn');}}><span>m<span className="brand-dot">•</span></span><div>mate<span>U DUO</span></div></a><nav aria-label="Navegación principal">{navigation.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>{setTab(n.id);setMessage('');window.scrollTo(0,0);}}><n.icon size={21}/><span>{n.label}</span>{n.id==='practice'&&due.length>0&&<b>{due.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">S</div><div>Tu espacio de estudio<small>Progreso en este dispositivo</small></div></div></aside>
    <div className="main-shell"><header className="topbar"><span className="mobile-brand">mate <b>U DUO</b></span><label className="course-picker"><span>Tu curso</span><select aria-label="Elegir curso" value={p.course} onChange={e=>{setBookPage(undefined);setP({...p,course:e.target.value as Progress['course']});}}><option value="discreta">Matemática Discreta</option><option value="precalculo">Precálculo</option></select></label><div className="top-stats"><span title="Racha"><Flame size={20} color="#e77d32"/>{streak(p)}</span><span title="Experiencia"><Star size={20} color="#bd8b0c"/>{p.xp}</span><span title="Monedas ficticias"><Coins size={20} color="#168979"/>{coins}</span></div><button className="icon-button" aria-label="Cambiar tema claro u oscuro" onClick={()=>setP({...p,dark:!p.dark})}><Moon size={19}/></button></header>
    <div className={`content-grid ${tab!=='learn'?'single':''}`}><main className="main-content">{message&&<p role="status" className="notice">{message}</p>}{storageError&&<p role="alert" className="notice">{storageError}</p>}
      {tab==='learn'&&<><div className="page-heading"><div><span className="eyebrow">UN POQUITO CADA DÍA</span><h1>Tu próxima gran idea<br/>empieza por un paso.</h1><p>{course.subtitle}</p></div><span className="course-badge"><TopicIcon name={course.emoji} size={32}/></span></div><section className="mission"><div><span className="pill">TU MISIÓN DE HOY</span><h2>{completed===path.length?'Volvamos a conectar ideas':`Seguimos con ${next.title.toLowerCase()}`}</h2><p>Seis minutos. Un concepto. Más confianza.</p><button className="primary" onClick={()=>startLesson(next)}>Continuar mi ruta<ArrowRight size={18}/></button></div><Mascot/></section>{pending&&<section className="card resume-card"><div><span className="eyebrow">TE GUARDAMOS EL LUGAR</span><h3>{pending.session.title}</h3><p>Ejercicio {Math.max(1,pending.index+1)} de {pending.session.items.length} · tu respuesta sigue acá.</p></div><button className="primary" onClick={resume}>Retomar sesión<ArrowRight size={18}/></button></section>}<div className="quick-actions"><button onClick={()=>startPractice('quick')}><RefreshCw size={20}/><span><b>Tengo un ratito</b><small>3 ejercicios para el bus</small></span><ArrowRight size={16}/></button><button onClick={()=>{setLabMode('explore');setTab('lab');}}><Sparkles size={20}/><span><b>Quiero entenderlo</b><small>Tocar, ver y conectar</small></span><ArrowRight size={16}/></button></div><LearningPath key={p.course} path={path} progress={p} onStart={startLesson} onFavorite={favorite}/><section className="card book-banner"><BookOpen size={28}/><div><h3>¿Tenés un ejercicio del libro?</h3><p>Abrilo y resolvelo con el cuaderno táctil.</p></div><button className="secondary" onClick={()=>setTab('books')}>Ir a mi libro<ChevronRight size={18}/></button></section></>}
      {tab==='practice'&&<Suspense fallback={<p role="status">Preparando tu práctica…</p>}><PracticeHub key={p.course} progress={p} onStart={startItems} onLesson={startLesson} onExplore={()=>{setLabMode('explore');setTab('lab');window.scrollTo(0,0);}}/></Suspense>}
      {tab==='library'&&<Library key={p.course} course={p.course} onPractice={startLesson} onRead={page=>{setBookPage(page);setTab('books');window.scrollTo(0,0);}}/>}
      {tab==='books'&&<Suspense fallback={<p role="status">Preparando tu libro…</p>}><Books key={p.course} course={p.course} initialPage={bookPage}/></Suspense>}
      {tab==='lab'&&<><span className="eyebrow">LAS MATEMÁTICAS SE PUEDEN TOCAR</span><h1>Probá una idea. Mirá qué pasa.</h1><div className="hub-tabs" role="group" aria-label="Modo de cuaderno"><button aria-pressed={labMode==='steps'} className={labMode==='steps'?'active':''} onClick={()=>setLabMode('steps')}><Wrench size={18}/>Mis pasos</button><button aria-pressed={labMode==='explore'} className={labMode==='explore'?'active':''} onClick={()=>setLabMode('explore')}><Sparkles size={18}/>Explorar</button></div>{labMode==='explore'?<Suspense fallback={<p role="status">Preparando el explorador…</p>}><Explorers key={p.course} course={p.course}/></Suspense>:<><Workbench key={p.course} draftPrefix={p.course==='discreta'?'mate-draft':'mate-lab-precalculo'} initialMode={p.course==='precalculo'?'algebra':'logic'}/>{p.course==='discreta'&&<Proof/>}</>}</>}
      {tab==='progress'&&<><span className="eyebrow">EL AVANCE SE CONSTRUYE</span><h1>Mirá lo que ya conectaste.</h1><div className="summary-grid"><div className="card"><Flame/><b>{streak(p)}</b><span>días de racha</span></div><div className="card"><Star/><b>{p.xp}</b><span>XP acumulado</span></div><div className="card"><Check/><b>{completed}/{path.length}</b><span>lecciones completadas</span></div><div className="card"><Trophy/><b>{mastered}</b><span>lecciones dominadas</span></div></div><p>El dominio requiere aciertos sin ayuda en sesiones separadas por el intervalo de repaso. Repetir inmediatamente no cuenta como recuerdo a largo plazo.</p><div className="card">{path.map(l=><div className="mastery-row" key={l.id}><span><TopicIcon name={l.icon}/></span><div><b>{l.title}</b><div className="progress-track"><div style={{width:`${lessonMastery(p,l)}%`}}/></div></div><span>{lessonMastery(p,l)}%</span></div>)}</div><h2>Mi actividad reciente</h2><div className="card">{p.attempts.length===0?<p>Tu historia empieza con el primer ejercicio.</p>:p.attempts.slice(-12).reverse().map((a,i)=><div className="history" key={i}><span>{a.correct?'✓':'↻'}</span><div>{lessons.find(l=>l.id===a.lessonId)?.title}<small>{new Date(a.date).toLocaleString('es-CR')} · {a.assisted?'con ayuda o reintento':'sin ayuda'}</small></div></div>)}</div></>}
      {tab==='settings'&&<><span className="eyebrow">A TU MANERA</span><h1>Un espacio cómodo para aprender.</h1><section className="card settings"><label>Color principal<select aria-label="Color principal" value={validPalette(p.palette)} onChange={e=>setP({...p,palette:e.target.value as Palette})}>{Object.entries(palettes).map(([id,color])=><option key={id} value={id}>{color.label}</option>)}</select></label><label>Modo oscuro<input type="checkbox" checked={p.dark} onChange={e=>setP({...p,dark:e.target.checked})}/></label><label>Reducir movimiento<input type="checkbox" checked={p.reduceMotion} onChange={e=>setP({...p,reduceMotion:e.target.checked})}/></label><label>Tamaño de letra<input type="range" min="1" max="1.3" step=".05" value={p.fontScale} onChange={e=>setP({...p,fontScale:Number(e.target.value)})}/></label><label>Meta diaria (ejercicios)<input type="number" min="4" max="30" value={p.goal} onChange={e=>setP({...p,goal:Math.min(30,Math.max(4,Number(e.target.value)))})}/></label></section><section className="card"><h2>Tu progreso te pertenece</h2><p>El avance y los libros se guardan en este navegador. La copia JSON incluye avance y monedas; los PDF y las notas del libro se conservan aparte en este dispositivo.</p><div className="row wrap"><button className="secondary" onClick={exportData}><Download size={18}/>Exportar progreso</button><button className="secondary" onClick={()=>importRef.current?.click()}>Importar copia</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importData(f);e.target.value='';}}/><button className="danger" onClick={()=>{if(window.confirm('¿Borrar todo el progreso, XP, monedas y la sesión pausada? Los libros y sus notas se conservan.')){clearPending();setP(freshProgress());}}}>Reiniciar progreso</button></div>{install&&<button className="primary" onClick={async()=>{await install.prompt();setInstall(null);}}>Instalar en mi celular</button>}</section><section className="card"><h2>Materiales y cobertura</h2>{sourceNotes.map(n=><p key={n}>{n}</p>)}<p>{lessons.length} lecciones · {lessons.reduce((n,l)=>n+l.questions.length,0)} ejercicios con corrección. Práctica del libro: visor privado con saltos por semana y cuaderno de pasos. Sin servicio externo de IA.</p><h3>Videos de apoyo · Discreta</h3><a href="https://youtu.be/OXd_qDrEJIE" target="_blank" rel="noreferrer">Conectivos y tablas ↗</a><br/><a href="https://youtu.be/otoEtJYo_2E" target="_blank" rel="noreferrer">Análisis de proposiciones ↗</a><br/><a href="https://youtu.be/2owNnbzW8Rc" target="_blank" rel="noreferrer">Simplificación ↗</a></section></>}
    </main>{tab==='learn'&&<aside className="right-rail"><section className="card daily-goal"><div className="row"><Target color="var(--button-accent)"/><b>Tu meta de hoy</b></div><div className="goal-ring" style={{background:`conic-gradient(var(--button-accent) ${Math.min(100,today/p.goal*100)}%,var(--border) 0)`}}><div><b>{Math.min(today,p.goal)}<small>/{p.goal}</small></b><span>ejercicios</span></div></div><p>{today>=p.goal?'¡Meta alcanzada! Cada paso cuenta.':'Unos minutos hoy hacen una diferencia mañana.'}</p></section><section className="card review-card"><span className="icon-box"><RefreshCw/></span><h3>Que se quede con vos.</h3><p>{due.length?`${due.length} ejercicios esperan tu repaso.`:'Después de practicar, te proponemos cuándo volver a recordar.'}</p><button className="secondary wide" onClick={()=>{setTab('practice');}}>Ir a mis repasos<ArrowRight size={16}/></button></section><section className="small-tip"><Sparkles size={20}/><div><b>Entender también es avanzar.</b><p>Consultá una ley, pedí una pista y volvé a probar. Aquí no perdés vidas.</p></div></section><a className="repo-link" href="https://github.com/santinofuentesAI/mate_U_duo" target="_blank" rel="noreferrer">Hecho para tu forma de aprender ↗</a></aside>}</div>
    <nav className="mobile-nav" aria-label="Navegación móvil">{navigation.slice(0,6).map(n=><button className={tab===n.id?'active':''} key={n.id} onClick={()=>{setTab(n.id);window.scrollTo(0,0);}}><n.icon size={21}/><span>{n.label}</span></button>)}<button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')} aria-label="Ajustes"><Settings size={21}/><span>Ajustes</span></button></nav></div></div>;
}
