import type { Course } from './types';
export const bookRoutes:Record<Course,{week:string;title:string;page:number;end:number;printed:string}[]>={
  discreta:[
    {week:'Apoyo',title:'Introducción · ejercicios 1.1',page:37,end:45,printed:'35–43'},
    {week:'S1',title:'Conectivas · ejercicios 1.2',page:55,end:58,printed:'53–56'},
    {week:'S1',title:'Leyes de lógica · ejercicios 1.3',page:63,end:63,printed:'61'},
    {week:'S2',title:'Inferencias · ejercicios 1.4',page:73,end:78,printed:'71–76'},
    {week:'Apoyo',title:'Formas normales · ejercicios 1.5',page:82,end:82,printed:'80'},
    {week:'S3',title:'Cuantificadores · ejercicios 1.6',page:93,end:97,printed:'91–95'},
    {week:'Apoyo',title:'Inferencias cuantificadas · ejercicios 1.7',page:100,end:100,printed:'98'},
    {week:'Apoyo',title:'Demostraciones · ejercicios 1.8',page:110,end:110,printed:'108'},
    {week:'S4',title:'Conjuntos · ejercicios 2.1',page:123,end:128,printed:'121–126'},
    {week:'Apoyo',title:'Conjuntos numéricos · ejercicios 2.2',page:133,end:134,printed:'131–132'},
    {week:'S4',title:'Venn · ejercicios 2.3',page:137,end:138,printed:'135–136'},
    {week:'S4',title:'Leyes de conjuntos · ejercicios 2.4',page:142,end:142,printed:'140'},
    {week:'Por confirmar',title:'Cardinalidad · ejercicios 2.5',page:148,end:152,printed:'146–150'},
  ],
  precalculo:[
    {week:'B1',title:'Números reales · práctica 1.4',page:18,end:19,printed:'18–19'},
    {week:'B2',title:'Expresiones y polinomios · práctica 2.5',page:33,end:33,printed:'33'},
    {week:'B3',title:'Factorización · práctica 3.2.5',page:42,end:43,printed:'42–43'},
    {week:'S4',title:'División sintética · ejemplos',page:43,end:45,printed:'43–45'},
    {week:'S4',title:'Fracciones algebraicas · ejemplos',page:45,end:49,printed:'45–49'},
    {week:'S4',title:'Racionalización · ejemplos',page:49,end:51,printed:'49–51'},
    {week:'S4',title:'Factorización y fracciones · práctica final 3.3.5',page:52,end:53,printed:'52–53'},
    {week:'B5',title:'Ecuaciones · práctica 4.6 y método de aplicaciones',page:63,end:63,printed:'63'},
  ],
};
export const readerPages:Record<Course,{title:string;page:number;end:number}[]>={
  discreta:[
    {title:'Portada, índice e introducción',page:1,end:36},
    {title:'Conectivas: definiciones y ejemplos',page:46,end:54},
    {title:'Leyes de lógica: identidades y ejemplos',page:59,end:62},
    {title:'Inferencias: reglas y demostraciones',page:64,end:72},
    {title:'Formas normales',page:79,end:81},
    {title:'Cuantificadores: significado y negaciones',page:83,end:92},
    {title:'Inferencias cuantificadas',page:98,end:99},
    {title:'Métodos de demostración',page:101,end:109},
    {title:'Conjuntos: operaciones y ejemplos',page:111,end:122},
    {title:'Conjuntos numéricos',page:129,end:132},
    {title:'Diagramas de Venn',page:135,end:136},
    {title:'Leyes de conjuntos',page:139,end:141},
    {title:'Cardinalidad y aplicaciones',page:143,end:148},
  ],
  precalculo:[
    {title:'Portada, índice y comienzo del libro',page:1,end:6},
    {title:'Números reales, operaciones, potencias y raíces',page:7,end:17},
    {title:'Variables, valor numérico y monomios',page:20,end:27},
    {title:'Polinomios y productos notables',page:28,end:31},
    {title:'División de polinomios',page:32,end:32},
    {title:'Factorización: métodos y ejemplos',page:34,end:42},
    {title:'División sintética: procedimiento resuelto',page:43,end:45},
    {title:'Simplificación de fracciones',page:45,end:46},
    {title:'Suma y resta de fracciones',page:46,end:48},
    {title:'Multiplicación y división',page:48,end:49},
    {title:'Racionalización con ejemplos',page:49,end:51},
    {title:'Ecuaciones lineales',page:54,end:56},
    {title:'Ecuaciones cuadráticas',page:57,end:58},
    {title:'Ecuaciones de grado superior',page:59,end:59},
    {title:'Ecuaciones racionales',page:60,end:61},
    {title:'Ecuaciones con radicales',page:62,end:62},
    {title:'Práctica y método de aplicaciones',page:63,end:63},
  ],
};
