import { useState } from 'react';
import { ArrowRight, BookOpenCheck, ChevronRight, FileText, PencilLine } from 'lucide-react';
import type { Course, Progress } from './types';
import type { PracticeItem } from './learning';
import { BookProblem } from './BookProblem';
import { assignmentLabel, bookCatalog, readBookPosition, responseStatus, reviewedActivities, statusLabels } from './bookCatalog';
interface Props {course:Course;items:PracticeItem[];progress:Progress;onStart:(items:PracticeItem[],title:string,mode:string)=>void;onRead:(page:number)=>void;initialProblem?:string;}
export function BookExam({course,items,progress,onStart,onRead,initialProblem}:Props) {
  const all=bookCatalog[course];
  const initial=all.find(p=>p.id===(initialProblem||readBookPosition(course)?.id));
  const [week,setWeek]=useState(initial?.week||(course==='discreta'?'S1':'S4')),[section,setSection]=useState(initial?.sectionCode||'all'),[topic,setTopic]=useState('all');
  const [selected,setSelected]=useState<string|null>(initial?.id||null),[message,setMessage]=useState('');
  const [lastPosition,setLastPosition]=useState(initial?.id||null);
  const [done,setDone]=useState<string[]>(()=>{try{const v=JSON.parse(localStorage.getItem(`mate-book-exam-done-${course}`)||'[]');return Array.isArray(v)?v.filter(id=>typeof id==='string'):[];}catch{return [];}});
  const weeks=[...new Set(all.map(p=>p.week))],topics=[...new Set(all.map(p=>p.section))];
  const sections=[...new Map(all.filter(p=>(week==='all'||p.week===week)&&(topic==='all'||p.section===topic)).map(p=>[p.sectionCode,p.section])).entries()];
  const catalog=all.filter(p=>(week==='all'||p.week===week)&&(topic==='all'||p.section===topic)&&(section==='all'||p.sectionCode===section));
  const current=all.find(p=>p.id===selected),status=(p:typeof all[number])=>responseStatus(p,items,progress,done.includes(p.id));
  function choose(id:string){setSelected(id);setLastPosition(id);setMessage('');try{localStorage.setItem(`mate-book-position-${course}`,JSON.stringify({id}));}catch{setMessage('No se pudo guardar tu posición. Conservá esta pestaña abierta.');}requestAnimationFrame(()=>document.getElementById('book-exam-current')?.scrollIntoView({behavior:'smooth',block:'start'}));}
  function resume(){const last=all.find(p=>p.id===lastPosition);if(!last)return;setWeek(last.week);setTopic('all');setSection(last.sectionCode);choose(last.id);}
  function markDone(){if(!selected)return false;const updated=[...new Set([...done,selected])];try{localStorage.setItem(`mate-book-exam-done-${course}`,JSON.stringify(updated));setDone(updated);return true;}catch{setMessage('No se pudo guardar el estado. Tu respuesta sigue en pantalla.');return false;}}
  function edited(){if(!selected||!done.includes(selected))return;const updated=done.filter(id=>id!==selected);setDone(updated);try{localStorage.setItem(`mate-book-exam-done-${course}`,JSON.stringify(updated));}catch{setMessage('No se pudo guardar el nuevo estado de la respuesta.');}}
  function nextProblem(delta=1){const index=catalog.findIndex(p=>p.id===selected),next=catalog[index+delta];if(next)choose(next.id);else setMessage(delta===1?'Llegaste al final de esta selección. Podés cambiar los filtros.':'Este es el primer ejercicio de la selección.');}
  function filter(){setSelected(null);setMessage('');}
  return <section className="book-exam card" aria-label="Modo Book Exam">
    <header className="book-exam-title" id="book-exam-heading"><span className="book-exam-emblem"><BookOpenCheck size={28}/></span><div><h2>Book Exam</h2><p>Un inciso a la vez. Escribí tus pasos y seguí después.</p></div></header>
    <div className="book-filters"><label>Semana<select aria-label="Semana de Book Exam" value={week} onChange={e=>{setWeek(e.target.value);setTopic('all');setSection('all');filter();}}><option value="all">Todo el alcance</option>{weeks.map(w=><option key={w} value={w}>{assignmentLabel(w)}</option>)}</select></label><label>Problema<select aria-label="Problema de Book Exam" value={catalog.some(p=>p.id===selected)?selected||'':''} onChange={e=>e.target.value?choose(e.target.value):filter()}><option value="">Elegí un problema o inciso</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.sectionCode} · {p.number}{p.part} · PDF {p.page}</option>)}</select></label></div>
    <details className="simple-more"><summary>Filtrar por tema y sección</summary><div className="book-filters"><label>Tema<select aria-label="Tema de Book Exam" value={topic} onChange={e=>{setTopic(e.target.value);setSection('all');filter();}}><option value="all">Todos los temas</option>{topics.map(t=><option key={t}>{t}</option>)}</select></label><label>Sección<select aria-label="Sección de Book Exam" value={section} onChange={e=>{setSection(e.target.value);filter();}}><option value="all">Todas las secciones</option>{sections.map(([code,name])=><option key={code} value={code}>{code} · {name}</option>)}</select></label></div></details>
    <div className="book-exam-actions"><button className="primary" disabled={!catalog.length} onClick={()=>{const next=catalog.find(p=>status(p)==='identified')||catalog.find(p=>status(p)==='submitted');if(next)choose(next.id);else setMessage('Ya trabajaste toda esta selección. Podés repasar un ejercicio o cambiar los filtros.');}}>Empezar por el primero pendiente<ArrowRight size={18}/></button>{lastPosition&&lastPosition!==selected&&<button className="secondary" onClick={resume}>Continuar donde quedé<ChevronRight size={18}/></button>}</div>
    {current&&<div id="book-exam-current"><BookProblem key={current.id} problem={current} verified={reviewedActivities(current,items)} responseState={status(current)} onVerified={item=>onStart([item],`Book Exam · ${current.sectionCode} · ${current.number}${current.part}`,'book-exam')} onDone={markDone} onEdited={edited} onNext={()=>nextProblem()} onPrevious={()=>nextProblem(-1)}/></div>}
    {message&&<p role="status" className="notice">{message}</p>}
    <details className="book-exam-list"><summary><PencilLine size={19}/> Inventario de esta selección <ChevronRight size={18}/></summary><div>{catalog.map(p=><button key={p.id} onClick={()=>choose(p.id)}><span className={`book-state-symbol ${status(p)}`}>{status(p)==='validated'?'✓':status(p)==='submitted'?'✎':'·'}</span><span><b>{p.sectionCode} · Ejercicio {p.number}{p.part} · {p.section}</b><small>PDF {p.page} · impresa {p.printedPage} · {statusLabels[status(p)]}</small></span><ChevronRight size={17}/></button>)}</div></details>
    <details className="book-exam-list"><summary><FileText size={19}/> Páginas y alcance semanal <ChevronRight size={18}/></summary><p>Las semanas con material confirmado son S1–S4 en Discreta y S4 en Precálculo. Los bloques B y los complementos no afirman una asignación del docente.</p><div>{[...new Map(catalog.map(p=>[p.sectionCode,p])).values()].map(p=><div className="book-exam-section" key={p.sectionCode}><b>{p.sectionCode} · {p.section}</b><small>{assignmentLabel(p.week)}</small><div>{[...new Set(all.filter(a=>a.sectionCode===p.sectionCode).flatMap(a=>a.sourcePages))].sort((a,b)=>a-b).map(page=><button key={page} onClick={()=>onRead(page)}>PDF {page}<ChevronRight size={16}/></button>)}</div></div>)}</div></details>
    <p className="book-exam-note">Identificar un ejercicio no valida su transcripción ni tu respuesta. Los textos auxiliares conservan su aviso; los originales se dibujan desde tu copia privada, importada una vez.</p>
  </section>;
}
