import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Check, Lightbulb, Coins } from 'lucide-react';
import type { Question, AnswerDetails, Course } from './types';
import { loadAnswerDraft } from './exerciseDraft';
import { grade, shuffle, truthRows } from './engine';
import { SymbolInput } from './Keyboard';
import { Laws } from './Workbench';
import { AnswerFeedback } from './AnswerFeedback';
import { GuidedProofExercise } from './GuidedProofExercise';
import { AnswerReveal } from './AnswerReveal';
import { ExamReasoningExercise } from './ExamReasoningExercise';
import katex from 'katex';
export function Exercise({question:q,course,coins,onSpend,onAttempt,onNext,draftKey,rewardAvailable=false}:{question:Question;course:Course;coins:number;onSpend:(n:number)=>void;onAttempt:(correct:boolean,assisted:boolean,details:AnswerDetails)=>void;onNext:()=>void;draftKey?:string;rewardAvailable?:boolean}) {
  if(q.type==='guidedproof')return <GuidedProofExercise question={q} course={course} coins={coins} onSpend={onSpend} onAttempt={onAttempt} onNext={onNext} rewardAvailable={rewardAvailable}/>;
  if(q.type==='examproof')return <ExamReasoningExercise question={q} onAttempt={onAttempt} onNext={onNext} draftKey={draftKey} rewardAvailable={rewardAvailable}/>;
  const [restored]=useState(()=>loadAnswerDraft(q,draftKey));
  const [value,setValue]=useState<string|string[]>(restored.value);
  const [exclusions,setExclusions]=useState(restored.exclusions);const [hint,setHint]=useState(restored.hint);const [feedback,setFeedback]=useState<{correct:boolean;error?:string}|null>(restored.feedback);const [rules,setRules]=useState(false);const [retried,setRetried]=useState(restored.retried);const [revealed,setRevealed]=useState(restored.revealed);const [showAnswer,setShowAnswer]=useState(restored.revealed);const [draftError,setDraftError]=useState('');
  const [earned,setEarned]=useState(0),[celebrate,setCelebrate]=useState(false);
  useEffect(()=>{if(!draftKey)return;try{localStorage.setItem(draftKey,JSON.stringify({value,exclusions,hint,feedback,retried,revealed}));setDraftError('');}catch{setDraftError('No se pudo guardar el borrador de esta respuesta.');}},[draftKey,value,exclusions,hint,feedback,retried,revealed]);
  const options=useMemo(()=>shuffle(q.options||[]),[q]); const selected=Array.isArray(value)?value:[];
  function toggle(s:string){setValue(selected.includes(s)?selected.filter(x=>x!==s):[...selected,s]);setFeedback(null);}
  function update(s:string){setValue(s);setFeedback(null);}
  const canCheck=Array.isArray(value)?(['table','synthetic'].includes(q.type)?value.every(s=>s.trim()!==''):q.type==='order'?value.length===q.options?.length:true):value.trim().length>0;
  function check(){const domains=exclusions.split(/[,;]/).map(s=>s.trim()).filter(Boolean);const result=grade(q,value,domains),assisted=hint>0||retried||revealed;setFeedback(result);setEarned(result.correct&&rewardAvailable?(assisted?5:10):0);setCelebrate(result.correct);onAttempt(result.correct,assisted,{answer:Array.isArray(value)?[...value]:value,exclusions:domains,error:result.error});if(!result.correct)setRetried(true);}
  const rows=q.type==='table'?truthRows(q.expression!,q.variables):[];
  const vennRegions=[{code:'100',x:86,y:89},{code:'010',x:222,y:89},{code:'001',x:155,y:207},{code:'110',x:155,y:77},{code:'101',x:111,y:156},{code:'011',x:200,y:156},{code:'111',x:155,y:129},{code:'000',x:280,y:235}];
  return <section className="exercise"><div className="row"><span className="eyebrow">{({choice:'ELEGÍ',logic:'CONSTRUÍ',table:'COMPLETÁ',set:'SELECCIONÁ',order:'ORDENÁ',venn:'EXPLORÁ',algebra:'RESOLVÉ',synthetic:'CALCULÁ',text:'RESPONDÉ'} as Record<string,string>)[q.type]}</span><button className="text-button" onClick={()=>setRules(true)}><BookOpen size={16}/>Ver leyes</button></div><h2>{q.prompt}</h2>
    {q.math&&<div className="math exercise-formula" dangerouslySetInnerHTML={{__html:katex.renderToString(q.math,{throwOnError:false,strict:false,displayMode:true})}}/>}
    {q.type==='choice'&&<div className="choices">{options.map((o,i)=><button key={o} className={value===o?'selected':''} disabled={!!feedback?.correct} onClick={()=>update(o)}><span>{i+1}</span>{o}{value===o&&<Check size={18}/>}</button>)}</div>}
    {['logic','algebra','text'].includes(q.type)&&<SymbolInput value={String(value)} onChange={update} mode={q.type==='logic'?'logic':'algebra'} disabled={!!feedback?.correct}/>}
    {q.type==='algebra'&&q.exclusions&&<label>Restricciones del dominio<input value={exclusions} onChange={e=>{setExclusions(e.target.value);setFeedback(null);}} placeholder="Ej.: 0, 3 · o x=0, y=0 si se indica" disabled={!!feedback?.correct}/><small>Valores excluidos, separados por coma. Conservá los del problema original.</small></label>}
    {q.type==='set'&&<div className="set-options">{q.universe?.map(s=><button aria-pressed={selected.includes(s)} className={selected.includes(s)?'selected':''} key={s} onClick={()=>toggle(s)} disabled={!!feedback?.correct}>{s}</button>)}<p>Tu conjunto: {selected.length?<>{'{'}{selected.join(', ')}{'}'}</>:'∅'}</p></div>}
    {q.type==='venn'&&<><svg viewBox="0 0 310 260" className="venn" role="group" aria-label="Regiones del diagrama de Venn"><rect x="2" y="2" width="306" height="256" rx="14" fill="var(--bg)" stroke="var(--border)"/><circle cx="112" cy="103" r="77" fill="#7556ef15" stroke="#7556ef"/><circle cx="198" cy="103" r="77" fill="#16897915" stroke="#168979"/><circle cx="155" cy="174" r="77" fill="#e5a51915" stroke="#bd8412"/><text x="33" y="24">A</text><text x="273" y="24">B</text><text x="155" y="253">C</text>{vennRegions.map(r=><g role="button" tabIndex={0} aria-label={`Región ${r.code}`} aria-pressed={selected.includes(r.code)} key={r.code} onClick={()=>!feedback?.correct&&toggle(r.code)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();if(!feedback?.correct)toggle(r.code);}}}><rect x={r.x-23} y={r.y-18} width="46" height="36" rx="9" fill={selected.includes(r.code)?'#7556ef':'var(--surface)'} stroke="var(--border)"/><text x={r.x} y={r.y+5} textAnchor="middle" fill={selected.includes(r.code)?'#fff':'var(--text)'}>{r.code}</text></g>)}</svg><p className="notice">Tocá las etiquetas para seleccionar regiones. El código ABC indica si estás dentro (1) o fuera (0) de cada conjunto.</p></>}
    {q.type==='table'&&<div className="table-scroll"><table><thead><tr>{q.variables?.map(v=><th key={v}>{v}</th>)}<th>{q.expression}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{Object.values(r.values).map((v,j)=><td key={j}>{v?'V':'F'}</td>)}<td><div className="truth-buttons">{['V','F'].map(v=><button key={v} disabled={!!feedback?.correct} aria-label={`Fila ${i+1}: ${v}`} className={selected[i]===v?'selected':''} onClick={()=>{const copy=[...selected];copy[i]=v;setValue(copy);setFeedback(null);}}>{v}</button>)}</div></td></tr>)}</tbody></table></div>}
    {q.type==='synthetic'&&<div className="synthetic"><p>Raíz r = {q.root} · coeficientes: {q.coefficients?.join(' · ')}</p><div>{q.coefficients?.map((c,i)=><label key={i}><b>{c}</b><input aria-label={`Fila final, posición ${i+1}`} type="text" inputMode="numeric" value={selected[i]} disabled={!!feedback?.correct} onChange={e=>{const copy=[...selected];copy[i]=e.target.value;setValue(copy);setFeedback(null);}}/></label>)}</div><small>La última casilla es el resto.</small></div>}
    {q.type==='order'&&<><div className="order-slots">{selected.length?selected.map((s,i)=><button key={s} disabled={!!feedback?.correct} onClick={()=>toggle(s)}><b>{i+1}</b>{s} <small>✕</small></button>):<p>Tocá cada paso en el orden correcto.</p>}</div><div className="set-options">{options.filter(s=>!selected.includes(s)).map(s=><button key={s} onClick={()=>toggle(s)}>{s}</button>)}</div></>}
    {!feedback?.correct&&<div className="help-row"><button className="secondary" disabled={hint>=1} onClick={()=>setHint(1)}><Lightbulb size={17}/>Consejo gratis</button><button className="secondary" disabled={hint>=2||coins<5} onClick={()=>{onSpend(5);setHint(2);}}><Coins size={17}/>Ayuda guiada · 5</button><small>{coins} monedas ficticias · intentos ∞</small></div>}
    {hint>0&&<aside className="hint" role="status"><b>{hint===1?'Una pista para empezar':'Veámoslo paso a paso'}</b><p>{q.hints[hint-1]}</p><small>Con ayuda, este ejercicio queda pendiente de repaso sin pistas.</small></aside>}
    <AnswerReveal question={q} open={showAnswer} completed={!!feedback?.correct} onToggle={()=>{const next=!showAnswer;setShowAnswer(next);if(next)setRevealed(true);}}/>
    {feedback&&<AnswerFeedback correct={feedback.correct} error={feedback.error} explanation={q.explanation} xp={earned} celebrate={celebrate}/>}
    {draftError&&<p className="notice" role="alert">{draftError}</p>}<button className="primary wide" disabled={!canCheck} onClick={feedback?.correct?onNext:check}>{feedback?.correct?'Continuar':'Comprobar'}<ArrowRight size={18}/></button>{rules&&<Laws mode={course==='precalculo'?'algebra':'logic'} onClose={()=>setRules(false)}/>}</section>;
}
