import { useId, useState } from 'react';
import { Check, ChevronRight, FlaskConical, Lightbulb, RotateCcw } from 'lucide-react';
import type { Course } from './types';
import { classify, evaluateLogic, parseLogic, truthRows } from './engine';
import { SymbolInput } from './Keyboard';
export function realRoots(a:number,b:number,c:number):number[]|'all' {
  if(a===0)return b===0?(c===0?'all':[]):[-c/b];
  const delta=b*b-4*a*c;if(delta<0)return [];
  if(delta===0)return [-b/(2*a)];
  return [(-b-Math.sqrt(delta))/(2*a),(-b+Math.sqrt(delta))/(2*a)].sort((x,y)=>x-y);
}
const fmt=(n:number)=>Number(n.toFixed(3)).toString();
export function Explorers({course}:{course:Course}) {
  const [tab,setTab]=useState('logic');
  return <section className="explore-suite"><div className="explore-heading"><span className="eyebrow">LABORATORIO DE IDEAS</span><h2>Tocá. Cambiá. Entendé.</h2><p>Explorá una idea antes de memorizarla. Cada cambio muestra qué pasa y por qué.</p></div>{course==='discreta'?<><div className="hub-tabs" role="group" aria-label="Explorador de discreta"><button className={tab==='logic'?'active':''} aria-pressed={tab==='logic'} onClick={()=>setTab('logic')}>Lógica en vivo</button><button className={tab==='sets'?'active':''} aria-pressed={tab==='sets'} onClick={()=>setTab('sets')}>Conjuntos en vivo</button></div>{tab==='logic'?<LogicExplorer/>:<SetExplorer/>}</>:<EquationExplorer/>}</section>;
}
function LogicExplorer() {
  const [expression,setExpression]=useState('P→Q'),[values,setValues]=useState<Record<string,boolean>>({P:true,Q:false,R:true,S:false});
  let vars:string[]=[],rows:ReturnType<typeof truthRows>=[],result=false,label='',error='';
  try {vars=[...new Set(expression.toUpperCase().match(/[A-Z]/g)||[])].sort();if(vars.length>4)throw new Error('Explorá hasta cuatro variables a la vez.');rows=truthRows(expression,vars);result=evaluateLogic(parseLogic(expression),values);label=classify(expression);}catch(e){error=e instanceof Error?e.message:'Revisá la expresión.';}
  const presets=[['∧','P∧Q','Conjunción'],['∨','P∨Q','Disyunción'],['→','P→Q','Implicación'],['↔','P↔Q','Bicondicional'],['¬','¬(P∧Q)','De Morgan'],['⊻','P⊻Q','Exclusiva']];
  const descriptions:Record<string,string>={'P∧Q':'Para obtener V, las dos entradas deben ser V.','P∨Q':'Basta con que una entrada sea V; también vale si las dos lo son.','P→Q':'Solo es F cuando P es V y Q es F. Si P es F, la implicación es V.','P↔Q':'Es V si P y Q coinciden; es F si tienen valores distintos.','¬(P∧Q)':'Primero se calcula P∧Q y después se invierte su valor. Equivale a ¬P∨¬Q.','P⊻Q':'Es V cuando exactamente una entrada es V.'};
  return <div className="card logic-explorer"><div className="operator-presets" role="group" aria-label="Elegir conector">{presets.map(([s,e,name])=><button key={e} className={expression===e?'selected':''} aria-label={`Explorar ${name}`} onClick={()=>setExpression(e)}><b>{s}</b><small>{name}</small></button>)}</div>
    <div className="live-logic"><div className="logic-switches">{vars.map(v=><button key={v} aria-label={`Cambiar ${v}`} aria-pressed={!!values[v]} className={values[v]?'truth-on':''} onClick={()=>setValues(old=>({...old,[v]:!old[v]}))}><b>{v}</b><span>{values[v]?'V':'F'}</span><small>Tocar para cambiar</small></button>)}</div><ChevronRight size={26}/><div className={`logic-output ${!error&&result?'truth-on':''}`} aria-live="polite"><small>RESULTADO</small><b>{error?'?':result?'V':'F'}</b><span>{expression||'Tu expresión'}</span></div></div>
    <p className="notice"><Lightbulb size={16}/>{error||descriptions[expression]||`Con las entradas elegidas, la expresión vale ${result?'V':'F'}. Cambiá una entrada y compará la fila resaltada.`}</p>
    <details className="custom-expression"><summary>Construir otra expresión con símbolos</summary><SymbolInput value={expression} onChange={setExpression} label="Expresión para explorar"/></details>
    {!error&&<><div className="row"><h3>La tabla cambia con vos.</h3><span className="status-chip">{label}</span></div><div className="table-scroll"><table><thead><tr>{vars.map(v=><th key={v}>{v}</th>)}<th>{expression}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className={vars.every(v=>r.values[v]===!!values[v])?'current-truth-row':''}>{vars.map(v=><td key={v}>{r.values[v]?'V':'F'}</td>)}<td><b>{r.result?'V':'F'}</b></td></tr>)}</tbody></table></div><small>La fila resaltada corresponde a los valores que acabás de elegir.</small></>}
  </div>;
}
function SetExplorer() {
  const universe=[1,2,3,4,5,6];const [a,setA]=useState([1,2,3]),[b,setB]=useState([3,4,5]),[op,setOp]=useState('union');
  const operators=[['union','A ∪ B','Todo lo que está en A o en B.'],['intersection','A ∩ B','Solo lo que está en ambos.'],['difference','A − B','Lo que está en A y no en B.'],['complement','Aᶜ','Lo que está en el universo y no en A.']];
  const result=universe.filter(n=>op==='union'?a.includes(n)||b.includes(n):op==='intersection'?a.includes(n)&&b.includes(n):op==='difference'?a.includes(n)&&!b.includes(n):!a.includes(n));
  function toggle(n:number,which:'a'|'b'){const setter=which==='a'?setA:setB;setter(old=>old.includes(n)?old.filter(x=>x!==n):[...old,n].sort());}
  return <section className="card set-explorer"><span className="eyebrow">UNIVERSO Ω = {'{1, 2, 3, 4, 5, 6}'}</span><h3>Construí tus conjuntos.</h3><p>Tocá un número para agregarlo o quitarlo. Observá qué elementos llegan al resultado.</p><div className="set-builder-grid">{[['a',a],['b',b]].map(([which,values])=><div key={String(which)}><b>Conjunto {String(which).toUpperCase()}</b><div className="set-options">{universe.map(n=><button key={n} aria-label={`${String(which).toUpperCase()} contiene ${n}`} aria-pressed={(values as number[]).includes(n)} className={(values as number[]).includes(n)?'selected':''} onClick={()=>toggle(n,which as 'a'|'b')}>{n}</button>)}</div></div>)}</div>
    <div className="operator-presets">{operators.map(([id,name])=><button key={id} aria-pressed={op===id} className={op===id?'selected':''} onClick={()=>setOp(id)}>{name}</button>)}</div><div className="set-result" aria-live="polite"><small>{operators.find(o=>o[0]===op)?.[1]}</small><b>{'{'}{result.join(', ')||'∅'}{'}'}</b><p>{operators.find(o=>o[0]===op)?.[2]}</p></div>
    <div className="element-decisions">{universe.map(n=><div key={n} className={result.includes(n)?'included':''}><b>{n}</b><span>A: {a.includes(n)?'sí':'no'} · B: {b.includes(n)?'sí':'no'}</span><span>{result.includes(n)?<><Check size={15}/>En el resultado</>:'Fuera del resultado'}</span></div>)}</div><p className="notice">El complemento depende del universo. Acá usamos exactamente los seis números de arriba.</p>
  </section>;
}
function EquationExplorer() {
  const [a,setA]=useState(1),[b,setB]=useState(-2),[c,setC]=useState(-3),[show,setShow]=useState(true);
  const roots=realRoots(a,b,c),delta=b*b-4*a*c,vertex=a!==0?[-b/(2*a),c-b*b/(4*a)]:null;
  const clipId=useId().replace(/:/g,'');const yLimit=Math.max(8,Math.abs(vertex?.[1]||0)+3,Math.abs(c)+3);
  const x=(n:number)=>40+(n+8)/16*440,y=(n:number)=>280-(n+yLimit)/(2*yLimit)*240;
  const curve=Array.from({length:241},(_,i)=>{const t=-8+i/15;return `${i?'L':'M'}${x(t).toFixed(2)},${y(a*t*t+b*t+c).toFixed(2)}`;}).join(' ');
  const equation=`${a}x² ${b<0?'−':'+'} ${Math.abs(b)}x ${c<0?'−':'+'} ${Math.abs(c)} = 0`;
  return <section className="card equation-explorer"><div className="row"><div><span className="eyebrow">ENTENDÉ LAS RAÍCES</span><h3>Una ecuación que podés mover.</h3></div><FlaskConical size={28}/></div><div className="equation-presets">{[[1,-2,-3,'Dos raíces'],[1,-4,4,'Una raíz'],[1,0,2,'Sin raíces'],[0,2,-4,'Recta']].map(([aa,bb,cc,name])=><button key={name} onClick={()=>{setA(Number(aa));setB(Number(bb));setC(Number(cc));}}>{name}</button>)}</div>
    <div className="equation-layout"><div><div className="live-equation" aria-live="polite">{equation}</div>{[['a',a,setA,4],['b',b,setB,6],['c',c,setC,6]].map(([name,value,set,max])=><label className="coefficient-slider" key={String(name)}><span>{String(name)}<b>{Number(value)}</b></span><input type="range" aria-label={`Coeficiente ${name}`} min={-Number(max)} max={Number(max)} step="1" value={Number(value)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}<button className="secondary" onClick={()=>{setA(1);setB(-2);setC(-3);}}><RotateCcw size={16}/>Reiniciar ejemplo</button><label className="scope-toggle"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/>Mostrar raíces y solución</label></div>
    <svg className="equation-graph" viewBox="0 0 520 320" role="img" aria-label={`Gráfica de ${equation}. ${roots==='all'?'Todos los números reales son solución':`${roots.length} raíces reales`}.`}><defs><clipPath id={clipId}><rect x="40" y="40" width="440" height="240"/></clipPath></defs><rect x="40" y="40" width="440" height="240" rx="10" fill="var(--bg)"/>{[-6,-4,-2,0,2,4,6].map(t=><g key={t}><line x1={x(t)} x2={x(t)} y1="40" y2="280" stroke="var(--border)"/><text x={x(t)} y="299" textAnchor="middle">{t}</text></g>)}<line x1="40" x2="480" y1={y(0)} y2={y(0)} stroke="var(--muted)"/><line x1={x(0)} x2={x(0)} y1="40" y2="280" stroke="var(--muted)"/><text x="489" y={y(0)+5}>x</text><text x={x(0)+10} y="32">y</text><path d={curve} clipPath={`url(#${clipId})`} fill="none" stroke="var(--button-accent)" strokeWidth="3"/>{show&&Array.isArray(roots)&&roots.map(r=><g key={r}><circle cx={x(r)} cy={y(0)} r="6" fill="#168979" stroke="var(--surface)" strokeWidth="2"/><text x={x(r)} y={y(0)-14} textAnchor="middle">{fmt(r)}</text></g>)}<text x="45" y="26">y: −{fmt(yLimit)} a {fmt(yLimit)}</text></svg></div>
    <p className="notice"><Lightbulb size={16}/>Resolver significa encontrar los valores de x donde la gráfica toca o cruza el eje horizontal.</p>
    {show&&<div className="equation-solution" aria-live="polite"><h3>{roots==='all'?'Infinitas soluciones reales':roots.length===0?'No hay soluciones reales':`${roots.length} ${roots.length===1?'solución real':'soluciones reales'}`}</h3>{Array.isArray(roots)&&roots.length>0&&<p className="root-chips">{roots.map(r=><span key={r}>x = {fmt(r)}</span>)}</p>}{a!==0?<ol><li>Identificá a = {a}, b = {b}, c = {c}.</li><li>Calculá Δ = b² − 4ac = ({b})² − 4·({a})·({c}) = {delta}.</li><li>{delta<0?'Δ es negativo: no hay raíces reales.':delta===0?`Δ = 0: hay una raíz doble, x = −b/(2a) = ${fmt(-b/(2*a))}.`:`Δ es positivo: aplicá x = (−b ± √Δ)/(2a). Las raíces aproximadas son ${(roots as number[]).map(fmt).join(' y ')}.`}</li></ol>:b!==0?<p>Como a = 0, la ecuación es lineal: {b}x + ({c}) = 0. Entonces x = −c/b = {fmt(-c/b)}.</p>:<p>{c===0?'La igualdad 0 = 0 se cumple para cualquier x.':`La igualdad ${c} = 0 nunca se cumple.`}</p>}<small>Los valores decimales se muestran con hasta tres cifras. Esta vista ayuda a comprender ecuaciones; no reemplaza una respuesta exacta con radicales.</small></div>}
  </section>;
}
