import type { Lesson, Question, QuestionType } from './types';

// Each row is a new, authored exercise. These are lesson practice, not transcriptions
// of numbered book problems. The final two rows of each lesson are challenges.
type Seed = [type: 'c' | 't' | 'a' | 'l' | 's', prompt: string, answer: string, explanation: string, options?: string[]];
const practice: Record<string, Seed[]> = {
  'Conjuntos numéricos': [
    ['c','¿A qué conjunto más pequeño pertenece 0?','ℕ','En esta app ℕ incluye el cero.',['ℕ','ℤ pero no ℕ','Irracionales']],
    ['c','¿Cuál de estos números es entero?','−12','−12 es un entero; las otras opciones no lo son.',['−12','2/3','√2']],
    ['c','¿Qué clase de número es 0,75?','Racional','0,75 = 3/4.',['Racional','Irracional','No real']],
    ['c','¿Cuál de los siguientes es irracional?','√5','5 no es un cuadrado perfecto.',['√5','√25','0,2']],
    ['a','Escribí 0,125 como fracción irreducible (a/b).','1/8','125/1000 se reduce dividiendo entre 125.'],
    ['c','¿Es √(16/25) racional?','Sí, vale 4/5','La raíz principal es 4/5.',['Sí, vale 4/5','No, es irracional','No es real']],
    ['c','¿Puede un irracional elevado al cuadrado ser racional?','Sí: (√2)² = 2','La clasificación puede cambiar al operar.',['Sí: (√2)² = 2','No, nunca','Solo si es negativo']],
  ],
  'Signos y jerarquía de operaciones': [
    ['t','Calculá −7 + 12.','5','Restá 12 − 7 y conservá el signo de 12.'],
    ['t','Calculá (−4)(−3).','12','Dos factores negativos dan positivo.'],
    ['t','Calculá 18 ÷ (−3) + 2.','-4','18 ÷ (−3) = −6; después sumá 2.'],
    ['t','Calculá 3 + 4 · (2 − 5).','-9','Primero 2 − 5 = −3; luego 4·(−3) = −12.'],
    ['t','Calculá 20 − 12 ÷ 3 · 2.','12','División y multiplicación van de izquierda a derecha: 12 ÷ 3 · 2 = 8.'],
    ['t','Calculá −(−2)³ + (−3)².','17','(−2)³ = −8; su opuesto es 8. El cuadrado vale 9.'],
    ['t','Calculá 6 − [2 − (−3)²] · (−2).','-8','El corchete vale 2 − 9 = −7; multiplicado por −2 vale 14.'],
  ],
  'Fracciones numéricas': [
    ['a','Calculá 1/3 + 1/3.','2/3','Con igual denominador sumá numeradores.'],
    ['a','Calculá 2/5 · 3/4.','3/10','El producto 6/20 se reduce a 3/10.'],
    ['a','Calculá 3/4 − 1/2.','1/4','Convertí 1/2 a 2/4.'],
    ['a','Calculá 2/3 + 1/6.','5/6','El común denominador es 6.'],
    ['a','Calculá 4/5 ÷ 2/3.','6/5','Multiplicá 4/5 por 3/2 y reducí.'],
    ['a','Calculá (3/4 − 1/6) · 12/7.','1','3/4 − 1/6 = 7/12, que cancela con 12/7.'],
    ['a','Calculá 1 ÷ (1/2 + 1/3).','6/5','Dentro del paréntesis obtenés 5/6; su recíproco es 6/5.'],
  ],
  'Leyes de potencias': [
    ['t','Calculá 3².','9','3 · 3 = 9.'],
    ['t','Calculá 5⁰.','1','Toda base no nula elevada a cero vale 1.'],
    ['a','Simplificá x² · x³.','x^5','Sumá exponentes de igual base.'],
    ['a','Simplificá (y²)³.','y^6','Multiplicá los exponentes: 2 · 3.'],
    ['a','Simplificá 2³ · 2⁻¹.','4','2³/2 = 4.'],
    ['a','Simplificá (3x²)².','9x^4','Elevá tanto 3 como x² al cuadrado.'],
    ['a','Simplificá (2a³b²)(−3a²b) / (6a²b), con a,b ≠ 0.','-a^3*b^2','Coeficiente −6/6; para a, 3 + 2 − 2 = 3; para b, 2 + 1 − 1 = 2.'],
  ],
  'Raíces y valor absoluto': [
    ['t','Calculá √49.','7','La raíz cuadrada principal es no negativa.'],
    ['t','Calculá |−8|.','8','Es la distancia entre −8 y cero.'],
    ['t','Calculá ∛(−27).','-3','(−3)³ = −27.'],
    ['t','Calculá √81 − |−4|.','5','9 − 4 = 5.'],
    ['c','En ℝ, ¿cuándo existe √(x−5)?','x ≥ 5','El radicando debe ser no negativo.',['x ≥ 5','x ≤ 5','Cualquier x']],
    ['t','Si x = −6, calculá √(x²) + x.','0','√(x²) = |x| = 6; 6 − 6 = 0.'],
    ['c','Simplificá √50 − √8.','3√2','5√2 − 2√2 = 3√2.',['3√2','√42','7√2']],
  ],
  'Variables y valor numérico': [
    ['t','Evaluá 2x + 1 para x = 3.','7','2·3 + 1 = 7.'],
    ['t','Evaluá x² para x = −4.','16','(−4)² = 16.'],
    ['t','Evaluá 3a − 2b para a = 2 y b = −1.','8','6 − (−2) = 8.'],
    ['t','Evaluá x² − 2x + 1 para x = 0.','1','Los términos con x desaparecen.'],
    ['t','Evaluá 2(x − 3)² para x = 1.','8','Primero (1 − 3)² = 4; luego multiplicá por 2.'],
    ['t','Para P(x)=x³−2x²+3, calculá P(−2).','-13','−8 − 8 + 3 = −13.'],
    ['t','Evaluá (a²−b²)/(a−b) para a=5, b=2.','7','(25−4)/3 = 7, o cancelá a−b con a²−b².'],
  ],
  'Monomios y términos semejantes': [
    ['t','¿Qué grado tiene 4x³?','3','El exponente de x es 3.'],
    ['c','¿Qué término es semejante a 2x²y?','−5x²y','La parte literal coincide exactamente.',['−5x²y','2xy²','2x²']],
    ['a','Reducí 3x + 4x.','7x','Sumá coeficientes.'],
    ['t','¿Qué grado tiene 9a²bc³?','6','2 + 1 + 3 = 6.'],
    ['a','Reducí 2x²−5x+3x²+x.','5x^2-4x','Agrupá los términos de grado 2 y de grado 1.'],
    ['a','Multiplicá (−2a²b)(3ab³).','-6a^3b^4','Multiplicá coeficientes y sumá exponentes de cada variable.'],
    ['t','¿Qué grado tiene 4x²y³ − x⁴ + 7?','5','El término x²y³ tiene grado total 5, el mayor.'],
  ],
  'Suma y resta de polinomios': [
    ['a','Sumá (x+2)+(2x+1).','3x+3','Sumá términos semejantes.'],
    ['a','Restá (x+5)−(x+2).','3','El término x se cancela.'],
    ['a','Sumá (x²−3x)+(2x²+x).','3x^2-2x','Reuní cuadrados y términos lineales.'],
    ['a','Restá (3a²+2a−1)−(a²−a+4).','2a^2+3a-5','Distribuí el signo negativo antes de reducir.'],
    ['a','Sumá (2x³−x+4)+(−x³+3x−7).','x^3+2x-3','Sumá coeficientes en cada grado.'],
    ['a','Restá (4x²−3x+2)−(−2x²+5x−6).','6x^2-8x+8','Cambiá los tres signos del segundo polinomio.'],
    ['a','Si P=x²−2x+3 y Q=2x²+x−4, hallá 2P−Q.','-5x+10','2P = 2x²−4x+6; restá Q y cancelá x².'],
  ],
  'Multiplicación y productos notables': [
    ['a','Desarrollá x(x+3).','x^2+3x','Distribuí x.'],
    ['a','Desarrollá (x+1)².','x^2+2x+1','Incluí el término cruzado 2x.'],
    ['a','Desarrollá (x+2)(x+3).','x^2+5x+6','Los términos lineales suman 5x.'],
    ['a','Desarrollá (a−4)(a+4).','a^2-16','Producto de suma por diferencia.'],
    ['a','Desarrollá (2x+1)(x−3).','2x^2-5x-3','Los términos cruzados son −6x y +x.'],
    ['a','Desarrollá (x−2)³.','x^3-6x^2+12x-8','Multiplicá (x−2)² por (x−2).'],
    ['a','Desarrollá (2x−3)(x²+3x+9).','2x^3+3x^2+9x-27','Distribuí ambos términos del primer factor y reducí.'],
  ],
  'División de polinomios': [
    ['t','¿Cuál es el resto de x²−1 al dividir entre x−1?','0','Evaluá en x=1.'],
    ['a','Dividí x²+3x+2 entre x+1. Escribí el cociente.','x+2','(x+1)(x+2) reproduce el dividendo.'],
    ['t','¿Cuál es el resto de x²+1 entre x−2?','5','Por el teorema del resto, P(2)=5.'],
    ['a','Dividí x²−4 entre x−2. Escribí el cociente.','x+2','Es una diferencia de cuadrados.'],
    ['a','Dividí 2x²+5x+3 entre x+1. Escribí el cociente.','2x+3','(x+1)(2x+3) = 2x²+5x+3.'],
    ['t','¿Cuál es el resto de 3x³−2x+1 entre x+2?','-19','P(−2)=3(−8)−2(−2)+1 = −19.'],
    ['a','Dividí x³+2x²−x−2 entre x+2. Escribí el cociente.','x^2-1','Agrupá: (x+2)(x²−1), con resto cero.'],
  ],
  'Factor común y agrupación': [
    ['a','Factorizá 3x+6.','3*(x+2)','Extraé el factor común 3.'],
    ['a','Factorizá x²+2x.','x*(x+2)','Extraé x.'],
    ['a','Factorizá 4a²+6a.','2a*(2a+3)','El factor común máximo es 2a.'],
    ['a','Factorizá xy+xz.','x*(y+z)','Ambos términos tienen x.'],
    ['a','Factorizá ax+ay+2x+2y.','(a+2)*(x+y)','Agrupá a(x+y)+2(x+y).'],
    ['a','Factorizá 6x³−9x²+3x.','3x*(2x^2-3x+1)','Cada término contiene 3x.'],
    ['a','Factorizá x²−xy+3x−3y.','(x+3)*(x-y)','Agrupá x(x−y)+3(x−y).'],
  ],
  'Trinomios y diferencias de cuadrados': [
    ['a','Factorizá x²−4.','(x-2)*(x+2)','Es la diferencia de x² y 2².'],
    ['a','Factorizá x²+3x+2.','(x+1)*(x+2)','1+2=3 y 1·2=2.'],
    ['a','Factorizá x²−9.','(x-3)*(x+3)','Diferencia de cuadrados.'],
    ['a','Factorizá x²−x−6.','(x-3)*(x+2)','−3+2=−1 y su producto es −6.'],
    ['a','Factorizá 9a²−16.','(3a-4)*(3a+4)','Las bases de los cuadrados son 3a y 4.'],
    ['a','Factorizá 3x²+10x+3.','(3x+1)*(x+3)','Los términos cruzados suman 9x+x.'],
    ['a','Factorizá 4x²−12x+9.','(2x-3)^2','Es un trinomio cuadrado perfecto.'],
  ],
  'Suma y diferencia de cubos': [
    ['c','¿Cuánto vale 2³?','8','2·2·2 = 8.',['8','6','4']],
    ['a','Factorizá x³−1.','(x-1)*(x^2+x+1)','Usá 1 = 1³.'],
    ['a','Factorizá x³+8.','(x+2)*(x^2-2x+4)','8 = 2³; en suma de cubos el término cruzado lleva menos.'],
    ['a','Factorizá a³−27.','(a-3)*(a^2+3a+9)','27 = 3³.'],
    ['a','Factorizá 8x³+1.','(2x+1)*(4x^2-2x+1)','Las bases son 2x y 1.'],
    ['a','Factorizá 27y³−64.','(3y-4)*(9y^2+12y+16)','Las bases son 3y y 4.'],
    ['a','Factorizá x⁶−64 mediante diferencia de cubos (escribí un producto).','(x^2-4)*(x^4+4x^2+16)','Tomá a=x² y b=4. El producto reproduce x⁶−64.'],
  ],
  'Raíces racionales y factores': [
    ['t','Evaluá P(2) para P(x)=x−2.','0','Sustituí x=2.'],
    ['c','Si P(−3)=0, ¿qué factor tiene P?','x+3','El factor asociado a r es x−r.',['x+3','x−3','x']],
    ['t','Evaluá P(1) para P(x)=x²−4x+3.','0','1−4+3=0, así que x−1 divide P.'],
    ['c','Para x²−5x+6, ¿cuál NO puede ser raíz racional?','4','Un entero candidato debe dividir al término constante 6.',['4','2','3']],
    ['a','Factorizá x²−5x+6.','(x-2)*(x-3)','Las raíces son 2 y 3.'],
    ['t','Evaluá P(−2) para P(x)=2x³+3x²−8x−12.','0','−16+12+16−12=0.'],
    ['a','Factorizá x³−x²−4x+4.','(x-1)*(x-2)*(x+2)','Agrupá (x−1)(x²−4) y aplicá diferencia de cuadrados.'],
  ],
  'División sintética': [
    ['t','¿Qué valor r usás al dividir entre x−3?','3','El divisor es x−r.'],
    ['t','¿Qué valor r usás al dividir entre x+2?','-2','x+2 = x−(−2).'],
    ['t','¿Qué coeficiente corresponde a x en x³+2x²−5?','0','El término x falta, pero su posición se conserva.'],
    ['t','Hallá el resto de x²−3x+2 entre x−1.','0','P(1)=1−3+2=0.'],
    ['a','Hallá el cociente de x²−3x+2 entre x−1.','x-2','Los coeficientes sintéticos finales son 1, −2, 0.'],
    ['t','Hallá el resto de 2x³−x²+4 entre x+2.','-16','P(−2)=−16−4+4=−16; incluí 0x.'],
    ['a','Hallá el cociente de x³−4x²+x+6 entre x−2.','x^2-2x-3','Con r=2, la fila final es 1, −2, −3, 0.'],
  ],
  'Factorización completa': [
    ['a','Factorizá x²−1 en ℝ.','(x-1)*(x+1)','Diferencia de cuadrados.'],
    ['t','Hallá Δ de x²−4x+4.','0','(−4)²−4·1·4=0.'],
    ['a','Factorizá x²+2x+1.','(x+1)^2','Hay una raíz doble en −1.'],
    ['c','¿Es x²+4 reducible en factores lineales reales?','No','Su discriminante es negativo.',['No','Sí, (x+2)(x+2)','Sí, (x−2)(x+2)']],
    ['a','Factorizá x³−x en ℝ.','x*(x-1)*(x+1)','Extraé x y luego una diferencia de cuadrados.'],
    ['a','Factorizá 2x³−8x en ℝ.','2x*(x-2)*(x+2)','Extraé 2x y factorizá x²−4.'],
    ['a','Factorizá x⁴−5x²+4 en factores lineales reales.','(x-2)*(x+2)*(x-1)*(x+1)','Tomá t=x²: (t−1)(t−4); ambos son diferencias de cuadrados.'],
  ],
  'Fracciones y dominio': [
    ['t','¿Qué valor excluye 1/(x−3)?','3','El denominador no puede ser cero.'],
    ['t','¿Qué valor excluye (x+1)/x?','0','x está en el denominador original.'],
    ['a','Simplificá (2x)/(4x), con x≠0.','1/2','Cancelá el factor 2x, conservando la restricción dada.'],
    ['c','¿Qué valores excluye 1/(x²−9)?','−3 y 3','x²−9=(x−3)(x+3).',['−3 y 3','Solo 3','Solo 0']],
    ['a','Simplificá (x²−4)/(x−2), con x≠2.','x+2','El factor x−2 se cancela; el dominio original sigue excluyendo 2.'],
    ['c','Después de simplificar x(x−1)/x, ¿se admite x=0?','No','La fracción original no estaba definida en cero.',['No','Sí','Solo si x=1']],
    ['c','Simplificás (x²−1)/(x²−x). ¿Qué valores siguen excluidos?','0 y 1','El denominador original x(x−1) excluye 0 y 1 aunque se cancele x−1.',['0 y 1','Solo 0','Solo 1']],
  ],
  'Operar fracciones algebraicas': [
    ['a','Sumá 1/x + 2/x, con x≠0.','3/x','Los denominadores ya coinciden.'],
    ['a','Multiplicá (x/2)(4/x), con x≠0.','2','Cancelá el factor x no nulo.'],
    ['a','Sumá 1/x + 1/(2x), con x≠0.','3/(2x)','El común denominador es 2x.'],
    ['a','Restá 1/(x−1) − 2/(x−1), con x≠1.','-1/(x-1)','Restá los numeradores sin cambiar el denominador.'],
    ['a','Multiplicá (x²−1)/(x+1) por 1/x, con x≠−1,0.','(x-1)/x','Factorizá x²−1 y cancelá x+1.'],
    ['a','Dividí (x/2) entre (x²/4), con x≠0.','2/x','Multiplicá x/2 por 4/x² y cancelá x.'],
    ['a','Sumá 1/(x−1) + 1/(x+1), con x≠±1.','2x/(x^2-1)','Numerador común (x+1)+(x−1)=2x.'],
  ],
  'Radicales y racionalización': [
    ['t','Calculá √9.','3','La raíz principal es 3.'],
    ['c','¿Cuál es el conjugado de 2+√3?','2−√3','Cambiá el signo entre los dos términos.',['2−√3','−2−√3','2+√3']],
    ['c','Racionalizá 1/√2.','√2/2','Multiplicá por √2/√2.',['√2/2','√2','2/√2']],
    ['t','Calculá (√5+2)(√5−2).','1','Diferencia de cuadrados: 5−4=1.'],
    ['c','¿Cuánto vale √(x²) si x<0?','−x','La raíz es |x|; para x negativo, |x|=−x.',['−x','x','x²']],
    ['c','Racionalizá 1/(√3+1).','(√3−1)/2','Multiplicá por el conjugado; 3−1=2.',['(√3−1)/2','(√3+1)/2','√3−1']],
    ['c','Para 1/(√x−2), ¿qué dominio real es correcto?','x≥0 y x≠4','La raíz exige x≥0 y el denominador excluye x=4.',['x≥0 y x≠4','x>0','Todos los reales excepto 4']],
  ],
  'Ecuaciones lineales y equivalencia': [
    ['t','Resolvé x+4=9. Escribí x.','5','Restá 4 en ambos lados.'],
    ['t','Resolvé 2x=14. Escribí x.','7','Dividí por 2.'],
    ['t','Resolvé 3x−2=10. Escribí x.','4','3x=12, luego x=4.'],
    ['t','Resolvé 5−2x=11. Escribí x.','-3','−2x=6, así que x=−3.'],
    ['t','Resolvé 2(x+3)=x+10. Escribí x.','4','2x+6=x+10.'],
    ['c','¿Cuántas soluciones tiene 4(x−1)=4x−5?','Ninguna','Se obtiene −4=−5.',['Ninguna','Una','Infinitas']],
    ['a','Resolvé (x−1)/2 + (x+2)/3 = 4. Escribí x.','23/5','Multiplicá por 6: 3x−3+2x+4=24; 5x=23.'],
  ],
  'Ecuaciones cuadráticas': [
    ['t','¿Cuánto vale el discriminante de x²−4=0?','16','b=0, a=1, c=−4: Δ=16.'],
    ['c','¿Cuáles son las raíces de x²=9?','−3 y 3','Al tomar raíz cuadrada considerá ambos signos.',['−3 y 3','Solo 3','Solo −3']],
    ['t','¿Cuál es la raíz doble de (x−5)²=0?','5','El factor se anula en 5.'],
    ['c','Resolvé x²+x−6=0.','−3 y 2','(x+3)(x−2)=0.',['−3 y 2','3 y −2','−6 y 1']],
    ['t','Hallá Δ de 3x²−2x+1=0.','-8','(−2)²−4·3·1=−8.'],
    ['c','Resolvé 2x²−5x−3=0.','−1/2 y 3','(2x+1)(x−3)=0.',['−1/2 y 3','1/2 y −3','−1 y 3']],
    ['s','Resolvé 3x²−2x−1=0 en ℝ. Seleccioná todas las raíces.','-1/3,1','(3x+1)(x−1)=0.',['-3','-1','-1/3','0','1/3','1','3']],
  ],
  'Ecuaciones de grado superior': [
    ['t','¿Qué raíz se obtiene de x(x−2)=0 si el primer factor se anula?','0','x=0 hace cero el producto.'],
    ['c','¿Cuáles son las raíces de x³−x=0?','−1, 0, 1','x(x−1)(x+1)=0.',['−1, 0, 1','−1 y 1','Solo 0']],
    ['t','¿Cuántas raíces reales distintas tiene x(x−1)²=0?','2','Son 0 y 1; la multiplicidad no suma una raíz distinta.'],
    ['c','Resolvé x⁴−16=0 en ℝ.','−2 y 2','x⁴=16; las raíces reales son ±2.',['−2 y 2','Solo 2','−4 y 4']],
    ['c','Resolvé (x²−1)(x²+4)=0 en ℝ.','−1 y 1','x²+4 no tiene raíces reales.',['−1 y 1','−2, −1, 1, 2','Ninguna']],
    ['c','Resolvé x³−4x²=0.','0 y 4','x²(x−4)=0.',['0 y 4','Solo 4','−4 y 0']],
    ['c','Resolvé x⁴−10x²+9=0 en ℝ.','−3, −1, 1, 3','Con t=x², (t−1)(t−9)=0.',['−3, −1, 1, 3','−9, −1, 1, 9','−3 y 3']],
  ],
  'Ecuaciones racionales': [
    ['t','¿Qué valor excluye la ecuación 1/(x−4)=2?','4','El denominador original no puede ser cero.'],
    ['t','Resolvé 1/x=1/2. Escribí x.','2','x≠0; multiplicá en cruz.'],
    ['t','Resolvé 2/(x−1)=1. Escribí x.','3','x−1=2 y x=3 no está excluido.'],
    ['c','¿Cuántas soluciones tiene (x−2)/(x−2)=0?','Ninguna','Para x≠2 el cociente vale 1; x=2 está excluido.',['Ninguna','Una: x=2','Todos excepto 2']],
    ['t','Resolvé (x+2)/x=3. Escribí x.','1','Con x≠0, x+2=3x; x=1.'],
    ['c','Resolvé 1/(x−1)=1/(x+1).','No tiene solución','Con x≠±1, igualar denominadores daría x+1=x−1.',['No tiene solución','x=0','x=1']],
    ['t','Resolvé 1/x + 1/(x−2)=1, con x≠0,2. Escribí la suma de las soluciones reales.','4','Multiplicar por x(x−2) da x²−4x+2=0; la suma de raíces es 4.'],
  ],
  'Ecuaciones con radicales': [
    ['t','Resolvé √x=3. Escribí x.','9','Al elevar al cuadrado, x=9; comprobá √9=3.'],
    ['t','Resolvé √(x+1)=2. Escribí x.','3','x+1=4 y el candidato cumple.'],
    ['c','Para √x=x−2, ¿qué condición debe cumplir x?','x≥2','El lado derecho debe ser no negativo y la raíz debe existir.',['x≥2','x≥0','x≤2']],
    ['t','Resolvé √(2x+1)=5. Escribí x.','12','2x+1=25; x=12 cumple.'],
    ['c','Al resolver √(x+2)=−1, ¿qué pasa?','No hay solución','Una raíz principal nunca vale −1.',['No hay solución','x=−1','x=1']],
    ['t','Resolvé √(x+6)=x. Escribí x.','3','x≥0; x+6=x² da x=3 o x=−2; solo 3 cumple.'],
    ['t','Resolvé √(x+1)=x−1. Escribí x.','3','x≥1; x+1=(x−1)² da x=0 o 3; verificá y conservá 3.'],
  ],
  'Plantear problemas de aplicación': [
    ['t','Un cuaderno cuesta 4 y una lapicera 2. ¿Cuánto cuestan juntos?','6','Sumá los dos precios.'],
    ['t','Tres entradas iguales cuestan 24. ¿Precio de una?','8','Dividí 24 entre 3.'],
    ['t','Un número aumentado en 7 es 19. Hallá el número.','12','Planteá x+7=19.'],
    ['t','La edad de Ana duplica la de Leo; juntas suman 27. ¿Edad de Leo?','9','Leo=x, Ana=2x: 3x=27.'],
    ['t','El largo de un rectángulo supera al ancho en 2; perímetro 20. ¿Ancho?','4','2x+2(x+2)=20; x=4.'],
    ['t','Dos números consecutivos suman 47. ¿Cuál es el mayor?','24','x+(x+1)=47; x=23.'],
    ['t','Dos cuadernos y tres lápices cuestan 19; un cuaderno y un lápiz cuestan 7. ¿Cuánto cuesta un lápiz?','5','Si c+l=7 y 2c+3l=19, restá 2(c+l): l=5; c=2.'],
  ],
  'Introducción y razonamiento lógico': [
    ['c','¿Un ejemplo verdadero prueba “todos los naturales son pares”?','No','Un ejemplo no alcanza para una afirmación universal.',['No','Sí']],
    ['c','¿Qué entero refuta “todo entero es positivo”?','−2','−2 es entero y no positivo.',['−2','2','10']],
    ['c','Si una conclusión es falsa y todas las premisas son verdaderas, ¿es válido el argumento?','No','Es un contraejemplo a la validez.',['No','Sí']],
    ['c','¿Qué se busca para refutar “todo múltiplo de 3 es par”?','Un múltiplo impar de 3','3 es un contraejemplo.',['Un múltiplo impar de 3','Un múltiplo par de 3','Diez casos favorables']],
    ['t','¿Cuál es el menor natural positivo que refuta “todo natural positivo es par”?','1','1 es natural positivo e impar.'],
    ['c','“Algunos enteros son negativos”. ¿Qué bastaría para demostrarlo?','Un testigo, como −1','Un existencial necesita un caso que cumpla.',['Un testigo, como −1','Comprobar todos los enteros','Un entero positivo']],
    ['c','Se observó que n(n+1) es par para 100 enteros. ¿Qué argumento demostraría el caso general?','n y n+1 son consecutivos: uno es par','En dos enteros consecutivos siempre hay uno par; por eso su producto es par para todo entero n.',['n y n+1 son consecutivos: uno es par','Basta con los 100 ejemplos','Todo entero n es par']],
  ],
  'Proposiciones y conectores': [
    ['c','Elegí el enunciado con valor de verdad definido.','7 es primo','Tiene valor de verdad definido.',['7 es primo','¿Es 7 primo?','Sumá 2']],
    ['c','Con P=V, ¿cuánto vale ¬P?','F','La negación invierte el valor.',['F','V']],
    ['c','Con P=V, Q=F, ¿cuánto vale P∧Q?','F','La conjunción exige ambas verdaderas.',['F','V']],
    ['c','Con P=V, Q=F, ¿cuánto vale P∨Q?','V','La disyunción inclusiva exige al menos una verdadera.',['V','F']],
    ['l','P: viajo. Q: leo. Escribí “no viajo o leo”.','¬P∨Q','Negá P y unilo a Q con ∨.'],
    ['c','Con P=F, Q=F, ¿cuánto vale P⊻Q?','F','La disyunción exclusiva exige exactamente una verdadera.',['F','V']],
    ['l','P: llueve. Q: hace frío. R: salgo. Escribí “ni llueve ni hace frío, pero salgo”.','¬P∧¬Q∧R','Negá P y Q; “pero” une con R mediante una conjunción.'],
  ],
  'Implicación y bicondicional': [
    ['c','Con P=V y Q=V, ¿cuánto vale P→Q?','V','Se cumple el consecuente.',['V','F']],
    ['c','Con P=F y Q=V, ¿cuánto vale P→Q?','V','Un antecedente falso no refuta la implicación material.',['V','F']],
    ['c','Con P=V y Q=F, ¿cuánto vale P↔Q?','F','Los valores no coinciden.',['F','V']],
    ['l','Escribí la recíproca de P→Q.','Q→P','Intercambiá antecedente y consecuente.'],
    ['l','Escribí la contrapositiva de P→Q.','¬Q→¬P','Invertí y negá ambas proposiciones.'],
    ['c','Con P=F y Q=F, ¿cuánto vale (P→Q)∧(Q→P)?','V','Ambas implicaciones son verdaderas; P↔Q también.',['V','F']],
    ['l','Escribí P↔Q usando solamente → y ∧.','(P→Q)∧(Q→P)','Se requieren ambas direcciones.'],
  ],
  'Tablas de verdad': [
    ['t','¿Cuántas filas tiene una tabla con una variable?','2','2¹ = 2.'],
    ['t','¿Cuántas filas tiene una tabla con cuatro variables?','16','2⁴ = 16.'],
    ['c','Con P=V y Q=F, ¿cuánto vale ¬P∨Q?','F','¬P es F y Q es F.',['F','V']],
    ['c','Con P=F y Q=V, ¿cuánto vale P→Q?','V','El antecedente es falso.',['V','F']],
    ['c','¿Qué clase de fórmula es P∨¬P?','Tautología','Todas las filas dan V.',['Tautología','Contradicción','Contingencia']],
    ['c','¿Qué clase de fórmula es (P∧Q)∨(P∧¬Q)?','Contingencia','Se simplifica a P: unas filas V y otras F.',['Contingencia','Tautología','Contradicción']],
    ['c','¿Cómo se clasifica ((P→Q)∧P)→Q?','Tautología','Si el antecedente es V, modus ponens asegura Q; en los demás casos la implicación también es V.',['Tautología','Contradicción','Contingencia']],
  ],
  'Equivalencias y simplificación': [
    ['l','Simplificá ¬¬P.','P','La doble negación devuelve P.'],
    ['l','Simplificá P∧1.','P','V es neutro de la conjunción.'],
    ['l','Simplificá P∨0.','P','F es neutro de la disyunción.'],
    ['l','Aplicá De Morgan a ¬(P∧Q).','¬P∨¬Q','Cambiá ∧ por ∨ y negá ambos.'],
    ['l','Simplificá P∧(P∨Q).','P','Ley de absorción.'],
    ['l','Simplificá (P∧Q)∨(P∧¬Q).','P','Factorizá P y usá Q∨¬Q=1.'],
    ['l','Simplificá ¬(P→Q).','P∧¬Q','P→Q equivale a ¬P∨Q; negá por De Morgan.'],
  ],
  'Traducción y contraejemplos': [
    ['l','P: estudio. Q: apruebo. Escribí “si estudio, apruebo”.','P→Q','Una condición suficiente se expresa con →.'],
    ['l','P: estudio. Q: apruebo. Escribí “estudio y no apruebo”.','P∧¬Q','Conjunción de P con la negación de Q.'],
    ['c','¿Qué valores refutan P→Q?','P=V, Q=F','Es la única fila que falsifica la implicación.',['P=V, Q=F','P=F, Q=V','P=F, Q=F']],
    ['l','P: corro. Q: descanso. Traducí “corro solo si descanso”.','P→Q','Descansar es necesario para correr.'],
    ['l','P: corro. Q: descanso. Traducí “descanso si corro”.','P→Q','La oración establece la misma dirección P→Q.'],
    ['c','¿Qué valores muestran que P→Q no equivale a Q→P?','P=F, Q=V','P→Q es V, pero Q→P es F.',['P=F, Q=V','P=V, Q=V','P=F, Q=F']],
    ['l','Negá “P si y solo si Q”.','(P∧¬Q)∨(¬P∧Q)','El bicondicional falla cuando los valores difieren.'],
  ],
  'Formas normales': [
    ['c','Elegí un literal para formar una cláusula.','P','Una variable sola es literal.',['P','P∧Q','P→Q']],
    ['c','¿P∨Q está en FNC?','Sí','Una sola cláusula disyuntiva ya está en FNC.',['Sí','No']],
    ['c','¿P∧Q está en FND?','Sí','Un solo término conjuntivo ya está en FND.',['Sí','No']],
    ['l','Eliminá → en P→Q.','¬P∨Q','Usá la equivalencia de implicación.'],
    ['c','¿Cuál es una FND de (P∨Q)∧R?','(P∧R)∨(Q∧R)','Distribuí R sobre la disyunción.',['(P∧R)∨(Q∧R)','P∨Q∨R','(P∧Q)∨R']],
    ['c','¿Cuál es una FNC de P∨(Q∧R)?','(P∨Q)∧(P∨R)','Distribuí P en cada cláusula.',['(P∨Q)∧(P∨R)','P∧Q∧R','(P∧Q)∨R']],
    ['c','¿Cuál es una FND de P↔Q?','(P∧Q)∨(¬P∧¬Q)','Es verdadero en VV y FF.',['(P∧Q)∨(¬P∧¬Q)','P∨Q','(P∧¬Q)∨(¬P∧Q)']],
  ],
  'Circuitos lógicos': [
    ['l','Dos interruptores P y Q en paralelo: escribí la salida.','P∨Q','Basta una rama conductora.'],
    ['c','P y Q en serie, P=V y Q=F. ¿Conduce?','No','Una serie requiere ambas entradas V.',['No','Sí']],
    ['c','P y Q en paralelo, P=F y Q=V. ¿Conduce?','Sí','La rama Q conduce.',['Sí','No']],
    ['l','P en serie con una rama donde Q y R están en paralelo. Escribí la salida.','P∧(Q∨R)','P es necesario, junto a Q o R.'],
    ['l','Dos ramas: P y Q en serie; R y S en serie. Están en paralelo.','(P∧Q)∨(R∧S)','Cada rama exige sus dos interruptores.'],
    ['c','Para P∧(Q∨R), P=V,Q=F,R=V. ¿Conduce?','Sí','Q∨R=V y P=V.',['Sí','No']],
    ['l','Simplificá la salida (P∧Q)∨(P∧¬Q).','P','Las dos ramas cubren ambos valores de Q siempre que P conduzca.'],
  ],
  'Reglas de inferencia': [
    ['c','P y Q son premisas. ¿Qué podés unir?','P∧Q','La adjunción combina dos premisas.',['P∧Q','P→Q','¬P']],
    ['c','Premisa P∧Q. ¿Qué se puede obtener?','P','Por simplificación.',['P','¬P','P→¬Q']],
    ['c','P→Q y P. ¿Qué regla aplicás?','Modus ponens','Afirmás el antecedente y derivás el consecuente.',['Modus ponens','Modus tollens','Falacia']],
    ['c','P→Q y ¬Q. ¿Qué derivás?','¬P','Modus tollens.',['¬P','P','Q']],
    ['c','P∨Q y ¬Q. ¿Qué derivás?','P','Silogismo disyuntivo.',['P','¬P','Q']],
    ['c','P→Q y Q→R. ¿Qué conclusión sigue?','P→R','Silogismo hipotético.',['P→R','R→P','Q→P']],
    ['c','P→Q, Q→R, P. ¿Qué conclusión final obtenés?','R','Aplicá modus ponens dos veces.',['R','¬R','¬P']],
  ],
  'Demostraciones y falacias': [
    ['c','P→Q y Q. ¿Es válido concluir P?','No','Es afirmación del consecuente.',['No','Sí']],
    ['c','P→Q y ¬P. ¿Es válido concluir ¬Q?','No','Es negación del antecedente.',['No','Sí']],
    ['c','P∨Q y ¬P. ¿Es válido concluir Q?','Sí','Silogismo disyuntivo.',['Sí','No']],
    ['c','¿Qué fila refuta P→Q, Q ⊢ P?','P=F, Q=V','Ambas premisas son V y la conclusión P es F.',['P=F, Q=V','P=V, Q=F','P=V, Q=V']],
    ['c','Si P→Q es V y P es V, ¿puede Q ser F?','No','Eso haría falsa la premisa P→Q.',['No','Sí']],
    ['c','P→Q, Q→R y ¬R. ¿Qué conclusión se sigue?','¬P','Modus tollens: ¬Q, después ¬P.',['¬P','P','R']],
    ['c','P∨Q, P→R, Q→R. ¿Qué se concluye?','R','Por casos: tanto P como Q llevan a R.',['R','¬R','P∧Q']],
  ],
  'Métodos de demostración': [
    ['c','Para probar “si n es par, n² es par”, ¿cómo escribís n?','n=2k','Es la definición de paridad para k entero.',['n=2k','n=2k+1','n=k²']],
    ['c','¿Cómo se escribe un entero impar?','2k+1','Uno más que un múltiplo de 2.',['2k+1','2k','k/2']],
    ['c','Para probar P→Q por contraposición, ¿qué probás?','¬Q→¬P','Ambas implicaciones son equivalentes.',['¬Q→¬P','Q→P','¬P→¬Q']],
    ['c','Si n=2k+1, ¿qué paridad tiene n²?','Impar','n²=4k²+4k+1=2(2k²+2k)+1.',['Impar','Par','Depende de k']],
    ['c','Para demostrar por contradicción que √2 es irracional, ¿qué suponés?','Que √2 es racional','Se supone la negación de lo que se quiere concluir.',['Que √2 es racional','Que 2 es impar','Que √2 es negativo']],
    ['c','Si n² es impar, ¿n puede ser par?','No','Si n fuera par, n² también sería par.',['No','Sí']],
    ['c','Para probar “si n² es impar, n es impar” por contraposición, ¿qué desarrollo sirve?','n=2k implica n²=2(2k²)','Demostrá que si n fuera par, su cuadrado sería par; eso prueba la contrapositiva.',['n=2k implica n²=2(2k²)','n=2k+1 implica n² impar','Probar con n=1 y n=3']],
  ],
  'Predicados y universos': [
    ['c','P(x): x>2 sobre ℤ. ¿Cuánto vale P(3)?','V','3>2.',['V','F']],
    ['c','P(x): x>2 sobre ℤ. ¿Cuánto vale P(−1)?','F','−1 no supera 2.',['F','V']],
    ['c','¿Es P(x): x²=4 una proposición antes de fijar x?','No','El valor de verdad depende de x.',['No','Sí']],
    ['c','P(n): n es par. ¿Es P(0) verdadera con ℕ={0,1,…}?','Sí','0=2·0.',['Sí','No']],
    ['c','En ℤ, P(x): x²=x. ¿Es P(1) verdadera?','Sí','1²=1.',['Sí','No']],
    ['c','En ℤ, P(x): x²=x. ¿Es P(2) verdadera?','No','2²=4, que difiere de 2.',['No','Sí']],
    ['s','En U={−2,−1,0,1,2}, seleccioná los x que cumplen P(x): x²=x.','0,1','x²−x=x(x−1)=0: son exactamente 0 y 1.',['-2','-1','0','1','2']],
  ],
  'Universal y existencial': [
    ['c','U={1,2}. ¿Es verdadero ∃x∈U: x=2?','V','2 es testigo.',['V','F']],
    ['c','U={1,2}. ¿Es verdadero ∀x∈U: x>0?','V','Ambos son positivos.',['V','F']],
    ['c','U={1,2,3}. ¿Es verdadero ∀x∈U: x<3?','F','x=3 refuta la afirmación.',['F','V']],
    ['c','U={2,4,6}. ¿Es verdadero ∃x∈U: x impar?','F','Todos los elementos son pares.',['F','V']],
    ['l','P significa P(a), Q significa P(b). Expandí ∃x∈{a,b}:P(x).','P∨Q','Al menos uno de los dos casos.'],
    ['c','En ℤ, ¿es verdadero ∃x: x²=9?','V','x=3 y x=−3 son testigos.',['V','F']],
    ['c','U={−2,−1,0,1,2} y P(x): x²≤1. ¿Qué valores tienen ∀x P(x) y ∃x P(x)?','F y V','±2 refutan el universal; 0, ±1 sirven de testigo existencial.',['F y V','V y V','F y F']],
  ],
  'Negar y distribuir': [
    ['c','Negá “todos son mayores de 5”.','Alguno no es mayor de 5','¬∀ se transforma en ∃¬.',['Alguno no es mayor de 5','Nadie es mayor de 5','Alguno es mayor de 5']],
    ['c','Negá “alguien tiene 18 años”.','Nadie tiene 18 años','¬∃ se transforma en ∀¬.',['Nadie tiene 18 años','Todos tienen 18 años','Alguien no tiene 18 años']],
    ['c','Negá “todos aprobaron A y B”.','Alguien no aprobó A o no aprobó B','Negá el universal y luego la conjunción.',['Alguien no aprobó A o no aprobó B','Todos reprobaron A y B','Alguien aprobó A']],
    ['c','¿∀x(P(x)∧Q(x)) equivale a qué?','(∀x P(x))∧(∀x Q(x))','Todos cumplen ambos exactamente cuando todos cumplen cada propiedad.',['(∀x P(x))∧(∀x Q(x))','(∃x P(x))∧(∃x Q(x))']],
    ['c','¿∃x(P(x)∨Q(x)) equivale a qué?','(∃x P(x))∨(∃x Q(x))','Un testigo para alguna alternativa es suficiente.',['(∃x P(x))∨(∃x Q(x))','(∀x P(x))∨(∀x Q(x))']],
    ['c','Negá ∀x∈ℤ: x²≥0.','∃x∈ℤ: x²<0','La negación cambia ∀ por ∃ y ≥ por <; sigue siendo falsa.',['∃x∈ℤ: x²<0','∀x∈ℤ: x²<0','∃x∈ℤ: x²≥0']],
    ['c','Negá ∃x∀y: P(x,y).','∀x∃y: ¬P(x,y)','Cambiá cada cuantificador sin alterar el orden.',['∀x∃y: ¬P(x,y)','∃x∀y: ¬P(x,y)','∀y∃x: ¬P(x,y)']],
  ],
  'Cuantificadores anidados': [
    ['c','En ℤ, ¿es verdadero ∀x∃y: y=x+1?','V','Para cada x elegí y=x+1.',['V','F']],
    ['c','En ℤ, ¿es verdadero ∃y∀x: y=x+1?','F','Un y fijo no puede ser sucesor de todos los enteros.',['F','V']],
    ['c','En ℝ, ¿es verdadero ∀x∃y: y>x?','V','Elegí y=x+1.',['V','F']],
    ['c','En ℝ, ¿es verdadero ∃y∀x: y>x?','F','No existe máximo real: x=y+1 lo refuta.',['F','V']],
    ['c','En ℤ, ¿es verdadero ∃x∀y: x+y=y?','V','El testigo fijo x=0 funciona para todo y.',['V','F']],
    ['c','Negá ∀x∃y: x<y.','∃x∀y: x≥y','Conservá el orden y negá la desigualdad.',['∃x∀y: x≥y','∀y∃x: x≥y','∃y∀x: x≥y']],
    ['c','En ℕ={0,1,…}, ¿es verdadero ∀x∃y: x=2y?','F','x=1 es contraejemplo: es impar.',['F','V']],
  ],
  'Matrices y patrones': [
    ['t','Para A[m][n]=m+3n+4, calculá A[0][0].','4','0+0+4=4.'],
    ['t','Calculá A[1][0].','5','1+0+4=5.'],
    ['t','Calculá A[0][2].','10','0+6+4=10.'],
    ['t','¿Cuánto aumenta A al avanzar una fila?','1','m aumenta una unidad.'],
    ['t','Calculá A[5][3].','18','5+9+4=18.'],
    ['c','¿Pueden A[0][1] y A[3][0] coincidir?','Sí, ambas valen 7','0+3+4 y 3+0+4 son iguales.',['Sí, ambas valen 7','No, las posiciones son distintas']],
    ['t','Si A[m][n]=22 y m=6, ¿cuánto vale n?','4','6+3n+4=22; 3n=12.'],
  ],
  'Inferencias cuantificadas': [
    ['c','De ∀x P(x), ¿podés obtener P(a) si a está en el universo?','Sí','Instanciación universal.',['Sí','No']],
    ['c','De P(a), ¿podés obtener ∃x P(x)?','Sí','a sirve de testigo.',['Sí','No']],
    ['c','De P(a), ¿podés obtener ∀x P(x)?','No','Un ejemplo no cubre el universo.',['No','Sí']],
    ['c','De ∀x(P(x)→Q(x)) y P(a), ¿qué se deriva?','Q(a)','Instanciá la regla en a y aplicá modus ponens.',['Q(a)','∀x Q(x)','¬P(a)']],
    ['c','De ∀x(P(x)→Q(x)) y ¬Q(a), ¿qué se deriva?','¬P(a)','Instanciá y aplicá modus tollens.',['¬P(a)','P(a)','∀x ¬P(x)']],
    ['c','De ∃x P(x) y ∀x(P(x)→Q(x)), ¿qué se concluye?','∃x Q(x)','El testigo de P también cumple Q.',['∃x Q(x)','∀x Q(x)','Q(a) para cualquier a']],
    ['c','De ∃x P(x) y ∃x Q(x), ¿se puede inferir ∃x(P(x)∧Q(x))?','No','Los dos testigos pueden ser diferentes.',['No','Sí']],
  ],
  'Pertenencia e inclusión': [
    ['c','Si A={1,2}, ¿es 1∈A?','Sí','1 es uno de sus elementos.',['Sí','No']],
    ['c','Si A={1,2}, ¿es {1}⊆A?','Sí','Todo elemento de {1} pertenece a A.',['Sí','No']],
    ['c','Si A={1,2}, ¿es {1}∈A?','No','Los elementos de A son números, no el conjunto {1}.',['No','Sí']],
    ['c','¿Es A⊆A para cualquier conjunto A?','Sí','La inclusión es reflexiva.',['Sí','No']],
    ['c','Si A={∅}, ¿es ∅∈A?','Sí','A tiene al conjunto vacío como su único elemento.',['Sí','No']],
    ['t','¿Cuántos subconjuntos tiene {a,b,c}?','8','Cada elemento se incluye o no: 2³=8.'],
    ['c','Si A={1,{2}}, ¿es {2}⊆A?','No','2 no es elemento de A; {2} sí es un elemento.',['No','Sí']],
  ],
  'Operaciones con conjuntos': [
    ['c','A={1,2}, B={2,3}. ¿Cuál es A∩B?','{2}','Solo 2 está en ambos.',['{2}','{1,2,3}','{1,3}']],
    ['c','A={1,2}, B={2,3}. ¿Cuál es A∪B?','{1,2,3}','Reuní elementos sin repetirlos.',['{1,2,3}','{2}','{1,3}']],
    ['c','A={1,2}, B={2,3}. ¿Cuál es A−B?','{1}','Conservá los de A que no están en B.',['{1}','{3}','{1,3}']],
    ['c','A={1,2}, B={2,3}. ¿Cuál es A△B?','{1,3}','Quitá lo común a la unión.',['{1,3}','{2}','{1,2,3}']],
    ['c','Ω={1,2,3,4}, A={2,4}. ¿Cuál es Aᶜ?','{1,3}','Restá A del universo.',['{1,3}','{2,4}','∅']],
    ['c','A={1,2,3}, B={2,3,4}, C={3,4,5}. ¿Cuál es A∩B∩C?','{3}','3 es el único elemento de los tres.',['{3}','{2,3}','{3,4}']],
    ['s','A={1,2,3}, B={2,3,4}, C={3,4,5}. Seleccioná (A−B)∪(B∩C).','1,3,4','A−B={1}; B∩C={3,4}.',['1','2','3','4','5']],
  ],
  'Intervalos y fronteras': [
    ['c','¿Qué intervalo contiene 2 pero no 5?','[2,5)','El corchete incluye 2 y el paréntesis excluye 5.',['[2,5)','(2,5]','(2,5)']],
    ['c','¿Cuál expresa x>3?','(3,∞)','3 queda fuera; ∞ siempre lleva paréntesis.',['(3,∞)','[3,∞)','(−∞,3)']],
    ['c','¿Cuál expresa −1≤x≤2?','[−1,2]','Ambos extremos están incluidos.',['[−1,2]','(−1,2)','[−1,2)']],
    ['c','A=[0,4], B=[2,6]. ¿Cuál es A∩B?','[2,4]','La zona común incluye 2 y 4.',['[2,4]','[0,6]','(2,4)']],
    ['c','A=[0,4], B=[2,6]. ¿Cuál es A∪B?','[0,6]','Los intervalos se solapan.',['[0,6]','[2,4]','[0,2)∪(4,6]']],
    ['c','A=[0,4], B=[2,6]. ¿Cuál es A−B?','[0,2)','2 se quita porque está en B.',['[0,2)','[0,2]','(0,2)']],
    ['c','¿Cuál es (−∞,1]∩(−2,∞)?','(−2,1]','−2 queda fuera; 1 pertenece a ambos.',['(−2,1]','[−2,1)','(−∞,∞)']],
  ],
  'Venn y leyes de conjuntos': [
    ['c','¿Cuántas regiones tiene un diagrama de dos conjuntos, incluida la exterior?','4','Hay 2² patrones de pertenencia.',['4','3','8']],
    ['c','¿Qué es A∩Aᶜ?','∅','Nada puede estar dentro y fuera de A.',['∅','A','Ω']],
    ['c','¿Qué es A∪Aᶜ?','Ω','A y su complemento cubren el universo.',['Ω','∅','A']],
    ['c','¿Cuál es (A∪B)ᶜ?','Aᶜ∩Bᶜ','De Morgan: fuera de ambos.',['Aᶜ∩Bᶜ','Aᶜ∪Bᶜ','A∩B']],
    ['c','¿Cuál es (A∩B)ᶜ?','Aᶜ∪Bᶜ','No estar en ambos equivale a faltar en al menos uno.',['Aᶜ∪Bᶜ','Aᶜ∩Bᶜ','A∪B']],
    ['c','¿Cuántas regiones tiene un diagrama de tres conjuntos, incluida la exterior?','8','Hay 2³ patrones.',['8','6','7']],
    ['s','Con códigos ABC, seleccioná las regiones de (A∪B)−C.','100,010,110','A o B deben ser 1 y C debe ser 0; incluí la intersección A∩B fuera de C.',['000','100','010','001','110','101','011','111']],
  ],
  'Aplicaciones e inclusión-exclusión': [
    ['t','|A|=8, |B|=7, |A∩B|=3. Calculá |A∪B|.','12','8+7−3=12.'],
    ['t','De 20 personas, 14 usan A y 6 no usan A. ¿Cuántas usan A?','14','Es el dato del enunciado; comprobá 14+6=20.'],
    ['t','|A|=12 y |A∩B|=5. ¿Cuántos están solo en A?','7','12−5=7.'],
    ['t','En 30 personas, |A∪B|=23. ¿Cuántas están fuera de ambos?','7','30−23=7.'],
    ['t','|A|=18, |B|=15, |A∪B|=27. Calculá |A∩B|.','6','18+15−27=6.'],
    ['t','|A|=10, |B|=12, |C|=8; pares 3,4,2 y triple 1. Hallá |A∪B∪C|.','22','10+12+8−3−4−2+1=22.'],
    ['t','En un grupo de 40, 22 estudian A, 19 B y 9 ambos. ¿Cuántos estudian exactamente uno?','23','Solo A=13, solo B=10; total 23.'],
  ],
};

export function addLessonPractice(lessons: Lesson[]): void {
  for (const lesson of lessons) {
    const seeds = practice[lesson.title];
    if (!seeds || seeds.length !== 7) continue;
    const added: Question[] = seeds.map(([kind, prompt, answer, explanation, options], i) => ({
      id: `${lesson.id}-extra${i+1}`, type: ({ c:'choice', t:'text', a:'algebra', l:'logic', s:'set' } as Record<string,QuestionType>)[kind],
      prompt, answer: kind === 's' ? answer.split(',') : answer, explanation,
      ...(kind === 's' ? { universe: options } : { options }), hints: ['Identificá la regla y resolvé un paso a la vez.', explanation],
      tag: lesson.title, difficulty: i < 2 ? 1 : i < 5 ? 2 : 3,
      ...(kind === 'a' && lesson.title === 'Conjuntos numéricos' && prompt.includes('fracción irreducible') ? { requiredForm: 'irreducibleFraction' as const } : {}),
      ...(kind === 'a' && /^Factorizá/.test(prompt) ? { requiredForm: lesson.title === 'Factorización completa' ? 'linearFactors' as const : 'factored' as const } : {}),
    }));
    // Short starters, guided practice, original lesson questions, final challenges.
    // Preserve existing question IDs so saved progress still points to the same work.
    lesson.questions = [...added.slice(0, 5), ...lesson.questions, ...added.slice(5)]
      .sort((a,b) => a.difficulty-b.difficulty ||
        (a.difficulty === 2 ? Number(a.id.includes('-extra'))*-1 - Number(b.id.includes('-extra'))*-1 : 0));
    lesson.minutes = 15;
  }
}
