import { useState } from 'react';
import { ArrowRight, BookOpen, Search } from 'lucide-react';
import katex from 'katex';
import { lessons } from './content';
import type { Course, Lesson } from './types';
import { Laws } from './Workbench';
import { TopicIcon } from './TopicIcon';
import { readerPages } from './bookIndex';
import { bookScope } from './bookScope';
const symbols=[['¬','Negación','Cambia V por F y F por V.'],['∧','Conjunción','Verdadera solo cuando ambas partes son verdaderas.'],['∨','Disyunción inclusiva','Verdadera cuando al menos una parte es verdadera.'],['⊻','Disyunción exclusiva','Verdadera cuando exactamente una parte es verdadera.'],['→','Implicación','Falsa solo si el antecedente es V y el consecuente F.'],['↔','Bicondicional','Verdadera cuando ambos valores coinciden.'],['∀','Universal','Exige todos los elementos del universo.'],['∃','Existencial','Exige al menos un testigo.'],['∈','Pertenencia','Un elemento está dentro de un conjunto.'],['⊆','Inclusión','Todos los elementos de un conjunto pertenecen al otro.'],['∪','Unión','Elementos que están en al menos uno de los conjuntos.'],['∩','Intersección','Elementos que están en ambos conjuntos.']];
export function Library({course,onPractice,onRead}:{course:Course;onPractice:(l:Lesson)=>void;onRead:(page:number)=>void}) {
  const [search,setSearch]=useState(''),[week,setWeek]=useState('Todas'),[selected,setSelected]=useState<string|null>(null),[showRules,setShowRules]=useState(false),[glossary,setGlossary]=useState(false);
  const path=lessons.filter(l=>l.course===course),weeks=[...new Set(path.map(l=>l.unit.split(' · ')[0]))];const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const filtered=path.filter(l=>(week==='Todas'||l.unit.startsWith(week))&&norm(`${l.title} ${l.theory.join(' ')}`).includes(norm(search)));const reading=path.find(l=>l.id===selected);
  return <div className="reading-library"><span className="eyebrow">LEÉ · ENTENDÉ · PROBÁ</span><h1>Una idea a la vez.</h1><p>Cuando algo no queda claro, volvé a la explicación y seguí un ejemplo completo. No hace falta acertar para entrar aquí.</p>
    <section className="card scope-card"><span className="eyebrow">ALCANCE ACTUAL</span><h2>{bookScope[course].label}</h2><p>{bookScope[course].explanation}</p></section><div className="library-search"><label><Search size={18}/><input aria-label="Buscar en la biblioteca" placeholder="Buscá De Morgan, fracciones, cuantificadores…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filtrar por semana o bloque" value={week} onChange={e=>setWeek(e.target.value)}><option>Todas</option>{weeks.map(w=><option key={w}>{w}</option>)}</select></div><div className="row wrap" style={{marginBottom:22}}><button className="secondary" onClick={()=>setShowRules(true)}><BookOpen size={16}/>Leyes y reglas</button><button className="secondary" onClick={()=>setGlossary(!glossary)}>Diccionario de símbolos</button></div>
    {glossary&&<section className="card"><h2>¿Qué significa ese símbolo?</h2>{symbols.map(([s,name,text])=><div className="glossary-row" key={s}><b>{s}</b><div><strong>{name}</strong><p>{text}</p></div></div>)}</section>}
    {reading?<article className="card reading-article"><button className="text-button" onClick={()=>setSelected(null)}>← Volver a los temas</button><span className="eyebrow">{reading.unit}</span><h2><TopicIcon name={reading.icon} size={22}/> {reading.title}</h2><h3>La idea</h3>{reading.theory.map(t=><p key={t}>{t}</p>)}<div className="formula-box">{reading.formulas.map(f=><div className="math" key={f} dangerouslySetInnerHTML={{__html:katex.renderToString(f,{throwOnError:false,strict:false,displayMode:true})}}/>)}</div><h3>Ejemplo resuelto</h3><p>Seguí los pasos. Observá qué operación o ley permite avanzar.</p><div className="example">{reading.example.steps.map((s,i)=><div key={s}><span>{i+1}</span><p>{s}</p></div>)}</div><h3>Más ejercicios explicados</h3>{reading.questions.map((q,i)=><details className="solved-question" key={q.id}><summary>Ejercicio {i+1} · {q.prompt}</summary><p><b>Respuesta:</b> {Array.isArray(q.answer)?q.answer.join(q.type==='order'?' → ':', '):q.answer}</p>{q.exclusions&&<p><b>Restricciones:</b> {q.exclusions.join(', ')}</p>}<p><b>Por qué:</b> {q.explanation}</p><small>Ejercicio adaptado del banco. Practicá más tarde sin mirar la solución.</small></details>)}<div className="row wrap"><button className="primary" onClick={()=>onPractice(reading)}>Ahora lo intento yo<ArrowRight size={18}/></button><button className="secondary" onClick={()=>setShowRules(true)}>Consultar leyes</button></div><p className="source-note">{reading.source} · páginas {reading.pages}. Explicación adaptada; las páginas originales del libro están abajo.</p></article>:<><div className="library-topics">{filtered.map(l=><button className="library-topic" key={l.id} onClick={()=>{setSelected(l.id);window.scrollTo(0,0);}}><span><TopicIcon name={l.icon}/></span><div><small>{l.unit.split(' · ')[0]}</small><h3>{l.title}</h3><p>Explicación · ejemplo resuelto · {l.questions.length} soluciones comentadas</p></div><ArrowRight size={17}/></button>)}</div>{!filtered.length&&<p className="notice">No encontré ese término. Probá otro nombre o quitá el filtro de semana.</p>}</>}
    <section className="card"><span className="eyebrow">DEL LIBRO ORIGINAL</span><h2>Leé los ejemplos tal como aparecen.</h2><p>Estos accesos abren tu PDF privado en la página correspondiente. Ahí verás el texto, las fórmulas y los ejemplos resueltos originales.</p><div className="topic-list">{readerPages[course].map(r=><button key={r.title} onClick={()=>onRead(r.page)}><BookOpen size={16}/><span>{r.title}<small style={{display:'block'}}>Páginas PDF {r.page}–{r.end}</small></span><ArrowRight size={16}/></button>)}</div></section>{showRules&&<Laws onClose={()=>setShowRules(false)}/>}</div>;
}
