import { useState } from 'react';
import { ArrowRight, Bookmark, CalendarDays, Clock, Lightbulb, RefreshCw, Target, WandSparkles } from 'lucide-react';
import { lessons } from './content';
import type { Lesson, Progress } from './types';
import { bank, dailyChallenge, latestAttempts, mistakeJournal, practicePlan, type PracticeItem } from './learning';
import { dayKey } from './progress';
import { TopicIcon } from './TopicIcon';
import { MathExpression } from './MathExpression';
import { BookPractice } from './BookPractice';
import { BookExam } from './BookExam';
import { ExamLobby } from './ExamLobby';
interface Props { progress:Progress;onStart:(items:PracticeItem[],title:string,mode:string)=>void;onExam:(units:string[])=>void;onLesson:(l:Lesson)=>void;onExplore:()=>void;onRead:(page:number)=>void; }
export function PracticeHub({progress:p,onStart,onExam,onLesson,onExplore,onRead}:Props) {
  const [count,setCount]=useState(3),[unit,setUnit]=useState('all'),[difficulty,setDifficulty]=useState('all'),[view,setView]=useState<'practice'|'errors'>('practice'),[revealed,setRevealed]=useState<string[]>([]),[source,setSource]=useState('all'),[examOpen,setExamOpen]=useState(false);
  const items=bank(lessons,p.course),units=[...new Set(items.map(i=>i.lesson.unit))],last=latestAttempts(p),journal=mistakeJournal(items,p);
  const visited=new Set(p.attempts.map(a=>a.lessonId)),seenUnits=units.filter((u,i)=>i===0||lessons.some(l=>l.course===p.course&&l.unit===u&&(p.completed.includes(l.id)||visited.has(l.id))));
  const pool=items.filter(i=>(source==='all'||!!i.question.bookSource)&&(unit==='all'||i.lesson.unit===unit)&&(difficulty==='all'||i.question.difficulty===Number(difficulty)));
  const plan=practicePlan(pool,p,count),daily=dailyChallenge(items,p.course);
  const todayDone=new Set(p.attempts.filter(a=>a.correct&&dayKey(new Date(a.date))===dayKey()).map(a=>a.questionId));
  const dailyDone=daily.filter(i=>todayDone.has(i.question.id)).length;
  const errors=items.filter(i=>{const a=last.get(i.question.id);return a&&(!a.correct||a.assisted);});
  const due=items.filter(i=>p.skills[i.question.id]&&Date.parse(p.skills[i.question.id].due)<=Date.now());
  function retry(item:PracticeItem) {onStart([item],`Volver a entender · ${item.lesson.title}`,'errors');}
  return <div className="practice-hub"><span className="eyebrow">PRÁCTICA QUE SE ADAPTA A VOS</span><h1>Tu tiempo. Tu siguiente paso.</h1><p>Una sesión corta también cuenta. Elegí qué querés trabajar y salí con una idea más clara.</p>
    <div className="hub-tabs" role="group" aria-label="Vista de práctica"><button aria-pressed={view==='practice'} className={view==='practice'?'active':''} onClick={()=>setView('practice')}><WandSparkles size={18}/>Mi práctica</button><button aria-pressed={view==='errors'} className={view==='errors'?'active':''} onClick={()=>setView('errors')}><Lightbulb size={18}/>Diario de errores<span>{journal.length}</span></button></div>
    {view==='practice'?<>
      <section className="exam-promo"><div className="exam-promo-art"><Target size={40}/><span>35</span></div><div><span className="eyebrow">NUEVO · MODO EXAMEN</span><h2>El examen llegó al aula.</h2><p>35 desafíos nuevos de los temas que ya viste. Incluye argumentos de varias líneas, traducción a símbolos y soluciones explicadas.</p><button className="primary" onClick={()=>setExamOpen(true)}>Entrar al examen<ArrowRight size={18}/></button></div></section>
      <BookExam key={p.course} course={p.course} items={items.filter(i=>i.question.bookSource)} progress={p} onStart={onStart} onRead={onRead}/>
      <BookPractice items={items.filter(i=>i.question.bookSource)} progress={p} count={count} onStart={onStart}/>
      <section className="card session-builder"><div className="row"><div><span className="eyebrow">HECHO PARA EL BUS</span><h2>Armá tu próxima sesión.</h2></div><Clock size={28}/></div><div className="session-lengths" role="group" aria-label="Cantidad de ejercicios">{[[3,'Un ratito','3 ejercicios'],[8,'Una pausa','8 ejercicios'],[15,'Con calma','15 ejercicios']].map(([n,name,text])=><button key={n} className={count===n?'selected':''} aria-pressed={count===n} onClick={()=>setCount(Number(n))}><b>{name}</b><small>{text}</small></button>)}</div>
      <div className="builder-filters"><label>Banco<select aria-label="Banco de ejercicios" value={source} onChange={e=>setSource(e.target.value)}><option value="all">Toda la práctica</option><option value="book">Solo ejercicios del libro</option></select></label><label>Tema<select aria-label="Tema" value={unit} onChange={e=>setUnit(e.target.value)}><option value="all">Todos los temas del curso</option>{units.map(u=><option key={u}>{u}</option>)}</select></label><label>Dificultad<select aria-label="Dificultad" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="all">Variada</option><option value="1">Bases</option><option value="2">Conectar ideas</option><option value="3">Desafío</option></select></label></div>
      <div className="plan-preview"><span className="eyebrow">ASÍ VAMOS A PRACTICAR</span>{plan.length?<><p>Primero repasos vencidos y errores; después conceptos nuevos.</p><div>{plan.map(i=><span key={i.question.id}><TopicIcon name={i.lesson.icon} size={16}/>{i.lesson.title}</span>)}</div></>:<p>No hay preguntas con esta combinación. Probá otra dificultad.</p>}</div><button className="primary wide" disabled={!plan.length} onClick={()=>onStart(plan,'Mi práctica personalizada','adaptive')}>Empezar {plan.length} ejercicios<ArrowRight size={18}/></button><small>Sin cronómetro. Tu ritmo importa más que la velocidad.</small></section>
      <div className="challenge-row"><section className="card daily-challenge"><CalendarDays size={24}/><span className="eyebrow">RETO DEL DÍA</span><h2>Cinco conexiones nuevas.</h2><p>Los mismos 5 ejercicios durante el día, para que podás terminar en varias pausas.</p><div className="daily-dots" aria-label={`${dailyDone} de ${daily.length} completados`}>{daily.map(i=><span key={i.question.id} className={todayDone.has(i.question.id)?'done':''}/>)}</div><button className="secondary" onClick={()=>onStart(daily,'Reto del día','daily')}>{dailyDone===daily.length?'Volver a practicar':'Abrir mi reto'}<ArrowRight size={16}/></button></section><section className="card explore-promo"><WandSparkles size={24}/><span className="eyebrow">TOCÁ Y ENTENDÉ</span><h2>Las ideas se pueden ver.</h2><p>{p.course==='discreta'?'Cambiá P y Q y descubrí cuándo una expresión es verdadera.':'Mové los coeficientes y mirá cómo cambian las raíces y la gráfica.'}</p><button className="secondary" onClick={onExplore}>Abrir explorador<ArrowRight size={16}/></button></section></div>
      <div className="practice-grid">{[{id:'review',icon:RefreshCw,title:'Repaso espaciado',text:`${due.length} ejercicios pendientes`,pool:due},{id:'errors',icon:Lightbulb,title:'Mis errores',text:`${errors.length} ejercicios por afianzar`,pool:errors}].map(m=><button className="practice-card" key={m.id} disabled={!m.pool.length} onClick={()=>onStart(m.pool.slice(0,count),m.title,m.id)}><m.icon size={28}/><h3>{m.title}</h3><p>{m.text}</p><b>{m.pool.length?'Empezar':'Al día'}<ArrowRight size={16}/></b></button>)}</div>
      {(p.favorites||[]).length>0&&<section className="card"><h2><Bookmark size={20}/> Mis temas guardados</h2><div className="topic-list">{lessons.filter(l=>l.course===p.course&&p.favorites?.includes(l.id)).map(l=><button key={l.id} onClick={()=>onLesson(l)}><TopicIcon name={l.icon} size={18}/>{l.title}<ArrowRight size={16}/></button>)}</div></section>}
      <h2>Práctica por tema</h2>{units.map(u=><details className="card practice-unit" key={u}><summary>{u}<span>{items.filter(i=>i.lesson.unit===u).length} ejercicios</span></summary><div className="topic-list">{lessons.filter(l=>l.course===p.course&&l.unit===u).map(l=><button key={l.id} onClick={()=>onLesson(l)}><TopicIcon name={l.icon} size={18}/>{l.title}<ArrowRight size={16}/></button>)}</div></details>)}
    </>:<><section className="card journal-intro"><Lightbulb size={24}/><h2>Un error que entendés deja de ser un obstáculo.</h2><p>Compará lo que escribiste con la explicación. Después resolvé otra vez, sin abrir la respuesta.</p></section>{journal.length?journal.slice(0,30).map(i=><article className="card mistake-card" key={i.question.id}><div className="row"><span className="eyebrow">{i.lesson.title}</span><span className={`status-chip ${i.resolved?'resolved':''}`}>{i.resolved?'Resuelto sin ayuda':'Por afianzar'}</span></div><h3>{i.question.prompt}</h3><div className="submitted-answer"><small>Tu respuesta en ese intento</small><code>{i.attempt.answer===undefined?'Este intento antiguo no guardó la respuesta.':Array.isArray(i.attempt.answer)?i.attempt.answer.join(' · ')||'∅':i.question.type==='algebra'?<MathExpression value={i.attempt.answer}/>:i.attempt.answer}</code>{i.attempt.exclusions?.length? <small>Restricciones: {i.attempt.exclusions.join(', ')}</small>:null}</div>{i.attempt.error&&<p className="notice">{i.attempt.error}</p>}
      {revealed.includes(i.question.id)&&<div className="journal-explanation"><b>Una forma correcta:</b><code>{Array.isArray(i.question.answer)?i.question.answer.join(' · '):i.question.type==='algebra'?<MathExpression value={i.question.answer}/>:i.question.answer}</code>{i.question.exclusions&&<p>Restricciones: {i.question.exclusions.join(', ')}</p>}<p>{i.question.explanation}</p></div>}<div className="row wrap"><button className="secondary" aria-expanded={revealed.includes(i.question.id)} onClick={()=>setRevealed(ids=>ids.includes(i.question.id)?ids.filter(id=>id!==i.question.id):[...ids,i.question.id])}>{revealed.includes(i.question.id)?'Ocultar explicación':'Entender mi error'}</button><button className="primary" onClick={()=>retry(i)}>Volver a intentarlo<ArrowRight size={16}/></button></div></article>):<div className="card empty-state"><Lightbulb size={32}/><h2>Tu diario está listo.</h2><p>Los errores aparecerán acá con tu respuesta y una explicación. No quitan vidas ni te bloquean.</p></div>}</>}
    {examOpen&&<ExamLobby units={units} defaultUnits={seenUnits} onClose={()=>setExamOpen(false)} onStart={selected=>{setExamOpen(false);onExam(selected);}}/>}
  </div>;
}
