import { useState } from 'react';
import { BookOpen } from 'lucide-react';
import { checkInference, inference } from './laws';
import { equivalentLogic } from './engine';
import { SymbolInput } from './Keyboard';
import { Laws } from './Workbench';
import { useDraft, validText } from './drafts';
export function Proof(){
  const [premises,setPremises]=useDraft('mate-proof-premises',['P→Q','P'],v=>Array.isArray(v)&&v.length>0&&v.length<=6&&v.every(validText));const [editing,setEditing]=useState(0);const [goal,setGoal]=useDraft('mate-proof-goal','Q',validText);const [lines,setLines]=useDraft<{expr:string;law:string;refs:number[]}[]>('mate-proof-lines',[],v=>Array.isArray(v)&&v.length<200&&v.every(x=>x&&validText(x.expr)&&validText(x.law)&&Array.isArray(x.refs)&&x.refs.every((n:unknown)=>Number.isInteger(n)&&Number(n)>=0&&Number(n)<206)));const [next,setNext]=useDraft('mate-proof-next','',validText);const [law,setLaw]=useState('Modus ponens');const [refs,setRefs]=useState<number[]>([]);const [message,setMessage]=useState('');const [show,setShow]=useState(false);
  const expressions=[...premises,...lines.map(l=>l.expr)];let finished=false;try{finished=!!lines.length&&equivalentLogic(lines.at(-1)!.expr,goal);}catch{}
  function add(){if(!checkInference(refs.map(i=>expressions[i]),next,law)){setMessage('La conclusión no se obtiene de esas líneas con la regla elegida. Revisá las referencias y la forma de la regla.');return;}setLines([...lines,{expr:next,law,refs}]);setNext('');setRefs([]);setMessage('Inferencia verificada.');}
  return <section className="card"><div className="row wrap"><div><span className="eyebrow">DEMOSTRACIONES</span><h2>De las premisas a la conclusión.</h2></div><button className="secondary" onClick={()=>setShow(true)}><BookOpen size={16}/>Ver reglas</button></div><p>Seleccioná las líneas que usás, construí la siguiente y elegí la regla. Cada inferencia se comprueba.</p>
    {!lines.length&&<><div className="set-options">{premises.map((_,i)=><button className={editing===i?'selected':''} key={i} onClick={()=>setEditing(i)}>Premisa {i+1}</button>)}{premises.length<6&&<button onClick={()=>{setPremises([...premises,'']);setEditing(premises.length);}}>+ Premisa</button>}</div><SymbolInput value={premises[editing]} onChange={s=>setPremises(premises.map((v,i)=>i===editing?s:v))} label={`Premisa ${editing+1}`}/><SymbolInput value={goal} onChange={setGoal} label="Conclusión que quiero demostrar"/></>}
    {expressions.map((expr,i)=><div className="proof-line" key={i}><span>{i+1}</span><code>{expr||'…'}</code><small>{i<premises.length?'Premisa':`${lines[i-premises.length].law} · ${lines[i-premises.length].refs.map(r=>r+1).join(',')}`}</small></div>)}
    <p className="notice">Objetivo: {goal}{finished?' · ¡Conclusión alcanzada!':''}</p><SymbolInput value={next} onChange={setNext} label="Nueva conclusión"/><label>Regla aplicada<select value={law} onChange={e=>setLaw(e.target.value)}>{inference.map(([name])=><option key={name}>{name}</option>)}</select></label><p style={{marginTop:18,marginBottom:5}}>Líneas que uso (hasta 3):</p><div className="set-options">{expressions.map((_,i)=><button key={i} aria-label={`Usar línea ${i+1}`} className={refs.includes(i)?'selected':''} onClick={()=>setRefs(refs.includes(i)?refs.filter(r=>r!==i):refs.length<3?[...refs,i]:refs)}>{i+1}</button>)}</div><div className="row wrap"><button className="primary" disabled={!next||!refs.length} onClick={add}>Comprobar inferencia</button><button className="secondary" onClick={()=>{setLines([]);setRefs([]);setNext('');setMessage('');}}>Reiniciar</button></div><p className="notice" role="status">{message}</p><small>Verifica las diez reglas mostradas. Para equivalencias, usá el cuaderno de transformaciones de arriba. Los cuantificadores no se verifican con este motor proposicional.</small>{show&&<Laws onClose={()=>setShow(false)}/>}</section>;
}
