import { useState } from 'react';
import { BookOpen } from 'lucide-react';
import { checkInference, inference } from './laws';
import { equivalentLogic } from './engine';
import { SymbolInput } from './Keyboard';
import { Laws } from './Workbench';
import { useDraft, validText } from './drafts';
export function Proof({draftPrefix='mate-proof',initialPremises=['P→Q','P'],initialGoal='Q',onUseLine}:{draftPrefix?:string;initialPremises?:string[];initialGoal?:string;onUseLine?:(line:string,reason:string)=>void}={}){
  const [premises,setPremises]=useDraft(`${draftPrefix}-premises`,initialPremises,v=>Array.isArray(v)&&v.length>0&&v.length<=6&&v.every(validText));const [editing,setEditing]=useState(0);const [goal,setGoal]=useDraft(`${draftPrefix}-goal`,initialGoal,validText);const [lines,setLines]=useDraft<{expr:string;law:string;refs:number[]}[]>(`${draftPrefix}-lines`,[],v=>Array.isArray(v)&&v.length<200&&v.every(x=>x&&validText(x.expr)&&validText(x.law)&&Array.isArray(x.refs)&&x.refs.every((n:unknown)=>Number.isInteger(n)&&Number(n)>=0&&Number(n)<206)));const [next,setNext]=useDraft(`${draftPrefix}-next`,'',validText);const [law,setLaw]=useState('Modus ponens');const [refs,setRefs]=useState<number[]>([]);const [message,setMessage]=useState('');const [show,setShow]=useState(false);
  const expressions=[...premises,...lines.map(l=>l.expr)];let finished=false;try{finished=!!lines.length&&equivalentLogic(lines.at(-1)!.expr,goal);}catch{}
  function add(){if(premises.some(x=>!x.trim())||!goal.trim()){setMessage('Completá todas las premisas y el objetivo antes de comprobar.');return;}if(!checkInference(refs.map(i=>expressions[i]),next,law)){setMessage('La conclusión no se obtiene de esas líneas con la regla elegida. Revisá las referencias y la forma de la regla.');return;}setLines([...lines,{expr:next,law,refs}]);setNext('');setRefs([]);setMessage('Inferencia verificada.');}
  return <section className="card proof-pad"><div className="row wrap"><div><span className="eyebrow">INFERENCIAS</span><h2>De las premisas a la conclusión.</h2></div><button className="secondary" onClick={()=>setShow(true)}><BookOpen size={16}/>Ver reglas</button></div><ol className="workbench-guide"><li>Editá las premisas y escribí el objetivo.</li><li>Tocá los números de las líneas que vas a usar.</li><li>Escribí la conclusión de ese paso, elegí la regla y comprobala.</li></ol><p>{initialGoal?'Ejemplo inicial: de P→Q y P se obtiene Q por modus ponens. Podés reemplazarlo con tus propias premisas.':'Comenzá copiando las premisas y la conclusión de este ejercicio. Esta hoja verifica inferencias proposicionales; tu desarrollo libre queda aparte.'}</p>
    {!lines.length&&<><div className="set-options">{premises.map((_,i)=><button className={editing===i?'selected':''} aria-pressed={editing===i} key={i} onClick={()=>setEditing(i)}>Premisa {i+1}</button>)}{premises.length<6&&<button onClick={()=>{setPremises([...premises,'']);setEditing(premises.length);}}>+ Premisa</button>}{premises.length>1&&<button onClick={()=>{setPremises(premises.filter((_,i)=>i!==editing));setEditing(Math.max(0,editing-1));setMessage('Premisa eliminada.');}}>Quitar premisa {editing+1}</button>}</div><SymbolInput compact value={premises[editing]} onChange={s=>setPremises(premises.map((v,i)=>i===editing?s:v))} label={`Premisa ${editing+1}`}/><SymbolInput compact value={goal} onChange={setGoal} label="Conclusión que quiero demostrar"/></>}
    {expressions.map((expr,i)=><div className="proof-line" key={i}><span>{i+1}</span><code>{expr||'…'}</code><small>{i<premises.length?'Premisa':`${lines[i-premises.length].law} · ${lines[i-premises.length].refs.map(r=>r+1).join(',')}`}</small></div>)}
    <p className="notice">Objetivo: {goal}{finished?' · ¡Conclusión alcanzada con pasos comprobados!':''}</p><SymbolInput value={next} onChange={setNext} label="Nueva conclusión"/><label>Regla aplicada<select value={law} onChange={e=>setLaw(e.target.value)}>{inference.map(([name])=><option key={name}>{name}</option>)}</select></label><p style={{marginTop:18,marginBottom:5}}>Usá hasta tres líneas anteriores:</p><div className="set-options">{expressions.map((_,i)=><button key={i} type="button" aria-label={`Usar línea ${i+1}`} aria-pressed={refs.includes(i)} className={refs.includes(i)?'selected':''} onClick={()=>setRefs(refs.includes(i)?refs.filter(r=>r!==i):refs.length<3?[...refs,i]:refs)}>{i+1}</button>)}</div><div className="row wrap"><button className="primary" disabled={!next.trim()||!refs.length} onClick={add}>Comprobar inferencia</button>{lines.length>0&&<button className="secondary" onClick={()=>{const last=lines.at(-1)!;setLines(lines.slice(0,-1));setNext(last.expr);setLaw(last.law);setRefs(last.refs);setMessage('Última inferencia lista para corregir.');}}>Corregir última línea</button>}<button className="secondary" onClick={()=>{setLines([]);setRefs([]);setNext('');setMessage('Ahora podés editar las premisas y empezar otra demostración.');}}>Borrar pasos</button></div><p className="notice" role="status">{message}</p>{onUseLine&&lines.length>0&&<button type="button" className="secondary workbench-copy" onClick={()=>{const last=lines.at(-1)!;onUseLine(last.expr,`${last.law}; líneas ${last.refs.map(r=>r+1).join(', ')}`);}}>Copiar última inferencia a mi desarrollo</button>}<small>Comprueba las diez reglas mostradas. Para equivalencias, elegí «Equivalencias» arriba. Este motor no valida inferencias con cuantificadores.</small>{show&&<Laws onClose={()=>setShow(false)}/>}</section>;
}
