import { useState } from 'react';
import { BookOpen, Check, Plus, RotateCcw } from 'lucide-react';
import { SymbolInput } from './Keyboard';
import { checkLaw, laws, inference } from './laws';
import { equivalentAlgebra, classify, truthRows } from './engine';
import { useDraft, validText } from './drafts';
export function Laws({onClose}:{onClose:()=>void}) { return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Leyes y reglas" onClick={e=>e.stopPropagation()}><div className="row"><h2>Tu caja de herramientas</h2><button autoFocus onClick={onClose} aria-label="Cerrar leyes">✕</button></div><p>Las leyes transforman expresiones equivalentes. Las inferencias derivan conclusiones desde premisas.</p><h3>Leyes lógicas</h3>{laws.map(l=><div className="law" key={l.name}><b>{l.name}</b>{l.patterns.map(([a,b])=><code key={a}>{a} ≡ {b}</code>)}<small>{l.text}</small></div>)}<h3>Reglas de inferencia</h3>{inference.map(([name,pattern])=><div className="law" key={name}><b>{name}</b><code>{pattern}</code></div>)}<button className="primary" onClick={onClose}>Volver al ejercicio</button></section></div>; }
export function Workbench({initial='¬(P∧Q)',compact=false,initialMode='logic',draftPrefix='mate-draft'}:{initial?:string;compact?:boolean;initialMode?:'logic'|'algebra';draftPrefix?:string}) {
  const [mode,setMode]=useDraft<'logic'|'algebra'>(`${draftPrefix}-mode`,initialMode,v=>v==='logic'||v==='algebra');const [start,setStart,draftError]=useDraft(`${draftPrefix}-start`,initialMode==='algebra'?'(x^2-1)/(x-1)':initial,validText);const [lines,setLines]=useDraft<{expr:string;law:string}[]>(`${draftPrefix}-lines`,[],v=>Array.isArray(v)&&v.length<200&&v.every(x=>x&&validText(x.expr)&&validText(x.law)));const [next,setNext]=useDraft(`${draftPrefix}-next`,'',validText);const [law,setLaw]=useState('De Morgan');const [message,setMessage]=useState('');const [showLaws,setShowLaws]=useState(false);const [table,setTable]=useState(false);
  const current=lines.at(-1)?.expr||start;
  function add() { try { const ok=mode==='logic'?checkLaw(current,next,law):equivalentAlgebra(current,next); if(!ok){setMessage(mode==='logic'?'Ese paso no coincide con la ley elegida. Puede requerir otra ley, otro orden o más de un paso.':'Las dos expresiones no son equivalentes. Revisá signos y factores.');return;}setLines([...lines,{expr:next,law:mode==='logic'?law:'Equivalencia algebraica'}]);setNext('');setMessage('Paso verificado.'); }catch(e){setMessage(String(e instanceof Error?e.message:e));} }
  let rows: ReturnType<typeof truthRows>=[],error=''; if(table)try{rows=truthRows(current);if(rows.length>16){rows=[];error='Para esta vista usá hasta cuatro variables.';}}catch(e){error=e instanceof Error?e.message:'';}
  return <section className={`card workbench ${compact?'compact':''}`}><div className="row"><div><span className="eyebrow">CUADERNO TÁCTIL</span><h2>Un paso. Una razón.</h2></div><button className="secondary" onClick={()=>setShowLaws(true)}><BookOpen size={16}/>Ver leyes</button></div><p>Escribí una transformación con el teclado y elegí la ley. Podés intentarlo todas las veces que necesités.</p>
    {draftError&&<p role="alert">{draftError}</p>}<small>Borrador guardado en este dispositivo. Cambiar de modo reinicia la zona de trabajo.</small><div className="segments"><button className={mode==='logic'?'active':''} onClick={()=>{setMode('logic');setLines([]);setStart(initial);setNext('');setTable(false);}}>Lógica</button><button className={mode==='algebra'?'active':''} onClick={()=>{setMode('algebra');setLines([]);setStart('(x^2-1)/(x-1)');setNext('');setTable(false);}}>Álgebra</button></div>
    {lines.length===0?<SymbolInput compact={compact} value={start} onChange={setStart} mode={mode} label="Expresión inicial"/>:<div className="proof-line"><span>0</span><code>{start}</code><small>Inicio</small></div>}
    {lines.map((l,i)=><div className="proof-line" key={i}><span>{i+1}</span><code>{l.expr}</code><small><Check size={14}/>{l.law}</small></div>)}
    <SymbolInput value={next} onChange={setNext} mode={mode} label="Siguiente paso"/>{mode==='logic'&&<label>Ley aplicada<select value={law} onChange={e=>setLaw(e.target.value)}>{laws.map(l=><option key={l.name}>{l.name}</option>)}</select></label>}
    <div className="row wrap"><button className="primary" disabled={!next||!start} onClick={add}><Plus size={18}/>Comprobar paso</button><button className="secondary" onClick={()=>{setLines([]);setNext('');setMessage('');}}><RotateCcw size={16}/>Reiniciar</button>{mode==='logic'&&<button className="secondary" onClick={()=>setTable(!table)}>Tabla de verdad</button>}</div><p role="status" className="notice">{message}</p>
    {mode==='algebra'&&<small>Compara identidad algebraica; no comprueba el método ni el dominio. Conservá tus restricciones en el ejercicio.</small>}
    {table&&<div className="table-scroll">{error?<p>{error}</p>:<><p>{classify(current)}</p><table><thead><tr>{Object.keys(rows[0]?.values||{}).map(v=><th key={v}>{v}</th>)}<th>{current}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{Object.values(r.values).map((v,j)=><td key={j}>{v?'V':'F'}</td>)}<td>{r.result?'V':'F'}</td></tr>)}</tbody></table></>}</div>}{showLaws&&<Laws onClose={()=>setShowLaws(false)}/>}</section>;
}
